src/unix/aix.c
src/unix/darwin.c
src/unix/freebsd.c
src/unix/linux-core.c
src/unix/netbsd.c
src/unix/openbsd.c
src/unix/sunos.c
test/test-get-currentexe.c

Passing a buffer that was too small to hold the result made it fail
with UV_EPERM because the -1 status code from _NSGetExecutablePath()
was returned unmodified to the caller.
This commit rewrites uv_exepath() to:
1. Not allocate heap memory, and
2. Not clobber the result buffer on error, and
3. Handle _NSGetExecutablePath()'s and realpath()'s idiosyncracies, and
4. Store as much of the path in the output buffer as possible, don't
fail with an error.  Makes it behave the same as other platforms.
The result is always zero-terminated.
Fixes: libuv#103
R=@saghul

darwin: fix uv_exepath() UV_EPERM with tiny buffer

---

src/win/fs.c
src/win/winapi.c
src/win/winapi.h

This replaces the current `uv_fs_scandir` implementation by one that talks to the NT kernel directly.
The previous implementation used the win32 `FindFirstFile()` and `FindNextFile` APIs which have quite some overhead.
@orangemocha, you seem best fit to review this.
Otherwise I'll defer to the usual suspects @saghul or @bnoordhuis.

win: use NtQueryDirectoryFile to implement uv_fs_scandir

---

autogen.sh
configure.ac

It should fix the following build error with old autoconf/automake
versions:
Makefile.am:24: Libtool library used but `LIBTOOL' is undefined
Makefile.am:24: The usual way to define `LIBTOOL' is to add
`AC_PROG_LIBTOOL'
Makefile.am:24: to `configure.ac' and run `aclocal' and `autoconf'
again.
Fixes: libuv#111
R=@rvagg

build: add AC_PROG_LIBTOOL to configure.ac

---

test/test-osx-select.c

R=@bnoordhuis
See the failure here: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/nodes=osx1010/45/console

test: skip OSX TTY select test if /dev/tty cannot be opened

---

src/win/internal.h
src/win/stream.c
src/win/tcp.c
src/win/tty.c
test/test-tcp-try-write.c

Support uv_try_write() for tcp and tty handles on windows.
I'm still not super excited about this API, but it seems to make node noticeably faster.
This does not change the API/ABI, so it's fine to land this in a patch release.
R=@saghul or @bnoordhuis

win,tcp,tty: support uv_try_write()

---

docs/src/loop.rst

Indicate that it can (and should) also be closed, currently it's not
"special" in any way.

doc: clarify uv_default_loop

---

Makefile.am
src/unix/linux-core.c
uv.gyp

Linux before kernel 2.6.19 does not support epoll_pwait().  Due to a
logic error in commit 2daf944 ("unix: add flag for blocking SIGPROF
during poll"), the fallback path for ENOSYS was not taken.
This commit also adds epoll_pwait() emulation using pthread_sigmask().
The block/unblock operations are not atomic but that is fine for our
particular use case, to wit, sleep through SIGPROF signals.
R=@saghul
https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/55/

linux: fix epoll_pwait() regression with < 2.6.19

---

src/win/getaddrinfo.c

The req->addrinfow field contains the hints in that case, so we must not
free it.
This regression was introduced in f2bb8d3 by yours truly.
R=@bnoordhuis
This gives us a green build on Windows: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/60/

windows: fix regression when cancelling getaddrinfo

---

Makefile.am
docs/src/stream.rst
src/unix/stream.c
test/test-list.h
test/test-pipe-set-non-blocking.c
uv.gyp

Commit 393c1c5 ("unix: set non-block mode in uv_{pipe,tcp,udp}_open")
causes a regression in the io.js cluster module.
The io.js documentation states that `worker.send()` and `process.send()`
are synchronous but they no longer were after upgrading to libuv v1.2.1.
The reason they are synchronous is because of backpressure - or rather,
lack of backpressure: a slow consumer eventually causes a fast producer
to run out of memory because the backlog of pending messages in the
producer can grow unchecked.
Ergo, implement uv_stream_set_blocking() on UNIX platforms to let io.js
enable the old blocking behavior for pipes again.
Refs: https://github.com/iojs/io.js/issues/760
R=@saghul
https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/63/

unix: implement uv_stream_set_blocking()

---

docs/src/threading.rst
src/unix/thread.c
src/win/thread.c

Before this commit, UNIX returned -1 on failure.  Windows sometimes
returned a UV_E* error code and sometimes a bogus status code, courtesy
of errno values not mapping to UV_E* error codes on that platform.
R=@saghul?
https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/67/

unix,windows: make uv_thread_create() return errno

---

src/unix/process.c

Backported from v1.x (66ab389)
R=@bnoordhuis
R=@tjfontaine

unix: call setgoups before calling setuid/setgid

---

src/unix/linux-core.c

Work around a bug in kernels 3.10 to 3.19 where passing a struct that
has the EPOLLWAKEUP flag set generates spurious syslog audit warnings.
A bad check makes the kernel read the events field when it should not
and complain when the process lacks the CAP_BLOCK_SUSPEND capability.
R=@saghul

linux: work around epoll bug in kernels 3.10-3.19

---

test/test-pipe-set-non-blocking.c

The main thread's epilog closed the file descriptor without waiting for
the worker to shut down, making it sporadically fail with a EBADF error.
Fixes: https://github.com/libuv/libuv/issues/248
R=@saghul

test: fix race condition in multithreaded test

---

src/unix/linux-core.c

arm64 doesn't have a epoll_wait() system call but a logic error stopped
libuv from falling back to epoll_pwait().
This bug was introduced in commit 67bb2b5 ("linux: fix epoll_pwait()
regression with < 2.6.19") which sadly exchanged one regression for
another.
R=@saghul
https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/75/

linux: fix epoll_pwait() fallback on arm64

---

src/unix/android-ifaddrs.c

R=@bnoordhuis
uv__malloc and uv__free are used here.

android: fix compilation warning

---

src/win/fs.c
test/test-fs.c

For posterity, these are the rules for access on Windows (taken from
CPython's implementation), Access is possible if:
* Write access wasn't requested
* The file isn't read-only
* It's a directory (directories cannot be read-only on Windows)
/cc @cjihrig
Should fix: https://github.com/iojs/io.js/issues/1397

win: fix uv_fs_access on directories

---

src/unix/fs.c

Move the logic out of uv__fs_work() and into a function of its own.
R=@saghul

unix: clean up uv_fs_open() O_CLOEXEC logic

---

include/uv.h
src/uv-common.h
src/win/fs.c
src/win/pipe.c
src/win/tty.c

The goal of this PR is to:
* Avoid closing inherited stdandard handles
* Avoid closing CRT file descriptors <= 2
* Close CRT file descriptors >2 with `close()` (instead of closing their underlying windows handles with `CloseHandle`).

[wip] do the right thing with close

---

src/unix/tcp.c
src/unix/udp.c

Binding to a socket of the wrong address returns EAFNOSUPPORT on OSX.
R=@bnoordhuis

test: fix tcp_create_early_bad_bind on OSX

---

src/win/thread.c

The main thread does not have the thread id TLS created.
Fixes: https://github.com/joyent/node/issues/25602
R=@piscisaureus, @orangemocha

win: fix returning thread id in uv_thread_self

---

src/queue.h

Silences the following runtime errors when compiling UBSan:
../src/unix/linux-core.c:181:9: runtime error: member access within null
pointer of type 'uv__io_t' (aka 'struct uv__io_s')
../src/unix/process.c:67:15: runtime error: member access within null
pointer of type 'uv_process_t' (aka 'struct uv_process_s')
../src/unix/process.c:91:15: runtime error: member access within null
pointer of type 'uv_process_t' (aka 'struct uv_process_s')
...
R=@bnoordhuis

common: use offsetof for QUEUE_DATA

---

docs/src/fs.rst

On Linux getting the type is only supported by some filesystems, check
getdents(2).
R=@bnoordhuis
/cc @creationix

doc: add a note about uv_dirent_t.type

---

src/win/tcp.c

This piece of code was incorrectly removed by yours trully in 2dddd56.
It triggered a rather obscure failure in Node:
https://github.com/nodejs/node/pull/2310
R=@piscisaureus, @bnoordhuis

win: fix setting accepted TCP sockets as non-inheritable

---

src/unix/fs.c
src/win/fs.c
test/benchmark-fs-stat.c
test/echo-server.c
test/runner-unix.c
test/test-fs-event.c
test/test-fs.c
test/test-spawn.c

For synchronous file operation requests (ones without a callback), there
is no need to make a copy of the arguments because they don't outlive
the scope of the function call.
R=@saghul
CI: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/128/

unix: don't copy arguments for sync fs requests

---

docs/src/errors.rst
src/uv-common.c

Make uv_err_name() and uv_strerror() return a dynamically allocated
string when the error code is not recognized.
It leaks a few bytes of memory but that can't be helped.  Asserting
and aborting is, in my opinion, much less helpful.
Fixes: https://github.com/nodejs/node/issues/63
R=@saghul
In libuv v2.x, we should probably modify the function signatures to make them accept a buffer to write to.

unix,windows: don't assert on unknown error code

---

src/uv-common.c

Refs: https://github.com/libuv/libuv/pull/467
R=@bnoordhuis

common: fix use of snprintf on Windows

---

src/threadpool.c

Commit 0f1bdb6 ("threadpool: send signal only when queue is empty")
introduces a regression where work is not evenly distributed across
the thread pool because the work queue's condition variable is only
signalled when the queue is empty, even when there are waiting workers.
It doesn't turn into outright deadlock because there is always
at least one thread making forward progress but it does degrade
throughput, sometimes massively so.
Signalling whenever there are waiting workers fixes the throughput
issue while still keeping the number of uv_cond_signal() calls low,
which was the motivation for commit 0f1bdb6.
Fixes: https://github.com/libuv/libuv/pull/490
Fixes: https://github.com/libuv/libuv/issues/492
R=@saghul
Sorry for the delay.  I got distracted yesterday halfway through writing …

threadpool: fix thread starvation bug

---

src/unix/process.c

uv__close() does not set errno, it returns the error.  It also never
returns EINTR, it always maps it to EINPROGRESS.
R=@saghul

unix: fix error check when closing process pipe fd

---

include/uv-win.h
src/win/thread.c

Before this patch an uv_mutex_t (backed by a critical section) could be
released by a tread different from the thread that acquired it, which is
not allowed. This is fixed by using a semaphore instead.
BUG: https://github.com/libuv/libuv/issues/515
REF: https://github.com/nodejs/node/pull/2723
R=@bnoordhuis
R=@saghul

win: fix unsavory rwlock fallback implementation

---

src/unix/thread.c
src/win/thread.c

Fold EAGAIN and EBUSY into EBUSY. This makes it consistent across all
Unix platforms and Windows.
Refs: https://github.com/libuv/libuv/pull/525
R=@bnoordhuis

unix: consolidate rwlock tryrdlock trywrlock errors

---

common.gypi
gyp_uv.py

R=@bnoordhuis
AFAIS this is only used by Chrome, in order to build each component as a shared or static library. They seem to use shared for development to make linking faster, and release builds are all statically linked. We don't need this here, do we?

build: remove unused 'component' GYP option

---

src/queue.h
src/threadpool.c
src/unix/async.c
src/unix/core.c
src/unix/fsevents.c
src/unix/linux-inotify.c
src/unix/loop-watcher.c
src/unix/signal.c
src/unix/stream.c
src/uv-common.c
test/test-emfile.c

Replace uses of QUEUE_FOREACH when the list can get modified while
iterating over it, in particular when a callback is made into the
user's code.  This should fix a number of spurious failures that
people have been reporting.
R=@saghul or @piscisaureus
@indutny There are two QUEUE_FOREACH statements in src/unix/fsevents.c.  They _look_ safe to me (as in: the list isn't mutated concurrently) but can you confirm?

unix: use QUEUE_MOVE when iterating over lists

---

src/unix/fs.c

Commit 0199955 ("fs: undo uv__req_init when uv__malloc failed")
mistakingly unregisters the requests unconditionally in a few places,
resulting in memory corruption when it hasn't been registered first.
Fixes: #543
R=@saghul
I redid the fix from the first commit in the second one as a macro.
Input on what you think is the cleanest approach appreciated.
CI: https://ci.nodejs.org/view/libuv/job/libuv+any-pr+multi/161/

unix: only undo fs req registration in async mode

---

src/unix/fs.c

The pthread_mutex_lock() and pthread_mutex_unlock() calls logically
cannot fail in uv__fs_write() but let's check the return value anyway:
cosmic rays and memory corruption do happen.
R=@saghul - for when you're back.

darwin: abort() if (un)locking fs mutex fails

---

src/unix/linux-syscalls.c
src/unix/linux-syscalls.h

According to [0] we need to pass it in 2 32bit registers. Fix
inspired by the musl libc implementation [1].
[0]: http://man7.org/linux/man-pages/man2/syscall.2.html#NOTES
[1]: http://git.musl-libc.org/cgit/musl/tree/src/unistd/preadv.c
R=@bnoordhuis
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/204/

linux,fs: fix calling p{read,write}v with a 64bit offset

---

test/test-mutexes.c

Trying to acquire a rwlock that the current thread already owns may fail
(not "shall fail") with EDEADLK.  Libuv considers that a fatal error and
rightly so in my opinion; it normally means the program contains a logic
error.
The test had indeed logic errors.  This commit splits off the UV_EBUSY
return code testing into a separate thread, eliminating the potential
for self-deadlock.
Fixes: https://github.com/libuv/libuv/issues/544
R=@saghul?
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/215/

test: fix self-deadlocks in thread_rwlock_trylock

---

test/runner-unix.c

Fix the logic that guards against the system clock jumping back in time.
Fixes: https://github.com/libuv/libuv/issues/667
R=@saghul
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/224/

test,unix: fix logic error in test runner

---

autogen.sh

Ensure that ltmain.sh gets copied, not symlinked, like we do with
automake artifacts.
R=@saghul
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/225/

build: invoke libtoolize with --copy

---

src/unix/stream.c

~~~~
src/unix/stream.c:1089:19: warning: variable length array folded to
constant array as an extension [-Wgnu-folding-constant]
char cmsg_space[CMSG_SPACE(UV__CMSG_FD_SIZE)];
~~~~
R=@bnoordhuis

osx: avoid compilation warning in Clang

---

uv.gyp

The file itself contains include guards, so don't compile it
conditionally.
R=@piscisaureus, @bnoordhuis

build,win: remove unneeded condition from GYP file

---

src/unix/linux-core.c

Not sure I'm on the right track here... When attempting to compile libuv + the tests with musl I get a compilation error:
~~~~
../src/unix/linux-core.c:55:30: fatal error: linux/if_packet.h: No such file or directory
compilation terminated.
~~~~
I'm compiling the thing with the musl-gcc wrapper as follows:
~~~~
export CC=musl-gcc
export LINK=musl-gcc
export CFLAGS=-static
./gyp_uv.py
...
~~~~
This PR compiles on musl and non-musl.
R=@bnoordhuis

linux: fix compilation with musl

---

docs/src/misc.rst
src/fs-poll.c
src/unix/core.c
src/unix/pipe.c
src/uv-common.c
src/win/pipe.c
src/win/util.c
test/test-fs-event.c
test/test-fs-poll.c
test/test-pipe-getsockname.c

libuv has multiple functions which return buffers. Make them consistent
with the following rules: the returned size *does not* include the null
byte, but the buffer *is* null terminated.
There is only one exception to the above: Linux abstract sockets,
because null bytes are not used as string terminators in those.
Refs: https://github.com/libuv/libuv/pull/674
R=@bnoordhuis, @sam-github, @cjihrig 
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/233/

unix, win: consistently null-terminate buffers

---

src/unix/core.c

uv__open_cloexec returns either the fd or a libuv error, which is -errno
on Unix, not -1.
R=@libuv/collaborators

linux: fix error checking in uv__open_file

---

src/unix/tty.c

Some platforms (notably Solaris) can fail in this ioctl() if interrupted
by a signal.  Retry the system call when that happens.
Fixes: https://github.com/nodejs/node/issues/5737

unix: retry ioctl(TIOCGWINSZ) on EINTR

---

test/test-tcp-create-socket-early.c
test/test-udp-create-socket-early.c

I detected this on one of the Raspberry Pi bots.
CI: https://ci.nodejs.org/job/libuv-test-commit/19/
R=@libuv/collaborators

test: skip early bind tests if no IPv6 is supported

---

src/unix/aix.c
src/unix/kqueue.c
src/unix/linux-core.c
src/unix/sunos.c

It was reported that some node.js tests fail on AIX because the exit
event sometimes comes before the final stdio output of a child process.
Work around that by deferring the signal watcher that is used for
process management until after the dispatch of regular i/o watchers.
Fixes: https://github.com/libuv/libuv/issues/610
R=@saghul.  The duplication is galling, we should do something about that in v2.
[I'll update with a CI link once ci.nodejs.org is back up.]

unix: delay signal handling until after normal i/o

---

src/win/fs.c

It has been reported that for SharePoint connections mapped as a drive,
uv_fs_scandir() returns "." and ".." entries when the expectation is
that they should be filtered out.
After some investigation it looks like the driver returns ".\0" and
"..\0" for those entries, that is, it includes the zero byte in the
filename length.  Rewrite the filter to catch those entries as well.
Fixes: https://github.com/nodejs/node/issues/4002
Maybe a better fix is:
```c
if (wchar_len > 0 && info->FileName[wchar_len - 1] == L'\0'))
wchar_len -= 1;
```
Thoughts?
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/195/

win: work around sharepoint scandir bug

---

src/unix/aix.c
src/unix/freebsd.c
src/unix/openbsd.c
src/uv-common.c

Libuv expects that free() does not clobber errno.  The system allocator
honors that assumption but custom allocators may not be so careful.
CI: https://ci.nodejs.org/job/libuv-test-commit/34/

unix: guard against clobbering errno in uv__free()

---

src/win/fs-event.c

The code for handling fs events is quite complex, this commits tries to
make it easier to follow.
First, there are 2 cases in which we use the name of the file straight
from the event (when watching a directory):
- if we cannot create the long path
- if the file got renamed or removed
So separate this logically, even if the code we need is the same.
Second, one way or anothwer we will always have some filename to report,
so remove an unnecessary if.
Third, nullify filenamew, to avoid having a dangling pointer, should the
code change.

win: clarify fsevents handling code

---

src/unix/fs.c
src/uv-common.c
src/win/fs.c

On unix, `scandir()` uses the system allocator to allocate memory. This commit releases the memory with `free()` instead of `uv__free()`. `uv__free()` is still used on Windows, which uses `uv__malloc()` to
request the memory.
Closes #873 
R= @saghul

unix: use system allocator for scandir()

---

src/win/tty.c

Fixes build on Windows XP with Visual Studio 2008.
R=@orangemocha, @piscisaureus

win,build: fix compilation on ancient Windows systems

---

src/unix/tty.c

When the select trick is used fd is replaced with the fake fd (one end
of the socketpair) so we're not setting the original fd in non-blocking
mode.
Refs: https://github.com/nodejs/node/issues/6456#issuecomment-220018822
R=@indutny
/cc @libuv/collaborators

darwin: fix setting fd to non-blocking in select(() trick

---

LICENSE
README.md

First of all: IANAL.
These changes basically reflect what we've been doing for a while.
As a follow-up, I'd like to remove all license boilerplate from the files replacing it with a "pointer" to the actual license. Example: https://github.com/openssl/openssl/commit/846e33c729311169d9c988ceba29484b3783f244
/cc @libuv/collaborators

Fixup license

---

src/unix/core.c
src/unix/fs.c
src/unix/process.c

It's just an indicator that the operation will happen later, so return
success.
R= @bnoordhuis (you suggested this in some issue I can't remember)
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/58/

unix: ignore EINPROGRESS in uv__close

---

include/uv.h
uv.gyp

Also bring uv.gyp up to date with the same flags set in Makefile.am
As discussed in PR https://github.com/libuv/libuv/pull/893
Should I also add `-Wno-attribrutes` to `libuv_la_CFLAGS`? Would really make the compile a lot less verbose
CI Run: https://ci.nodejs.org/job/libuv-test-commit-aix/nodes=aix61-ppc64/69/console

test: silence build warnings on AIX

---

src/unix/stream.c

It's already documented in
http://docs.libuv.org/en/v1.x/stream.html#c.uv_accept

unix: remove unneeded TODO note

---

src/unix/fs.c

Don't call uv__to_stat() when the stat/fstat/lstat system call fails;
the stack-allocated buffer contains only garbage in that case.
Not a very serious bug it's technically undefined behavior and it made
valgrind squawk.
Introduced in commit 499c7976 ("unix, windows: nanosecond resolution
for uv_fs_[fl]stat").
Alternatively, we could `memset(pbuf, 0, sizeof(pbuf))` before the system call.  Thoughts?
CI: https://ci.nodejs.org/job/libuv-test-commit/65/

unix: don't convert stat buffer when syscall fails

---

src/win/fs-event.c
test/test-fs-event.c
test/test-list.h

This PR causes Window file watching events to compare the entire file path when filtering events. This fixes a bug where incomplete path comparisons would cause invalid events to be raised.
Refs: https://github.com/libuv/libuv/pull/682

win: compare entire filename in watch events

---

src/unix/linux-core.c

It was pointed out[0] that libuv could effectively enter an infinite
loop (but not a busy loop) under certain conditions when polling for
events:
1. When the architecture is 32 bits, and
2. When timeout > 0, i.e., finite, and
3. When timeout > max_safe_timeout (~30 minutes), and
4. When epoll_wait(timeout) returns 0, then
5. timeout was not properly updated on the next call to epoll_wait().
Inspection of the code uncovered a secondary bug where under a similar
set of circumstances the timeout could drift when the epoll_wait()
system call returned late.
[0] https://github.com/libuv/libuv/pull/354#discussion_r67837112
CI: https://ci.nodejs.org/job/libuv-test-commit/66/

linux: fix potential event loop stall

---

src/unix/loop.c
src/uv-common.c
test/test-loop-close.c

Libuv leaves loop->data unchanged in uv_loop_init() and uv_loop_done()
on Windows but it clobbered it on UNIX platforms.  This commit fixes
that inconsistency.
CI: https://ci.nodejs.org/job/libuv-test-commit/74/

unix: preserve loop->data across loop init/done

---

include/uv.h

Same as we do for uv_handle_t and uv_req_t, they may come useful if we
need to get creative to keep ABI compatibility.

core: add reserved fields to uv_loop_t

---

README.md
include/uv-win.h
src/win/core.c
src/win/getaddrinfo.c
src/win/winapi.h
src/win/winsock.h
test/runner-win.c
test/runner-win.h
test/test-spawn.c

MinGW (from mingw.org) is really old, so stop pretending we support it.
Just support MinGW-w64, which works also works with 32bit Windows,
despite it's misleading name.

win: drop support for old MinGW versions

---

test/test-pipe-getsockname.c

The test uses an annonymous pipe, which means the returned length will
be 0.
Fixes: https://github.com/libuv/libuv/issues/376
Fixes: https://github.com/libuv/libuv/issues/529
Refs: https://github.com/libuv/libuv/issues/264

test: fix OOB buffer access

---

test/test-pipe-getsockname.c

After 4ed29c2498408c99079f25bfc0c6aec5bfbf42c4 got fixed, when a CRT fd
is handed off to a pipe handle using uv_pipe_open libuv will close it
properly, so it's an error to do so ourselves.
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows/126/

test: don't close CRT fd handed off to uv_pipe_t

---

test/test-tcp-close-while-connecting.c

It's not impossible for the connect() to succeed before handle is fully
closed, so handle that case too.
Hopefully it fixes #1003 
R= @libuv/collaborators @jbergstroem 
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/97/

test: make tcp_close_while_connecting more resilient

---

docs/src/loop.rst
include/uv.h
src/unix/core.c
src/win/core.c
test/test-embed.c

Change the return type from int to uv_os_fd_t so we can return an int on
Unix and a HANDLE on Windows.
Applications can use this to poll the libuv event loop from another
thread as is now possible on Unix.
The test implementation is based in what Electron does:
https://github.com/electron/electron/blob/master/atom/common/node_bindings_win.cc
Refs: https://github.com/libuv/libuv/issues/965
R=@libuv/collaborators and maybe @joaocgreis ?
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/103/

win: return IOCP HANDLE in uv_backend_fd

---

src/win/tty.c

Introduced in 58ccfd4c210d3cc1a36dd82474976aac296589f2, reviewed by your
truly :-(
R = @iWuzHere

win: fix typo in type name

---

include/pthread-barrier.h

Fixes: https://github.com/libuv/libuv/issues/1019
R = @libuv/collaborators

unix: always define pthread barrier fallback pad

---

test/test-tcp-close-while-connecting.c

The expected error is UV_ECANCELED but the test tries to connect to what
is basically an arbitrary address in the expectation that no network
path exists, so UV_ENETUNREACH is an equally plausible outcome.
This commit undoes the change from commit e994000 ("test: make
tcp_close_while_connecting more resilient") because I don't think
the connection ever actually succeeds.
Refs: https://github.com/libuv/libuv/pull/1005
CI: https://ci.nodejs.org/job/libuv-test-commit/131/

test: fix tcp_close_while_connecting CI failures

---

src/unix/thread.c

Simplify and optimize uv_thread_create() by casting the function pointer
to the prototype that pthread_create() wants.  Avoids the indirection of
an intermediate callback and heap-allocating custom state that is really
only there to placate the compiler.
CI: https://ci.nodejs.org/job/libuv-test-commit/154/

unix: don't malloc in uv_thread_create()

---

src/win/core.c
src/win/fs.c

default_loop_struct and default_loop_ptr seem to have been overlooked
in commit 32747c7 ("win,unix: move loop functions which have identical
implementations".)
CI: https://ci.nodejs.org/job/libuv-test-commit/155/

win: remove unused static variables

---

src/unix/signal.c

So it aborts in case `pthread_once` fails.

signal: replace pthread_once with uv_once

---

src/win/process-stdio.c

Add a missing `break` statement referenced in https://github.com/libuv/libuv/issues/1119#issuecomment-258118534.
R= @bnoordhuis

win: add missing break statement

---

MAINTAINERS.md

The v1.10.0 release was signed with this key by mistake.
Fixes: https://github.com/libuv/libuv/issues/1140

doc: add cjihrig alternative GPG ID

---

src/win/tty.c
test/test-list.h
test/test-tty.c

Causes regressions on Windows 10 in applications that use ANSI codes.
Also revert one-liner commit 0895ccf ("win: fix typo in type name").
This reverts commit 0895ccfc8ced0c2442c8aab75ccef1f1a6b3938e.
This reverts commit 58ccfd4c210d3cc1a36dd82474976aac296589f2.
Refs: https://github.com/nodejs/node/issues/9542
Refs: https://github.com/libuv/libuv/pull/889
Refs: https://github.com/libuv/libuv/issues/1135
CI: https://ci.nodejs.org/job/libuv-test-commit/169/

Revert "win,tty: add support for ANSI codes in win10 v1511"

---

src/win/tty.c
test/test-list.h
test/test-tty.c

Two commits:
- Revert the revert.
- When calling `MultiByteToWideChar` make sure there's enough room in the output buffer by dynamically allocating memory in case the size of the buffer needs to be greater than 8192 characters.

win,tty: bring back and fix ANSI support

---

src/unix/fs.c
test/test-fs.c

Define `_GNU_SOURCE` on BSD platforms so the `uv_stat_t` struct is
correctly filled.
Disclaimer: I have only tested it on `FreeBSD`. It would be great if someone could test it in the other `BSDs`.

fs: fix uv_fs_fstat on BSD platforms

---

src/unix/internal.h
src/unix/openbsd.c
test/test-poll.c

It fixes `process_title`, `poll_bad_fdtype` and `poll_nested_kqueue`
tests.

test: fix tests on OpenBSD

---

test/test-threadpool-cancel.c

Substitute the `z` length modifier with `l` to avoid warnings, as the
`z` modifier is defined in the C99 standard.

test: fix -Wformat warning

---

docs/src/signal.rst
include/uv.h
src/unix/signal.c
src/uv-common.h
src/win/signal.c
test/test-list.h
test/test-signal.c

It behaves as `uv_signal_start` but it resets the signal handler as soon
as the signal is received.
Refs: https://github.com/libuv/libuv/issues/1104

signal: add uv_signal_start_one_shot method

---

Makefile.am
checksparse.sh
docs/src/misc.rst
include/uv.h
src/unix/core.c
src/win/internal.h
src/win/util.c
test/test-env-vars.c
test/test-list.h
uv.gyp

These functions are used to create, update, and retrieve environment variables.
Closes #1198

unix,win: add uv_getenv() and uv_setenv()

---

docs/src/fs_event.rst
docs/src/fs_poll.rst
docs/src/misc.rst

This commit adds additional documentation to the `UV_ENOBUFS` scenario for several methods.
Closes #1179

docs: improve UV_ENOBUFS scenario documentation

---

src/unix/sunos.c
src/win/fs-event.c
test/test-fs-event.c
test/test-list.h

This commit stops the handle in the `uv_fs_event_start()` error handler if it was started prior to the error.
Fixes: https://github.com/libuv/libuv/issues/1253

win: stop handle in uv_fs_event_start() on error

---

src/threadpool.c
src/unix/internal.h
src/uv-common.h
src/win/async.c
src/win/fs-event.c
src/win/fs.c
src/win/getaddrinfo.c
src/win/getnameinfo.c
src/win/pipe.c
src/win/poll.c
src/win/process.c
src/win/req-inl.h
src/win/signal.c
src/win/stream-inl.h
src/win/stream.c
src/win/tcp.c
src/win/tty.c
src/win/udp.c

Fixes a TODO in src/threadpool.c.  Updates the Windows code to drop the
unused `loop` parameter in calls to uv_req_init().
CI: https://ci.nodejs.org/job/libuv-test-commit/152/

unix,windows: refactor request init logic

---

test/test-spawn.c

At least starting with Darwin Kernel Version 16.4.0, sending a SIGTERM
to a process that is still starting up kills it with SIGKILL instead of
SIGTERM.
Fixes: https://github.com/libuv/libuv/issues/1226

test,osx: fix flaky kill test

---

src/unix/pipe.c

This goto target is only one line, and is only reached from one place.

unix: inline uv_pipe_bind() err_bind goto target

---

src/unix/fsevents.c

This call, in the context of file watching, appears to trigger assertion warnings on some macOS configurations.
Attempt at fixing https://github.com/libuv/libuv/issues/1334, https://github.com/nodejs/node/issues/854.
cc: @indutny (https://github.com/nodejs/node/issues/854#issuecomment-298688225)

unix: remove FSEventStreamFlushSync() call

---

test/test-tcp-write-queue-order.c

Delay the timer start to be sure all handles are created when `timer_cb`
is executed. In some cases this was not the case causing the following
error:
```
not ok 51 - tcp_write_queue_order
exit code 134
Output from process `tcp_write_queue_order`:
lt-run-tests: src/unix/core.c:166: uv_close: Assertion `0' failed.
```

test: fix flaky tcp-write-queue-order

---

docs/src/loop.rst

`uv_loop_fork()` was recently added, but is known to contain bugs. This commit marks the function as experimental so that bugs can be addressed without blocking further libuv releases.
Refs: https://github.com/libuv/libuv/pull/846
Refs: https://github.com/libuv/libuv/pull/1269
Refs: https://github.com/libuv/libuv/issues/1264

doc: mark uv_loop_fork() as experimental

---

docs/src/misc.rst
src/uv-common.c
test/test-ip6-addr.c
test/test-list.h

On Unix, `uv_ip6_addr()` calls `if_nametoindex()`. This commit adds error handling for `if_nametoindex()` failures.
Fixes: https://github.com/libuv/libuv/issues/1313

src: handle if_nametoindex errors in uv_ip6_addr

---

src/unix/stream.c
test/run-tests.c
test/test-ipc.c
test/test-list.h

Return `EBADF` when trying to send a handle which, while enqueued, was
closed.
Fixes: https://github.com/libuv/libuv/issues/806

unix,stream: return error on closed handle passing

---

src/win/dl.c
test/test-dlerror.c

Should hopefully make the dreaded "%1 is not a valid Win32 application"
error message a thing of the past.
CI: https://ci.nodejs.org/job/libuv-test-commit/162/

win: include filename in dlopen error message

---

vcbuild.bat

Introduced in
https://github.com/libuv/libuv/commit/2f6d4b4b58ea290961dc983117d31b19e198403a and accidentally (?) undone in
https://github.com/libuv/libuv/commit/19c896dd086abb351361eab54b7e88ed5ce8af08.

win,build: fix building from Windows SDK or VS console

---

SUPPORTED_PLATFORMS.md

Refs: https://github.com/libuv/libuv/issues/1458
Refs: https://github.com/libuv/libuv/pull/991
This would also require an owner to rename the existing sunos team.

doc: differentiate SmartOS and SunOS support

---

src/unix/fs.c

Pass `NULL` instead of `req->loop` to the various libuv functions called from `uv__fs_copyfile()`.
Refs: https://github.com/libuv/libuv/pull/1494

unix: don't use req->loop in uv__fs_copyfile()

---

src/unix/fs.c

This commit introduces `fchmod()` in `uv_fs_copyfile()` to set the mode of the destination file.
Refs: https://github.com/nodejs/node/issues/15394

unix: use fchmod() in uv_fs_copyfile()

---

src/unix/fs.c
test/test-fs-copyfile.c

This PR fixes two bugs in the `sendfile()` fallback for `uv_fs_copyfile()`.
- Copying empty files. The `err` variable was never initialized through the course of execution if the source file is empty. That was causing failures on FreeBSD, as exposed in the test from #1551.
- Truncating destination files. If the source file was smaller than the destination file, then the result of the copy was incorrect. This is @ugexe's fix from #1551, with style nits addressed.
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/472/

Support empty files and truncation in uv_fs_copyfile()

---

src/win/process.c

For a while now, Node users on Windows have reported that console windows sometimes pop up when spawning child processes. libuv has the `UV_PROCESS_WINDOWS_HIDE` flag, that is supposed to solve this problem. I tried exposing the flag to Node in https://github.com/nodejs/node/pull/15380, but it didn't seem to fix the problem.
`UV_PROCESS_WINDOWS_HIDE` was added in https://github.com/joyent/libuv/pull/627. That PR states:
> UV_PROCESS_WINDOWS_HIDE enables suppression of process windows when launching subprocesses on Windows platforms from a executable linked to the WINDOWS subsystem (as opposed to the CONSOLE subsystem).
In #965 @saghul mentioned that [Electron is setting the `CREATE_NO_WINDOW` flag on child processes to suppress console …

win: let UV_PROCESS_WINDOWS_HIDE hide consoles

---

docs/src/misc.rst
include/uv-unix.h
include/uv-win.h
include/uv.h
src/unix/core.c
src/win/internal.h
src/win/pipe.c
src/win/util.c
test/test-platform-output.c

Requested in https://github.com/nodejs/node/issues/14957. The only real work is on Windows, and libuv already had the functionality internally, so I thought I'd take a shot at exposing it.
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/542/

unix,win: add uv_os_getppid()

---

include/uv-unix.h
src/unix/getaddrinfo.c

This commit moves the `net/if.h` include into `src/getaddrinfo.c` to prevent AIX compilation errors. With these symbols exposed publicly, Node.js compilation failed on AIX by exposing `Free()`, which conflicts with another API.
Refs: https://github.com/nodejs/node/pull/16835
Refs: https://github.com/libuv/libuv/pull/1445
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/564/

unix: move net/if.h include

---

include/uv-win.h

This updates the value to Windows Vista.
I agree with https://github.com/libuv/libuv/issues/1671#issuecomment-350009867, that we should drop this completely. I'd like to update it here and remove it on master.
Fixes: https://github.com/libuv/libuv/issues/1671

win: set _WIN32_WINNT to 0x0600

---

src/win/fs.c
test/test-fs.c
test/test-list.h

Title should be self-explanatory.
cc @cjihrig 
hi @saghul, @bnoordhuis

win: allow directory symlinks to be created in a non-elevated context

---

test/test-fs-event.c

This commit fixes two assertions of the form `(events == UV_CHANGE || UV_RENAME)` which always passed because `UV_RENAME` is 1.
Refs: https://github.com/libuv/help/issues/41

test: fix incorrect asserts

---

src/unix/fs.c

On Unix, if a fs function fails validation after `INIT` but before sending the work to the thread pool, then is is necessary to manually unregister the request. This commit moves the registration to just before the work submission. This also makes Unix match the Windows behavior.
Refs: https://github.com/libuv/libuv/pull/1747

unix: delay fs req register until after validation

---

src/unix/fs.c
src/win/fs.c
test/test-fs.c

Refs: https://github.com/libuv/libuv/pull/1751#discussion_r169645330
I added a commit that checks the fs req fields when erroring before the work is sent to the thread pool. It would probably be useful to have similar checks on errors after the work is sent to the thread pool at some point.

 unix,win: ensure req->bufs is freed

---

docs/src/fs.rst
include/uv.h
src/unix/fs.c
src/win/fs.c
test/test-fs-copyfile.c

`UV_FS_COPYFILE_FICLONE_FORCE` attempts to use copy-on-write semantics in `uv_fs_copyfile()`. If CoW is not available, an error is returned.

unix,win: add UV_FS_COPYFILE_FICLONE_FORCE support

---

configure.ac
docs/src/misc.rst
include/uv.h
src/unix/core.c
src/win/util.c
test/test-get-passwd.c
test/test-platform-output.c
uv.gyp

On Unix the `gecos` field usually contains the full name of the user. This is returned by `getpwuid_r()` on Unix and `GetUserNameExW` on Windows (falling back to `NameSamCompatible` if the users display name is not set).
This is a reworking of https://github.com/libuv/libuv/pull/834. I kept @kthelgason as the author, but added @saghul (for the original Windows implementation) and myself (because this PR is different enough, especially on Windows) as co-authors.
Successful CI run: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/788/

unix,win: add gecos field to uv_passwd_t

---

src/win/fs.c
test/test-fs.c

This reverts commit aa1beaa07c3c8fc7531055412728c8bf691e118e. This commit was causing `EPERM` errors in Node.js.
Fixes: https://github.com/nodejs/node/issues/20112

Revert "win, fs: use FILE_WRITE_ATTRIBUTES when opening files"

---

include/uv-errno.h
include/uv.h

I was able to generate this error in https://github.com/nodejs/node/pull/20588 on FreeBSD. Without it being defined, Node crashed with:
```
TypeError: errmap.get is not a function or its return value is not iterable
at Object.uvException (internal/errors.js:521:34)
```
After defining it, I got a proper exception.

unix,windows: map EFTYPE errno

---

src/win/process.c

If I'm reading https://github.com/nodejs/node/issues/20605 properly, then it seems that this comparison should be case insensitive. Untested locally, but that's what the CI is for.

win: perform case insensitive PATH= comparison

---

src/win/getaddrinfo.c
src/win/winapi.c
src/win/winapi.h

Libuv is not supported on Windows XP, as stated in the SUPPORTED_PLATFORMS document. It also can't possibly work because `ReOpenFile()` in src/win/fs.c is not weakly linked, so any executable that links libuv would simply fail to load on XP.
This reverts commit 17eaa956bde35daad99b36b820daf8e8227add74.
Refs: https://github.com/libuv/libuv/pull/1810

Revert "win: add Windows XP support to uv_if_indextoname()"

---

src/win/udp.c
test/test-udp-options.c

Unix allows socket options to be set prior to binding. This commit aligns Windows with this behavior.
Fixes: https://github.com/libuv/libuv/issues/1842
Refs: https://github.com/joyent/libuv/issues/1205
Refs: https://github.com/joyent/libuv/pull/1270
Green CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/898/

win: allow setting udp socket options before bind

---

test/test-process-title-threadsafe.c

This test has been timing out on macOS on the CI. Try to avoid that by reducing the number of iterations run. It looks like macOS performance was already a known issue based on the `#ifdef`.
I ran the libuv-test-commit-osx job a handful of times: https://ci.nodejs.org/job/libuv-test-commit-osx/. Builds 905-909 are this change.

test: speedup process-title-threadsafe on macOS

---

src/win/core.c

This commit sets the error returned by `uv_loop_init()` to `UV_ENOMEM` in the case of a failed timer heap malloc.

win: return UV_ENOMEM from uv_loop_init()

---

src/unix/linux-core.c
src/unix/linux-syscalls.c
src/unix/linux-syscalls.h
src/unix/os390-syscalls.h
src/unix/os390.c

Remove the syscalls wrappers now that the minimum requirements are
kernel 2.6.32 + glibc 2.12.
This commit should fix the epoll_pwait()-related issues that have
been reported against mips/mipsel builds.
Fixes: #335 (longstanding issue)

linux: remove epoll syscall wrappers

---

src/unix/bsd-ifaddrs.c
src/unix/linux-core.c
src/unix/os390.c

This commit ensures that the memory of the `phys_addr` field is initialized on all platforms.
Refs: https://github.com/nodejs/node/issues/23043
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1033/ (one unrelated failure)

unix: initialize uv_interface_address_t.phys_addr

---

src/unix/bsd-ifaddrs.c
src/unix/linux-core.c

Prior to https://github.com/libuv/libuv/pull/1999, `uv_interface_addresses()` did not populate the `phys_addr` field on Cygwin or MinGW. This commit restores that behavior, which was mistakenly changed.
Fixes: https://github.com/libuv/libuv/issues/2034
EDIT: Passing CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1063/

unix: restore skipping of phys_addr copy

---

src/unix/aix-common.c
src/unix/bsd-ifaddrs.c
src/unix/linux-core.c
src/unix/os390.c
src/unix/sunos.c
src/win/util.c

This commit does a few things to make the function more
consistent across platforms:
- Initialize the output parameters before everything else.
- Return early if there are no interfaces instead of performing
zero-sized allocations.
- Add a missing memory deallocation.
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1065/
EDIT: CI seems fine

unix,win: make uv_interface_addresses() consistent

---

configure.ac

With this simple addition, libuv now passes tests when built out-of-tree! This asks `config.status` to generate links (or copies) of these files in the expected place in the build tree.
```
/bin/bash ./config.status
config.status: creating Makefile
config.status: creating libuv.pc
config.status: linking /data/vtjnash/libuv/test/fixtures/empty_file to test/fixtures/empty_file
config.status: linking /data/vtjnash/libuv/test/fixtures/load_error.node to test/fixtures/load_error.node
config.status: executing depfiles commands
config.status: executing libtool commands
```

build: support running tests in out-of-tree builds

---

src/unix/aix.c
src/unix/fsevents.c
src/unix/internal.h
src/unix/kqueue.c
test/test-fs-event.c
test/test-list.h

In the merged PR (#1572), the ifdef conditional was reversed, leading to the old code-path still being used (and thus making the PR a glorified no-op for 10.7+, instead of for 10.6- as intended).
This also reduces some of the redundancy in the conditional checks, by factoring out the common test.
And fixes a divergence in functionality kFSEventsRenamed => kFSEventStreamEventFlagItemRenamed (this is what actually lead me to start investigating this PR, since it altered the behavior of this code when this got merged into master and the `ifdef` got rewritten).
And actually includes the part of the original PR (#641) to kqueue that enabled watching files with fsevents!
Fixes #387

fsevents: really watch files with fsevents on macos 10.7+

---

src/win/thread.c

Appears to be needed for compile with `-msse2` (such as implied by `-march=pentium4`)
for the i686-w64-mingw64 target triple. This seems like a header mistake, but
we can work-around it here by including the header explicitly. (this call was added in #1634)

thread,mingw64: need intrin.h header for SSE2 MemoryBarrier

---

src/win/fs-event.c

`short_path`'s type changed from `WCHAR` array to `WCHAR*` in https://github.com/libuv/libuv/pull/1267, leading to a sizeof-pointer-div warning.
Fixes: https://github.com/libuv/libuv/issues/2138

win: fix sizeof-pointer-div warning

---

CMakeLists.txt
Makefile.am
docs/src/misc.rst
include/uv.h
src/unix/core.c
src/win/util.c
src/win/winapi.c
src/win/winapi.h
test/test-list.h
test/test-platform-output.c
test/test-uname.c
test/test.gyp

Notes:
- ~~The Windows implementation isn't written yet in this PR.~~
- ~~In Node's `os` module, the `sysname` field is always `'Windows_NT'` on non-POSIX platforms. Should we mirror that here? Probably not, but it could impact the integration process in Node.~~
- ~~In Node's `os` module on AIX and Windows, the `release` field has a custom implementation.~~
- ~~CI run (https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1133/) shows issues on SmartOS (looks like SmartOS returns a non-negative value on success, where other platforms return 0, will test).~~
- ~~Latest CI run: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1135/ (no related failures except missing Windows implementation)~~
Fixes: https://github.com/libuv/libuv/issues/2126

unix,win: add uv_os_uname(), uv_os_free_utsname()

---

src/win/util.c

`RegCloseKey()` is the first thing executed in both the success and error case, so combine the calls.

win: simplify registry closing in uv_cpu_info()

---

docs/src/misc.rst
include/uv.h
include/uv/unix.h
src/unix/core.c
src/win/util.c
test/test-gethostname.c

This commit adds `UV_MAXHOSTNAMESIZE` for working with `uv_os_gethostname()`. Prior to this commit, this logic was duplicated in several places across libuv and Node.js alone.
Passing CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1193/

src,include: define UV_MAXHOSTNAMESIZE

---

src/win/util.c

Currently, on Windows the `uv_utsname_t`'s `version` field can be an empty string if no service packs are installed. This isn't very helpful, and a lot more information is available in the Windows registry. This commit prepends the full product name to the existing service pack information.
Refs: https://github.com/nodejs/node/issues/25843
Refs: https://github.com/libuv/libuv/pull/2128#issuecomment-452109129

win: return product name in uv_os_uname() version

---

src/unix/fs.c

Fixes: https://github.com/libuv/libuv/issues/2212
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1248/
EDIT: CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1249/. zOS failures are unrelated.

unix: fix __FreeBSD_kernel__ typo

---

docs/src/misc.rst
include/uv.h
src/unix/core.c
src/win/util.c
test/test-gettimeofday.c

These are the bits that were abandoned in https://github.com/libuv/libuv/pull/2244.
Fixes: https://github.com/libuv/libuv/issues/2243
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1340/

unix,win: introduce uv_timeval64_t

---

include/uv/unix.h

This commit includes `uv/posix.h` in one `#elif` instead of four. Noticed while reviewing https://github.com/libuv/libuv/pull/2301.

unix: simplify uv/posix.h include logic

---

test/test-list.h

The test `threadpool_multiple_event_loops` has been timing out consistently on FreeBSD in the CI. This commit attempts to mitigate the problem by extending the test timeout.
In case anyone is curious, I tried changing the timeout to 10 seconds and still saw timeouts on FreeBSD. From there, I arbitrarily picked a 60 second timeout, and everything seems fine. I'm personally OK with leaving it as a 60 second timeout.
Two CI runs showing the timeout issue resolved:
https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1402/
https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1403/
EDIT: Upon further review, the test failed on https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/136/console

test: increase test timeout

---

test/test-tcp-try-write-error.c

Recent CI failures imply that `uv_try_write()` can return `UV_ECONNRESET` - specifically on FreeBSD. This commit updates the test to pass when that error code is returned.
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1445/

test: allow UV_ECONNRESET in tcp_try_write_error

---

src/unix/cygwin.c

I don't really have any way to test this.
Refs: https://github.com/libuv/libuv/issues/1906#issuecomment-507280243

unix: add uv_get_constrained_memory() cygwin stub

---

.github/ISSUE_TEMPLATE.md

A number of bug reports about the test suite are the result of the user running the test suite as root. It might be wishful thinking, but perhaps some of the bug reports can be eliminated by adding some text to the GitHub issue template.

github: add root warning to template

---

src/win/fs.c

This commit removes two extraneous semicolons and an unused variable that was generating a compiler warning.

win: misc fs cleanup

---

src/win/error.c
src/win/util.c
test/test-env-vars.c

Fixes: https://github.com/libuv/libuv/issues/2413

win: support retrieving empty env variables

---

test/test-fs.c

It has been reported that this value can also equal 0.
Fixes: https://github.com/libuv/libuv/issues/2417

test: loosen assertion in fs_statfs test

---

docs/src/fs.rst
test/test-fs-readdir.c

In the fs_readdir_empty_dir test, the `uv_fs_readdir()` request is cleaned up after calling `uv_fs_closedir()`. However, the readdir request should be cleaned up before calling `uv_fs_closedir()`.
Fixes: https://github.com/libuv/libuv/issues/2496

test: fix order of operations in test

---

src/unix/darwin-proctitle.c
src/unix/proctitle.c
test/test-process-title-threadsafe.c

Libuv loaded and unloaded the Core Services and Application Services for
every call to uv_set_process_title().
Change that to load them on the first call to uv_set_process_title() and
delay unloading until libuv is unloaded.
Speeds up process_title_threadsafe by about 10x on my system. It should
fail less often (hopefully not at all) on the CI now.
Should fix #2479. The fix-up commit is the change relative to 00c6b16.
CI: https://ci.nodejs.org/job/libuv-test-commit/1579/

darwin: speed up uv_set_process_title()

---

docs/src/misc.rst
include/uv.h
src/unix/core.c
src/win/util.c
test/runner-unix.c
test/runner-win.c
test/task.h

This commit exposes the `uv_sleep()` function that previously only existed in the test runner.

unix,win: add uv_sleep()

---

configure.ac
uv.gyp

This flag emits warnings with some versions of gcc that we don't care
about (libuv targets POSIX conformance, not strict ISO C conformance)
and it's arguably not that useful as libuv is compiled in -std=gnu89
mode.
Fixes: https://github.com/libuv/libuv/pull/2567
CI: https://ci.nodejs.org/job/libuv-test-commit/1660/

build: remove -pedantic from compiler flags

---

src/unix/darwin-proctitle.c
src/unix/proctitle.c
test/test-process-title-threadsafe.c

This reverts commit 038eacf.
It was reported that this change causes a regression when trying
to obtain the screen resolution with `CGDisplayPixelsWide()` or
`CGDisplayPixelsHigh()` after changing the process title.
This is the second time this change had to be reverted due to
regressions and, although third time is allegedly the charm,
leaving well enough alone is the proverb I plan to adhere to...
Fixes: #2566
CI: https://ci.nodejs.org/job/libuv-test-commit/1657/

Revert "darwin: speed up uv_set_process_title()"

---

test/run-tests.c

The test suite is known to have issues when run as root. This commit prevents the test suite from running when the euid is 0.
I'm not sure how the other maintainers will feel about this change, but people clearly don't read the GitHub issue template, so I thought this was worth a shot to prevent issues like https://github.com/libuv/libuv/issues/2549 (and many more).
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1666/ (looks like a normal libuv CI run)

test: disallow running the test suite as root

---

.github/stale.yml

As discussed in #2498, add some more tags to not-stale. This list is primarily about preserving past discussions about a known bug/improvement/doc-fix, for the eventual time someone makes a PR to implement a feature. There's two primary goals here:
- making a "doc-fest" or "first-issue hackathon" more productive
- preserve existing discussion context so it doesn't need to be repeated when/if someone resubmits a duplicate and/or a pull request

misc: make more tags "not-stale"

---

docs/src/design.rst
docs/src/fs.rst
docs/src/fs_event.rst
docs/src/guide/about.rst
docs/src/guide/introduction.rst
docs/src/guide/networking.rst
docs/src/guide/processes.rst
docs/src/guide/threads.rst
docs/src/guide/utilities.rst
docs/src/index.rst
docs/src/misc.rst
docs/src/sphinx-plugins/manpage.py
docs/src/version.rst

Running `make -C docs linkcheck` revealed a couple dead (or incorrect) links, plus many of moved resources. This changes everything to prefer https, plus fixes those links that were redirecting or dead.

fix documentation links

---

src/win/winsock.c

Even more lenient version of cfe14452ae97322939bdf1e1ffe608fc757c3968 and #2124, PTAL:
IIUC, this should just falls back to the slower runtime paths when start-up detection of the existence of the fast-path code fails for any reason (rather than enumerating which reasons are acceptable and aborting otherwise).
CI: https://ci.nodejs.org/job/libuv-test-commit/1682/

win: remove abort when non-IFS detection fails

---

docs/src/guide/processes.rst
docs/src/pipe.rst

Some people have misread this section to imply that libuv does not support Unix `pipe` objects, while it only should be saying that the UV_CREATE_PIPE makes a socketpair. Clarify the docs to say specifically that `uv_pipe_t` represents any local file stream.

docs: clarify that uv_pipe_t is a pipe

---

src/win/tty.c

This code already had special handling for decoding utf-8 characters correctly for the UCS-2 conhost
(trailing incomplete bytes and characters > 0xFFFF). Rather than trying to duplicate that, we should be able to simply delete the duplicate code-path and selectively disable the parts that do not apply.
This caused https://github.com/JuliaLang/julia/issues/27267 (which we fixed in the short-term by reverting https://github.com/libuv/libuv/pull/1143).
~~TODO: determine whether the eol handling is still desirable.~~ CHECKED
~~TODO: need to test this (both locally, and in the test-suite)~~ CHECKED

win,tty: avoid regressions in utf-8 handling

---

.github/stale.yml

With the current settings, I need to either opt out entirely from the benefits of stalebot with "no-stale", or handle an additional continual stream of email notifications to avoid them falling off my list. I propose we make the "close" operation a manual step, such that "stale" operates instead like an automation of the existing "stalled" label.
Since it seems that each application of "stale" need be reviewed anyways, it seems equally reasonable to expect the reviewer to click the Github close button instead of the no-stale button and deleting the comment. This also means folks can take more than a one-week (daysToClose: 7) vacation, and the queue (https://github.com/libuv/libuv/labels/stale) will still be sitting there waiting for whenever you return.

RFC: make stalebot less manual work

---

test/test-env-vars.c

It has been observed that running the tests via shell script can cause special environment variables to be missing. This commit ensures that a special Windows environment variable is set.
Fixes: https://github.com/libuv/libuv/issues/2622
Credit to @vtjnash for the idea of setting the environment variable in the test instead of relying user/CI to provide it.
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1708/ (looks good)

test: fix env-vars flakiness

---

test/runner-unix.c
test/runner-win.c
test/runner.c

If the output data contained a null byte (for example, because it was
really utf16), we'd truncate the output there. This commonly would
manifest as the output on the CI bot being:
```
> not ok 308 - threadpool_cancel_random
> # exit code 3
> # Output from process :
> # A
```
Now we'll attempt to print out the whole error message as text (albeit
with the wrong encoding, but the ascii content should still nearly
always be readable).
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1691/, showing a now functional error message for a failure (https://ci.nodejs.org/job/libuv-test-commit-windows/1888/nodes=win2016-vs2017/console)

fix truncated assertion messages on windows CI

---

src/unix/fsevents.c

The mutex also needs to protect the access to the state->loop variable,
since that's owned by the child thread and will be destroyed as soon as
it processes our message.
This previously caused shutdown of libuv loops (especially the stress test fs_event_error_reporting) to segfault occasionally.
Fixes: https://github.com/libuv/libuv/issues/2625

osx,fsevent: fix race during uv_loop_close

---

src/unix/stream.c

As mentioned in the text of https://github.com/libuv/libuv/pull/2447, this seems to have been attempted before and quickly reverted because it was causing errors to be forgotten (breaking tests). The ability to test this codepath in libuv directly was added only very recently (https://github.com/libuv/libuv/issues/1991), and so now adding tests of this code reveal that this PR would re-introduce that failure mode for AIX (https://github.com/libuv/libuv/pull/2409#issuecomment-571277235). So this proposes reverting commit ca08b48252230db27592248aef10c2d1779bccce for the same reason that this code was reverted before in https://github.com/libuv/libuv/pull/475.

Revert "aix: replace ECONNRESET with EOF if already closed"

---

test/test-poll.c

The test had two bugs:
1. It didn't handle EINTR when calling send() and recv().
2. It checked `errno` on EOF but that's only set when the return value
is less than zero.
CI: https://ci.nodejs.org/job/libuv-test-commit/1768/

test: handle EINTR, fix EOF check in poll test

---

docs/src/udp.rst
include/uv.h
src/unix/udp.c

Introduce a new flag to signal the returned buffer. This retains the
previous behavior of returning datagrams in order to the application.
TODO:

udp: return recvmmsg-ed datagrams in order

---

CMakeLists.txt
src/unix/os390-syscalls.c
src/unix/os390-syscalls.h
test/test-spawn.c

This is WIP attempt to fix the z/OS cmake build. CI changes are discussed in https://github.com/nodejs/build/issues/2175.
- Correct CMAKE_SYSTEM_NAME.
- Exclude pthread lib on z/OS.
- Remove deleted src/unix/pthread-barrier.c.
- Set LIBPATH for shared library test.

build: fix z/OS cmake build

---

test/run-benchmarks.c
test/run-tests.c
test/runner-unix.c
test/runner-win.c
test/runner.h
test/test-cwd-and-chdir.c
test/test-fs.c
test/test-get-currentexe.c
test/test-homedir.c
test/test-process-title-threadsafe.c
test/test-tmpdir.c

Commit ff29322 ("test: canonicalize test runner path") from 2014
changed the test runner to call `realpath(3)` on `argv[0]` in order
to fix the `get_currentexe` test failing with the autotools build when
the executable path contained symbolic links but that is now causing
the `spawn_reads_child_path` test to fail on z/os with the cmake build.
Fix that by only doing path canonicalization in the `get_currentexe`
test, not always.
An auxiliary fix is applied to the `process_title_threadsafe` test
because it assumed that setting the process title to a long string,
then reading it back produces in the original string.
On some platforms however the maximum size of the process title is
limited to the size of the `argv` vector.
Because the test runner used absolute paths until now, the argv …

test: canonicalize argv[0] in exepath test

---

src/win/util.c
src/win/winapi.c
src/win/winapi.h

Fixes: https://github.com/libuv/libuv/issues/2759
~~CI: https://ci.nodejs.org/job/libuv-test-commit/1826/~~ (doesn't work)
~~CI: https://ci.nodejs.org/job/libuv-test-commit-windows/2023/~~ ✅
CI: https://ci.nodejs.org/job/libuv-test-commit/1828/ ✅
<details>
~~@libuv/windows this needs your input because I'm not sure what adverse effects this could have or if it introduces new failure modes.~~
~~It changes the current "libuv won't load" failure mode to "uv_random() won't work." That seems like an improvement.~~
~~Is dynamically loading advapi32.dll a security risk on multi-user systems? If the answer is 'yes', then why do we load powrpof.dll and user32.dll that way?~~
(resolved by way of using `SystemFunction036()` directly.)
</details>

win: use LoadLibrary to load advapi32.dll

---

docs/src/misc.rst
include/uv.h
src/threadpool.c
src/unix/aix.c
src/unix/bsd-proctitle.c
src/unix/internal.h
src/unix/no-proctitle.c
src/unix/proctitle.c
src/unix/signal.c
src/uv-common.c
src/uv-common.h
src/win/signal.c
src/win/util.c
test/task.h

Make it possible to explicitly tell libuv to release any resources
it's still holding onto (memory, threads, file descriptors, etc.)
Before this commit, cleanup was performed in various destructors.
This commit centralizes the cleanup logic, enabling the addition of
`uv_library_shutdown()`, but maintains the current observable behavior
of cleaning up when libuv is unloaded by means of `dlclose(3)`.
Fixes: https://github.com/libuv/libuv/issues/2763
CI: https://ci.nodejs.org/job/libuv-test-commit/1829/

unix,win: add uv_library_shutdown()

---

src/unix/udp.c
src/uv-common.c
src/uv-common.h
src/win/udp.c
test/test-udp-options.c

Commit 5736658b ("udp: add flag to enable recvmmsg(2) explicitly") added
the flag but didn't update the validation logic in src/win/udp.c.
This commit moves the validation logic to src/uv-common.c. The flag is
now accepted as a no-op on Windows.
Fixes: https://github.com/libuv/libuv/issues/2806
CI: https://ci.nodejs.org/job/libuv-test-commit/1873/

win: make uv_udp_init_ex() accept UV_UDP_RECVMMSG

---

docs/src/check.rst
docs/src/idle.rst
docs/src/prepare.rst

Make the documentation reflect that the init/start/stop functions
for check/idle/prepare handles always succeed.

doc: check/idle/prepare functions always succeed

---

Makefile.am
src/unix/darwin-proctitle.c
src/unix/darwin-stub.h
src/unix/fsevents.c

The header files for ApplicationServices and CoreFoundation contain
C language extensions that Apple's compiler understands but gcc does
not, notably blocks:
https://en.wikipedia.org/wiki/Blocks_(C_language_extension)
Work around that by defining the types inline and stop including
the headers. It's inelegant but the alternatives are worse.
Fixes: https://github.com/libuv/libuv/issues/2805
CI: https://ci.nodejs.org/job/libuv-test-commit/1875/

darwin: fix build with non-apple compilers

---

src/unix/udp.c

Commit 3d713663 ("freebsd,linux: add recvmmsg() + sendmmsg() udp
implementation") forgot to zero some of the members of the msghdr
struct. It seems to work by accident, not by design.
Refs: https://github.com/libuv/libuv/pull/2818
CI: https://ci.nodejs.org/job/libuv-test-commit/1888/

unix: fully initialize struct msghdr

---

.github/workflows/CI.yml

The QEMU CI broke recently. The calculation to determine the QEMU
version to install now returns multiple versions. This commit
updates the logic to only take the last result (which I think will
be the newest matching version).

test: use last matching qemu version

---

CMakeLists.txt
Makefile.am
src/unix/linux-core.c

It was reported that uv_loadavg() reports the wrong values inside an
lxc container.
Libuv calls sysinfo(2) but that isn't intercepted by lxc. /proc/loadavg
however is because /proc is a FUSE fs inside the container.
This commit makes libuv try /proc/loadavg first and fall back to
sysinfo(2) in case /proc isn't mounted.
This commit is very similar to commit 3a1be72 ("linux: read free/total
memory from /proc/meminfo") from April 2019.
Fixes: nodejs/node#33791
CI: https://ci.nodejs.org/job/libuv-test-commit/1929/
The first commit is a small refactor to promote code reuse.

linux: read load average from /proc/loadavg

---

src/unix/core.c
src/unix/fs.c
src/unix/kqueue.c
src/unix/linux-core.c
src/unix/os390-syscalls.c
src/unix/pthread-fixes.c
src/unix/tcp.c
src/uv-common.c
src/uv-common.h

Make ThreadSanitizer stop complaining about the static variables that
libuv uses to record the presence (or lack) of system calls and other
kernel features.
Fixes: https://github.com/libuv/libuv/issues/2884
~~CI: https://ci.nodejs.org/job/libuv-test-commit/1933/~~
CI: https://ci.nodejs.org/job/libuv-test-commit/1934/

unix: use relaxed loads/stores for feature checks

---

m4/.gitignore

It was reported that the addition of that file without adding an
exception to m4/.gitignore breaks the tarball autotools build because
the file isn't distributed.
Fixes: https://github.com/libuv/libuv/issues/2862

build: don't .gitignore m4/ax_pthread.m4

---

src/unix/darwin.c

It was reported that mach_absolute_time() can jump backward in time when
the machine is suspended. Use mach_continuous_time() when available to
work around that (macOS 10.12 and up.)
Fixes: https://github.com/libuv/libuv/issues/2891
CI: https://ci.nodejs.org/job/libuv-test-commit/1938/

darwin: use mach_continuous_time() when available

---

CMakeLists.txt
Makefile.am
src/unix/udp.c
test/test-list.h
test/test-udp-sendmmsg-error.c

This issue manifested on `connected` udp sockets trying to send
datagrams to a non-existent server and returning `ECONNREFUSED` because
an ICMP error was received before the actual sending was performed.

udp: fix write_queue cleanup on sendmmsg error

---

CMakeLists.txt

MinGW prefers a POSIX like file system hierarchy. Therefore, it is appropriate that the installation destination is the same as UNIX.

build,cmake: Change installation location on MinGW

---

src/unix/fs.c
src/unix/linux-syscalls.c
src/unix/linux-syscalls.h

According to [the man page](http://www.man7.org/linux/man-pages/man2/copy_file_range.2.html#NOTES):
> copy_file_range() gives filesystems an opportunity to implement "copy acceleration" techniques, such as the use of reflinks (i.e., two or more inodes that share pointers to the same copy-on-write disk blocks) or server-side-copy (in the case of NFS).
Thus copy_file_range may provide better performance on certain devices.
Tested on Linux archlinux-pc 5.1.15-arch1-1-ARCH
Ref: https://github.com/libuv/libuv/issues/925#issuecomment-234696227

linux: use copy_file_range for uv_fs_copyfile when possible

---

CMakeLists.txt
Makefile.am
src/win/tcp.c
test/test-list.h
test/test-tcp-read-stop-start.c

This fix avoids inserting a duplicate pending request in the case where
`WSARecv()` returns an error (e.g. when a connection has been terminated by its
peer) when `uv_read_start()` is called in a read callback.

win, tcp: fix to avoid reinserting a pending request

---

docs/src/udp.rst
include/uv.h
src/unix/udp.c
src/win/udp.c
test/test-udp-mmsg.c

Allows for determining if a buffer large enough for multiple dgrams should be allocated in `alloc_cb` of `uv_udp_recvstart`. See #2822 for more details.
For an example of how this would be used, see https://github.com/squeek502/libuv/commit/48e2e7d3baa9a4839e744445b4488381a105e8cd which alters the test added in #2818 to use `uv_udp_is_using_recvmmsg`
~~EDIT: Note that this PR changes the `UV_HANDLE_UDP_RECVMMSG` flag to only be set on the `uv_udp_t` handle if the platform actually supports `recvmmsg`.~~ (no longer the case)
---
I think it's also worth addressing this:
> One other thing is that, due to how the number of dgrams read via `recvmmsg` is reliant on multiples of [`UV__UDP_DGRAM_MAXSIZE`](https://github.com/libuv/libuv/blob/2bbf7d5c8cd070cc8541698fe72136328bc18eae/src/unix/udp.c#L …

udp: add uv_udp_using_recvmmsg

---

docs/src/dns.rst
docs/src/fs.rst
docs/src/request.rst
docs/src/threadpool.rst
include/uv.h
src/random.c
src/threadpool.c
src/unix/fs.c
src/unix/getaddrinfo.c
src/unix/getnameinfo.c
src/uv-common.h
src/uv-data-getter-setters.c
src/win/core.c
src/win/fs-event.c
src/win/fs.c
src/win/getaddrinfo.c
src/win/getnameinfo.c
src/win/pipe.c
src/win/poll.c
src/win/process.c
src/win/signal.c
src/win/stream-inl.h
src/win/stream.c
src/win/tcp.c
src/win/tty.c
src/win/udp.c
test/test-getters-setters.c

Hi,
The rationale of this patch is pretty simple: Being able to easily access the loop from an uv_req_t.
Most of the uv_req_t expose a loop member, and there is room inside uv_req_t to get the pointer without breaking binary compatibility.
Documentation and source is updated accordingly, aiming this patch to land in 1.25.0 release because of the new symbol.
Change was build and tested on linux (need real world testing for binary compatibility). Windows platform was blindly edited without any compile checking.
Please review/comment.
Thanks.

API: Pull up loop to uv_req_t.

---

docs/src/errors.rst

added some error constants to doc
<code>UV_ENOTTY</code>, <code>UV_EFTYPE</code>, <code>UV_EILSEQ</code>

doc: add error constants

---

CMakeLists.txt
Makefile.am
docs/src/api.rst
docs/src/loop.rst
docs/src/metrics.rst
include/uv.h
src/unix/aix.c
src/unix/core.c
src/unix/kqueue.c
src/unix/linux-core.c
src/unix/loop.c
src/unix/os390.c
src/unix/posix-poll.c
src/unix/sunos.c
src/uv-common.c
src/uv-common.h
src/win/core.c
test/test-list.h
test/test-metrics.c

This PR contains code that I've been working on for a while as part of some research I've been doing at work, and decided it would be good to submit this for review after seeing @indutny's Node.js PR https://github.com/nodejs/node/pull/32018.
The main reasons for writing this patch are:
- Have very accurate measurements of idle time spent in the kernel's event provider.
- Allow retrieval of the idle time from another thread to allow more accurate time-series data collection (instead of only collecting the data when the event loop can process a callback).
A lot is explain in the commit message below, and I'll be happy to explain in detail why the implementation was done this way. For example, this approach was a conclusion I came to last year after researching whether it was possible to …

Add API for measuring event loop idle time

---

src/win/fs-fd-hash-inl.h
src/win/fs.c
src/win/tty.c
src/win/util.c

fix some warnings from MinGW compiler while compiling on win
See #2790

win: fix some MinGW warnings

---

test/test-process-title-threadsafe.c

Libuv calls uv__process_title_cleanup() on shutdown, which raced with
one of the threads from the test that calls uv_get_process_title() in
an infinite loop. Change the test to properly shut down the thread
before exiting.
Refs: https://github.com/libuv/libuv/pull/2853#issuecomment-665259082
CI: https://ci.nodejs.org/job/libuv-test-commit/1978/

test: fix thread race in process_title_threadsafe

---

test/test-list.h

The test is supposed to complete in about 3.5s but it can
hit the 10s timeout when run on a system with high load.
Fixes: https://github.com/libuv/libuv/issues/2342 (hopefully?)
Refs: https://github.com/libuv/libuv/pull/2345
CI: https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/170/
CI: https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/171/

test: give hrtime test a custom 20s timeout

---

.github/workflows/CI.yml
test/test-getaddrinfo.c
test/test-getnameinfo.c
test/test-thread.c
test/test-tty.c

Fix: #2937
`qemu-user-static_4.2-3ubuntu9_amd64.deb` and `qemu-user-static_4.2-3ubuntu8_amd64.deb` works fine.
But `qemu-user-static_4.2-3ubuntu10_amd64.deb` has regressions, and break the tests.
And ubuntu don't keep old deb files.
In the long run:
* will qemu team will make to test libuv in their workflow.
* should we switch to docker build to make test more stable ? we can install qemu in docker, and the version will be stable. And preinstall all toolchains, looks like ubuntu makes a bug on installing 
deps https://github.com/libuv/libuv/pull/2939/checks?check_run_id=949787423

build: add more failed test for qemu version bump

---

CMakeLists.txt
Makefile.am
docs/src/misc.rst
src/unix/aix-common.c
src/unix/aix.c
src/unix/core.c
src/unix/ibmi.c
src/unix/internal.h
src/unix/os390.c
test/test-get-currentexe.c

Store a copy of the original argv[0] to protect `uv_exepath()`
against `uv_set_process_title()` changing the value of argv[0].
Since `uv_exepath()` is in `src/unix/aix-common.c`.
cc @dmabupt re. IBMi
Changes assume it is possible for `uv_setup_args()` not to 
be called prior to `uv_exepath()` being called (current 
[documentation for `uv_setup_args()`](http://docs.libuv.org/en/v1.x/misc.html#c.uv_setup_args) says that it is
"Required for getting / setting the process title.") in 
which case the existing code is used. Our test runner always
calls `uv_setup_args()` prior to running any tests.
Fixes: https://github.com/libuv/libuv/issues/2674
CI: https://ci.nodejs.org/job/libuv-test-commit/1985/

aix: protect uv_exepath() from uv_set_process_title()

---

src/unix/fs.c
src/win/fs.c
test/test-fs.c

Contents of template variable passed for posix call mkstemp on error
code EINVAL is unknown. On AIX platform, template will get clobbered
on EINVAL and any attempt to read template might result in error.
In libuv, req->path is passed directly to the mkstemp call and
behavior of this string on error is platform dependent. To avoid
portability issues, it's better to have a common behavior on all
platform. For both unix and windows platform libuv will rewrite path
with with an empty string on all error cases.
Ref: https://github.com/libuv/libuv/issues/2913

fs: clobber req->path on uv_fs_mkstemp() error

---

CMakeLists.txt
Makefile.am
test/task.h
test/test-list.h
test/test-test-macros.c

Passing expression as an argument to a function-like macro will
replace all occurrence of the arguments with expressions during
preprocessing. This result in multiple evaluation of the same
expression and can slow-down the program or even change program
state. Here ASSERT_BASE macro gets an expression involving a
and b as first argument and macro definition has a print
statement with a and b, which means there is double evaluation
of a and b when the expression evaluates to false. To avoid
double evaluation temporary variables are created to store
results of a and b.
Since the expression argument is dropped from ASSERT_BASE,
the macro no longer works for string assertions. So a new macro,
ASSERT_BASE_STR, is introduced to deal with strings. ASSERT_BASE
can still work with pointers.
Fix …

test: Avoid double evaluation in ASSERT_BASE macro 

---

docs/src/async.rst
docs/src/errors.rst
docs/src/fs.rst
docs/src/guide/filesystem.rst
docs/src/guide/networking.rst
docs/src/guide/processes.rst
docs/src/guide/utilities.rst
docs/src/handle.rst
docs/src/loop.rst
docs/src/process.rst
docs/src/request.rst
docs/src/sphinx-plugins/manpage.py
docs/src/tty.rst
docs/src/udp.rst

sphinx didn't like that the syntax of these was wrong, leading to loss of formatting in the html, and other minor nits.
I left this one, since I don't really like the valid syntax version (the [] should be on the right of the variable name):
```
docs/src/dns.rst:54: WARNING: Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name. [error at 4]
char[NI_MAXHOST] uv_getnameinfo_t.host
----^
docs/src/dns.rst:60: WARNING: Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name. [error at 4]
char[NI_MAXSERV] uv_getnameinfo_t.service
----^
```

doc: fix most sphinx warnings

---

include/uv/errno.h

https://github.com/libuv/libuv/pull/2979 negated the value of
UV__EPROTO on platforms that don't define EPROTO, but it didn't
remove the surrounding UV__ERR() call. This was causing numerous
test failures in Node.js.

include: remove incorrect UV__ERR() for EPROTO

---

docs/src/tcp.rst
src/unix/tcp.c
src/win/tcp.c
test/echo-server.c
test/test-list.h
test/test-tcp-bind-error.c

Fix a bug where libuv forgets about EADDRINUSE errors reported earlier:
uv_tcp_bind() + uv_tcp_connect() seemingly succeed but the socket isn't
actually bound to the requested address.
This bug goes back to at least 2011 if indeed it ever worked at all.
CI: https://ci.nodejs.org/job/libuv-test-commit/1260/

unix: report bind error in uv_tcp_connect()

---

docs/src/poll.rst

Added notes to documentation of `uv_poll_t`:
- The callback will be called over-and-over again as long as the socket
remains readable/writable.
- uv_pool_stop() cancels pending callbacks of already happened events.
https://github.com/libuv/libuv/issues/1078

doc: poll: add notes (repeated cb & cancel pending cb)

---

src/unix/linux-syscalls.c

The seccomp filter with older Android SDKs kills the process when libuv
tries to make system calls it doesn't know about.
This commit adds ifdef guards that stop libuv from making those system
calls with affected SDKs.
Fixes: https://github.com/libuv/libuv/issues/2923
CI: https://ci.nodejs.org/job/libuv-test-commit/2079/
<hr>
I apparently forgot to PR this back in July...

android: add system call api guards

---

docs/src/stream.rst
src/unix/stream.c
src/uv-common.c
src/uv-common.h
src/win/stream.c
test/test-pipe-getsockname.c
test/test-shutdown-eof.c
test/test-tcp-bind-error.c

The behavior of `uv_read_start()` when the handle is closing or already
busy reading wasn't consistent across platforms. Now it is.
Fixes: libuv/help#137
CI: https://ci.nodejs.org/job/libuv-test-commit/1869/
The second commit also checks the arguments.

unix,win: harmonize uv_read_start() error handling

---

src/timer.c

With the addition of `uv_timer_get_due_in()` it's observable with tools like
valgrind that the `timer->timeout` field isn't initialized until the timer
is started.
Fixes the following valgrind warning when running the `timer_init` test:
==325215== Conditional jump or move depends on uninitialised value(s)
==325215==    at 0x1B0131: uv_timer_get_due_in (timer.c:134)
==325215==    by 0x19AF09: run_test_timer_init (test-timer.c:164)
==325215==    by 0x119FF1: run_test_part (runner.c:376)
==325215==    by 0x11875D: main (run-tests.c:68)
==325215==
==325215== Conditional jump or move depends on uninitialised value(s)
==325215==    at 0x19AF1F: run_test_timer_init (test-timer.c:164)
==325215==    by 0x119FF1: run_test_part (runner.c:376)
==325215==    by 0x11875D: main (run-tests.c:68)
Fixes: …

unix,win: initialize timer `timeout` field

---

src/unix/bsd-ifaddrs.c

While going through the source code, I found a comment that referred to `operation system`. Probably the committer meant `operating system`. So I reworded the sentence a bit. Also I removed a double space in another comment nearby.

unix: improve comment

---

src/unix/fs.c
src/win/fs.c
test/task.h
test/test-fs.c
test/test-list.h

`uv_fs_utime()` and `uv_fs_futime()` receive the timestamp as
a `double` and then convert it to `struct timeval` or `struct timespec`
where necessary but the calculation for the sub-second part exhibited
rounding errors for dates in the deep past or the far-flung future,
causing the timestamps to be off by sometimes over half a second.
Fixes: nodejs/node#32369 (partially)
~~CI: https://ci.nodejs.org/job/libuv-test-commit/1806/~~
~~CI: https://ci.nodejs.org/job/libuv-test-commit/1817/~~
CI: https://ci.nodejs.org/job/libuv-test-commit/1825/

unix: fix utime/futime timestamp rounding errors

---

src/unix/fs.c
test/test-fs.c

Fix the `off_in` argument  in `copy_file_range()`.
Fixes: https://github.com/libuv/libuv/issues/3056

unix,fs: fix uv_fs_sendfile()

---

CMakeLists.txt
Makefile.am
src/unix/core.c
src/unix/poll.c
test/test-list.h
test/test-poll-multiple-handles.c

Consider the following scenario:
```
uv_poll_init(loop, poll, fd);
uv_poll_start(poll, UV_READABLE, cb);
// the cb gets invoked etc.
uv_poll_stop(poll);
// some time later:
uv_poll_init(loop, otherpoll, fd);
uv_poll_start(otherpoll, UV_READABLE, cb);
uv_close(poll); // uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
```
Reasons to change this:
- This was hard to track down. (In particular for users using the bindings for other languages, they don't know to debug the C state properly.)
- This turned out to be a very dangerous issue due to the poll handle being closed as part of a delayed garbage collection. The point in time was very much non-deterministic and it would or would maybe not happen for a long time, depending on whether there was another poll handle alive at the …

fix: Do not stop the poll watcher twice

---

src/unix/linux-core.c

As it was in the original version of
https://github.com/libuv/libuv/pull/3072, `%lf` must be used in
`sscanf()` as the value is being stored in a `double` and not a `float`.
From the `fscanf()` section of the `C99` standard:
> l(ell)           Specifies that a following d,i,o,u,x,X, or n conversion specifier applies to  an  argument  with  type  pointer  to long  int or unsigned  long int;that a following a,A,e,E,f,F,g, or G conversion specifier applies to an  argument  with  type  pointer  to double; or that  a  following c,s,or [ conversion specifier applies to an argument with type pointer to wchar_t.

unix: fix uv_uptime() regression

---

docs/src/pipe.rst
docs/src/tcp.rst

This commit adds the `versionadded` metadata for `uv_pipe()` and `uv_socketpair()`.
Refs: https://github.com/libuv/libuv/pull/2953

doc: fix versionadded metadata

---

src/unix/process.c

This PR tackles #3050.
With Big Sur (macOS 11), apple introduced a significant performance degradation when trying to `fork()`/`exec` a new child process when the parent has many pages mmaped with `MAP_JIT` (like, say, a javascript interpreter). At the same time, on macOS spawning a subprocess with `posix_spawn` (as chromium does) does not incur on the overhead. 
This bug impacts electron apps that spawn subprocess, like for example, [VSCode](https://github.com/microsoft/vscode/issues/105446#issuecomment-729274600). There is an issue filed against [electron itself](https://github.com/electron/electron/issues/26143) as a consequence. 
Using the [repro app](https://github.com/deepak1556/libuv-spawn) from the issue, I implemented the forking logic specific to macOS using posix_spawn, as far …

darwin: Use posix_spawn to spawn subprocesses in macOS

---

src/unix/process.c

This reverts commit 39968db6434f16f9fbd3c78f6c7392fd7ae9074e.
This commit caused a number of failures in the Node.js test suite
while attempting to release libuv 1.41.0.
Node.js integration CI: https://ci.nodejs.org/view/libuv/job/libuv-in-node/175/. The previously observed macOS failures seem to be fixed by this revert.

Revert "macos: use posix_spawn instead of fork"

---

CMakeLists.txt
README.md
src/unix/fs.c
src/unix/os390-proctitle.c
src/unix/os390-syscalls.c
src/unix/os390-syscalls.h
src/unix/os390.c
src/unix/process.c
test/run-benchmarks.c
test/run-tests.c
test/test-fs.c

This PR is for building libuv on z/OS systems. The PR make changes to build libuv in ASCII code page, and introduce a dependency on [ZOSLIB](https://github.com/ibmruntimes/zoslib) to enable this transition.
[ZOSLIB](https://github.com/ibmruntimes/zoslib) is a z/OS C/C++ library which implements additional POSIX APIs that are not available in the LE C Runtime Library, and provides API for EBCDIC <-> ASCII conversion. ZOSLIB can be installed separately on the system, and then linked to libuv using the `-DZOSLIB_DIR` option introduced by this PR.

zos: build in ASCII code page and introduce zoslib

---

src/unix/ibmi.c

IBM i interface names are based off the associated line description.
Since line descriptions are objects, they have 10 character limit on
their names. However, since IBM i 7.2 interface names may be up to 16
characters long if the interface is for a a VLAN (eg. MYETHLINE1.4094).
To handle this, we must strip off a VLAN ID to get the actual line
description name, since that's what the QDCRLIND API wants. One issue
exists because line descriptions can contain periods and numbers; so
for interface names less than 10 characters long ETH2.4 could be a line
description name or it could be ETH2 with VLAN 4. We follow the
method that the XPF ioctls use: try the interface name directly first
and if an error occurs, try to strip off the VLAN ID. …

ibmi: Handle interface names longer than 10 chars

---

src/unix/stream.c

the previous implementation was `uv_write + uv_cancel`, it's too hack
If this pr is acceptable, I hope we can implement `uv_try_write2` and it always returns `UV_EAGAIN` when `send_handle != NULL` on WIN
ping @bnoordhuis

unix: refactor uv_try_write

---

src/unix/linux-core.c

Apparently, we should assert the non-existence of dividing by zero before performing the actual division. This eliminates any undefined behavior.

Add proper divide by zero protection

---

src/unix/getaddrinfo.c
src/unix/linux-syscalls.h

Since we are building with the `-D_GNU_SOURCE` option turned on, the macro
definitions are not needed anymore.
Refs: https://github.com/libuv/libuv/pull/3165#issuecomment-835747442

misc: remove unnecessary `_GNU_SOURCE` macros

---

test/runner.c

Hi!
I replaced the stderrs in the test runner with stdouts, since the TAP specification [1] explicitely states:
`A harness must only read TAP output from standard output and not from standard error.`
Best regards
bb
[1] https://testanything.org/tap-specification.html

test: log to stdout to conform TAP spec

---

src/win/fs.c

When compiling the current code MSVC prints this warning:
warning C4090: '=': different 'const' qualifiers
This warning was introduced with dc6fdcd where the `(char*)` cast for
the call to `wcstombs` was removed.
Readding this cast to silence the warning.

win,fs: fix C4090 warning with MSVC

---

configure.ac

libuv is packaged for OmniOS, an illumos distribution (OpenSolaris fork), and on that platform `libdl.so` is just a legacy stub library that does not need to be linked; `dlopen()` and friends are present in libc.
Changing to using `AC_SEARCH_LIBS()` instead of `AC_CHECK_LIB()` stops the unnecessary linking of libdl.

Some systems provide dlopen() in libc

---

CMakeLists.txt

This allows to build uv.dll not linked to MSVC runtime, with a simple cmake flag to configure.
The naming has been inspired by [SDL2's cmake](https://github.com/spurious/SDL-mirror/blob/master/CMakeLists.txt#L225).

win: Add cmake STATIC_VCRT option to force /MT build flag

---

src/win/util.c

Windows API gethostname(buffer, size) return unicode string in char
array. It will cause grabled code if the host name contains non ascii
characters without cast into multi byte char.
This change keep the same encoding with the implementation on
unix/macOs platform, which is "utf-8"
Fix issue #3148

win: fix encoding issue of uv_os_gethostname() 

---

CMakeLists.txt

Reverts libuv/libuv#3085 as it broke the android CI worker.
CMake 3.15 might be somewhat newer than we want to require. Currently Android CI is using 3.10 because of https://github.com/react-native-community/docker-android/blob/96ea6a470eff4d77bd89bddfa0d1d7029092b165/Dockerfile#L76

Revert "win: Add cmake STATIC_VCRT option to force /MT build flag"

---

src/unix/process.c

Reading the code reveals a lot of repetition, here the logic is simplified using `uv__write_errno`.

unix,process: replace uv__write_int with uv__write_errno

---

CMakeLists.txt
Makefile.am
src/unix/stream.c
src/win/tcp.c
test/echo-server.c
test/test-list.h
test/test-not-readable-nor-writable-on-read-error.c
test/test-not-readable-on-eof.c
test/test-not-writable-after-shutdown.c

This reverts commit 46f36e3df1a666620f6749427f15651cbc4b7001. Make this PR as a placeholder to remember that nodejs needs to be debugged with it.
Identical to: https://github.com/libuv/libuv/pull/2967
Refs: https://github.com/libuv/libuv/pull/2409
Refs: https://github.com/libuv/libuv/issues/2943
Refs: https://github.com/libuv/libuv/pull/2968

Revert "Revert "unix,stream: clear read/write states on close/eof""

---

src/inet.c

inet_ntop6 return value is inconsistent with  inet_ntop4 when size is 0.
It seems more reasonable to return UV_ENOSPC in this case.
```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <arpa/inet.h>
int main()
{
struct sockaddr_in6 src = {};
const char* p = inet_ntop(AF_INET6, &src.sin6_addr, NULL, 0);
printf("p=%p, error=%s\n", p, strerror(errno));
return 0;
}
```
output:
```
p=0x0, error=No space left on device
```

inet: fix inconsistent return value of inet_ntop6

---

docs/src/stream.rst
include/uv.h
src/unix/stream.c
src/win/stream.c

it is reasonable for me to keep the `uv_try_write*` methods and `uv_write*` functions aligned. And things seem clearer after we refactored `uv_try_write`.
`uv_try_write2(stream, bufs, nbufs, send_handle)` acts like `uv_try_write()` and extended write function for sending handles over a pipe like `uv_write2`.
it always returns `UV_EAGAIN` instead of `UV_ENOSYS` on Windows so we can easily write cross-platform code without special treatment.

stream: introduce uv_try_write2(...)

---

src/win/fs.c
test/test-fs-open-flags.c

Just like the unix counterpart, `uv_fs_read` and `uv_fs_write` should
throw an `EBADF` instead of manually throwing an `EPERM` when the passed
`fd` has not been opened with the right flags.

win,fs: correct error code in uv_fs_read and uv_fs_write

---

src/threadpool.c
src/uv-common.c

The _WIN32 guards appear to be remnants of another time. Begone with them!
/cc @bnoordhuis @cjihrig @addaleax 
Fixes: https://github.com/libuv/libuv/issues/2980
Refs: https://github.com/nodejs/node/pull/35021
Signed-off-by: James M Snell <jasnell@gmail.com>

Remove _WIN32 guards on threadpool.c

---

src/unix/core.c
src/unix/internal.h
src/unix/poll.c

These functions are declared with one set of conditionals in the
header, and defined with another set of conditionals in the c file.
This commit picks the more specific set of conditions and switches
the conditions in the c file to those.
(the aforementioned conditions in the header: https://github.com/libuv/libuv/blob/v1.x/src/unix/internal.h#L169-L182)

core: Correct the conditionals for {cloexec,nonblock}_ioctl

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
README.md
docs/code/dns/main.c
docs/src/guide/networking.rst

Freenode is gone (replaced by Libera.chat), but IRC was unused anyways.
Fixes: https://github.com/libuv/libuv/issues/3157
Fixes: https://github.com/libuv/libuv/issues/3208

doc: switch discussion forum to github

---

src/unix/tty.c

uv_tty_set_mode() allows a tty device to be set to raw mode with
UV_TTY_MODE_RAW, which correctly sets MIN and TIME to appropriate values
for character input.  When UV_TTY_MODE_IO is passed, on illumos systems
a compatibility implementation of cfmakeraw() is used that does _not_
set MIN or TIME.  As a result, consumers of IO mode will block until a
minimum of 4 bytes is available on the tty instead of just 1 as is
expected.

unix/tty: UV_TTY_MODE_IO waits for 4 bytes at a time on illumos

---

src/unix/linux-core.c

Fixes: https://github.com/libuv/libuv/issues/3217

linux: read CPU model information on ppc

---

CMakeLists.txt
Makefile.am
src/unix/stream.c
test/echo-server.c
test/test-list.h
test/test-shutdown-simultaneous.c

While normally, users will likely typically call uv_close in their
uv_shutdown callback, some callers (notable nodejs) do not. This can
result in libuv keeping the loop active, even though there are no
outstanding reqs left to handle.
This bug was added in 80f2f826bf90b84e659321c0b7fd8af419acb85e, where
the premise of that commit was simply incorrect, as demonstrated by the
added test. (@bnoordhuis)
Refs: https://github.com/libuv/libuv/issues/3202#issuecomment-874961223
CI: https://ci.nodejs.org/job/libuv-test-commit/2178/ + https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/371/
CI+node: ~~https://ci.nodejs.org/view/libuv/job/libuv-in-node/186/~~ https://ci.nodejs.org/view/libuv/job/libuv-in-node/187/

unix,stream: fix shutdown hang

---

docs/src/udp.rst
src/unix/udp.c
src/uv-common.h
src/win/udp.c

Note: I'm not super convinced this is totally necessary/the best way to do this.
The intention here is to make working with recvmmsg more straight-forward, since internally Libuv expects buffers that are multiples of UV__UDP_DGRAM_MAXSIZE, but previously that wasn't totally obvious (from my perspective at least).
This would be the final part of #2822. If merged, closes #2822.

udp: ensure that suggested_size in alloc_cb of recv_start is 1 max size dgram

---

src/unix/internal.h
src/unix/sunos.c

strnlen is not available, fall back to using memchr instead of adding compatibility code as this is the only use of strnlen in the tree

unix: strnlen is not available on Solaris 10

---

CMakeLists.txt
Makefile.am
src/unix/sunos.c

The sunos platform currently covers at least the Solaris and illumos
operating systems. Although these diverged 11 years ago they still share
some common features such as support for event ports.
illumos also has a compatibility wrapper for epoll but this is not
recommended for use over event ports. From the NOTES section of
https://illumos.org/man/5/epoll:
The epoll facility is implemented for purposes of offering
compatibility to and portability of Linux-borne
applications; native applications should continue to prefer
using event ports... In particular, use of epoll in a
multithreaded environment is fraught with peril...
Restore the event ports code so that libuv can continue to be used
on Solaris, and to avoid the problems that come with using epoll()
on illumos. The separation of …

sunos: restore use of event ports

---

CMakeLists.txt

On illumos, the global errno variable is not thread-safe by default,
requiring that the application be built with gcc's -pthread option, or
that it defines -D_REENTRANT.
This is done correctly for the autotools build, but not for the CMake
one.

sunos: use thread-safe errno

---

test/test-tty-escape-sequence-processing.c

test: fix typo in test-tty-escape-sequence-processing.c

---

src/win/process.c

PR to fix the issue #3159.
The origin [issue](https://gitlab.kitware.com/cmake/cmake/-/issues/22141) is on CMake side: **CTest cannot run executable from network path**.

win: Allow UNC path with forward slash

---

SUPPORTED_PLATFORMS.md

There haven't been active maintainers for this platform for a long time
so back to tier 3 it goes.

doc: mark SmartOS as Tier 3 support

---

src/win/util.c
src/win/winapi.c
src/win/winapi.h

Commit e9c524aa from pull request https://github.com/libuv/libuv/pull/3149 introduced a hard dependency on `GetHostnameW`, which isn't declared yet in mingw distributions (see https://github.com/msys2/MINGW-packages/issues/9667).
This prevents the current version of libuv from building on many mingw distributions, until such time the next version of mingw is released with the correct definition for GetHostnameW, preventing a lot of projects depending on libuv from building on mingw properly, as not all distributions will update to head immediately anyway.
Instead of waiting, let's find the definition ourselves using GetProcAddress and use the pointer instead.

Fixing build for mingw32

---

include/uv/win.h

A structure definition was added to `mstcpip.h` in mingw-w64-x86_64-headers-git 9.0.0.6327.f29c1101f, which causes a conflict and the build fails. Fix this by changing the name in the definition in `mstcpip.h`.
Ref. https://github.com/msys2/MINGW-packages/issues/9946
<details><summary>Build Log</summary>
```
2021-10-30T11:01:33.6596333Z -- Build files have been written to: D:/a/neovim/neovim/nvim-deps/build/src/libuv
2021-10-30T11:01:34.8718790Z [89/137] cmd.exe /C "cd /D D:\a\neovim\neovim\nvim-deps\build\src\libuv && C:\msys64\mingw64\bin\cmake.exe --build . --config RelWithDebInfo && C:\msys64\mingw64\bin\cmake.exe -E touch D:/a/neovim/neovim/nvim-deps/build/src/libuv-stamp/libuv-build"
2021-10-30T11:01:34.8720621Z FAILED: build/src/libuv-stamp/libuv-build …
```

build: fix build failures with MinGW-w64 new headers

---

src/unix/linux-core.c

This is the result of `platform_output` test, before this PR the "model" value was: "unknown".
These changes were develop in an aarch64 VM in aws
```bash
uv_get_process_title: build/uv_run_tests_a
uv_cwd: /home/ubuntu/libuv
uv_resident_set_memory: 794624
uv_uptime: 597488.500000
uv_getrusage:
user: 0 sec 1003 microsec
system: 0 sec 0 microsec
page faults: 0
maximum resident set size: 3264
uv_cpu_info:
model: Neoverse-N1
speed: 0
times.sys: 88210
times.user: 183090
times.idle: 597098570
times.irq: 0
times.nice: 13710
model: Neoverse-N1
speed: 0
times.sys: 95720
times.user: 183360
times.idle: 597009280
times.irq: 0
times.nice: 11790
uv_interface_addresses:
name: lo
internal: 1
physical address: 00:00:00:00:00:00
address: 127.0.0.1
netmask: 255.0.0.0
name: ens5
internal: 0
physical address: …
```

unix: support `aarch64` in `uv_cpu_info`

---

include/uv.h
test/test-fs.c

Oracle Solaris linker visibility support.  Option "-fvisibility=hidden"
requires public functions to be defined as "__global".
fs_utime_round test failed as timespec.tv_nsec conversion to double
resulted in negative number.  Skipped this test.
Note that it was necessary to compile with C99 language features.

include,test,sunos: Oracle Developer Studio support.

---

include/uv.h
test/test-fs.c

Reverts libuv/libuv#3364
The PR was reported to break libuv on Illumos systems.

Revert "include,test,sunos: Oracle Developer Studio support."

---

CMakeLists.txt
Makefile.am
src/unix/stream.c
src/win/pipe.c
src/win/tcp.c
test/test-list.h
test/test-readable-on-eof.c

On some streams (notably TTYs), it is permitted to continue reading
after getting EOF. So still stop reading on EOF, but allow the user to
reset the stream and try to read again (which may just get EOF).
This relaxes the constraint added in ce15b8405e9d01e221f8390475deab4a40d26e38.
Refs: https://github.com/libuv/libuv/pull/3006
Fixes: https://github.com/JuliaLang/julia/issues/42937

stream: permit read after seeing EOF

---

src/win/thread.c
test/test-thread-equal.c

In particular, previously the main thread would have an id of NULL, which was then not valid to use with any other API that expected a uv_thread_t handle.
It is expected that if you call `uv_thread_self` on any thread, eventually you will call `uv_thread_join` or `uv_thread_detach` on that thread id, which will release this handle again and avoid a resource leak.

thread: initialize uv_thread_self for all threads

---

src/unix/kqueue.c

The combination EVFILT_WRITE+EV_EOF is valid and indicates that the
reader has disconnected (called `shutdown(SHUT_RD)`). Probably very rare
in practice, but this seems more correct.
Issue noticed (for UV_DISCONNECT clients of uv_poll), while doing
research for https://github.com/libuv/libuv/pull/3250.

kqueue: ignore write-end closed notifications

---

src/unix/darwin.c

https://github.com/libuv/libuv/issues/3355
The fix is to use the cfdata length related to the data we want to interpret & then cast the data accordingly.

Fix for issue 3355

---

CMakeLists.txt
Makefile.am
docs/src/misc.rst
include/uv.h
src/uv-common.c
test/test-ip-name.c
test/test-list.h

discussion #3365 
uv_ip_name is a kind of wrapper of uv_ip4_name and uv_ip6_name which can be used after getaddrinfo to get the IP name directly from addrinfo.ai_addr.
I haven't found a test just for `uv_ip*_name`, so I created a test called `ip_name` and set up a very simple case. Maybe a better way is to generate all the legal and illegal strings and feed them into these functions.

net: add uv_ip_name to get name from sockaddr

---

src/threadpool.c
src/unix/os390-syscalls.c
src/unix/os390-syscalls.h
src/uv-common.c

This PR resolves the z/OS test failures in #3349
The `uv__threadpool_cleanup()` function cannot be called from inside `uv_library_shutdown()` on z/OS. Instead, the destructor attribute must be used; otherwise, tests will fail with exit code 1 and no output as seen in #3349. Additionally, `post()` does not need to be called when the destructor attribute is used.
Also adds `uv__os390_cleanup()` function to clean System V message queue on z/OS.
We are planning to revisit these changes once the Woz compiler becomes available to see if these changes are still necessary at that time, or if improvements can be made.

zos: use destructor for uv__threadpool_cleanup()

---

src/unix/dl.c

Similar to the dlopen codepath.
Older FreeBSD sometimes concurrently sets or clears this variable from other threads inside the libc they use. There was thus no way to ever use dlerror safely there. Julia does not use these libuv wrapper calls, so I forgot about it here, but we reported upstream, and looks like it is fixed now (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=95339), so this PR is only about supporting old FreeBSD versions better.
Refs: https://github.com/JuliaLang/julia/pull/40392
Refs: https://github.com/JuliaLang/julia/issues/39582

dlerror,freebsd: call dlerror only if necessary

---

src/unix/stream.c

It's been reported in the past that OS X 10.10, because of a race
condition in the XNU kernel, sometimes returns a transient EPROTOTYPE
error when trying to write to a socket. Libuv handles that by retrying
the operation until it succeeds or fails with a different error.
Recently it's been reported that current versions of the operating
system formerly known as OS X fail permanently with EPROTOTYPE under
certain conditions, resulting in an infinite loop.
Because Apple isn't exactly forthcoming with bug fixes or even details,
I'm opting to simply remove the workaround and have the error bubble up.
Refs: https://github.com/libuv/libuv/pull/482

darwin: remove EPROTOTYPE error workaround

---

include/uv/win.h
src/win/thread.c

Closes #3382 
The primary motivation is to try and improve runtime performance.  The OS primitive should be _very_ efficient for the intended use case and will be modestly smaller than the existing implementation.  This change also allows a dozen or so lines of code to be deleted in favor of just using the OS SRWLock implementation.
Trim down the `uv_rwlock_t` struct to just the `SRWLock` field.  There are comments about removing things in v2.x so I am unsure whether this is a breaking change, or not.  I can modify it to be non-breaking if that is necessary.
Update the various `uv_rwlock_` methods to call the Windows SRWLock API.  This is mostly deleting a bunch of code and replacing it with one-liners.
I ran the existing test collateral (compiled as Debug for more asserts) and they …

The Windows SRWLock primitive can be used for rw locking instead of a custom CRITICAL_SECTION+Semaphore implementation #3382

---

src/unix/core.c

Currently it's checking pointers to the uv_buf_t fields match the size
of the iovec fields. This is true on traditional architectures where
pointers are just machine word-sized integers, but not on CHERI, and
thus Arm's Morello prototype, where pointers contain additional metadata
(including bounds and permissions). Drop the & to fix this.

unix: Fix STATIC_ASSERT to check what it means to check

---

src/unix/thread.c
test/test-thread.c

uv_thread_create_ex() lets you set a stack size that is smaller than is
safe. It enforces a lower bound of PTHREAD_STACK_MIN (when that constant
is defined) but with musl libc that's still too small to receive signals
on.
Put the lower bound at 8192 or PTHREAD_STACK_MIN, whichever is greater.
The same restriction was already in place for the _default_ stack size.
<hr>
Coincidentally fixes a couple of -Wsign-compare warnings. Diff is probably easiest to review side-by-side.

unix: don't allow too small thread stack size

---

src/unix/bsd-proctitle.c

The process title mutex was destroyed on library unload without ensuring
it was initialized - and it may not be because it's initialized lazily.
On most platforms it worked by accident because an "all zeroes" mutex is
synonymous with an initialized and unlocked mutex, but not on NetBSD.
Refs: https://github.com/libuv/libuv/pull/3286#issuecomment-1014058782

bsd: ensure mutex is initialized

---

test/test-fs.c

Disable `atime` testing for symlink as this test
is dependant on a race condition on some OSes
(Linux is one) given that `lstat` updates the `atime`
As both `mtime` and `atime` are set by the same
syscall, barring an eventual kernel bug, this
test does not omit any error case

test: fix flaky uv_fs_lutime test

---

Makefile.am
m4/libuv-check-flags.m4

The CFLAGS variable is reserved and should never be set:
https://www.gnu.org/software/automake/manual/html_node/User-Variables.html
I had run into some issues with this, where the compiler did not like that this configuration meant we were attempting to list all CFLAGS variables twice on the command line.
I also simultaneously dropped support for automake < 1.14, released in 2013.

build: rename CFLAGS to AM_CFLAGS

---

src/unix/internal.h
src/unix/kqueue.c
src/unix/process.c

The kernel may return ESRCH if the child has already exited here.
This is rather annoying, and means we must indirectly handle
notification to our event loop of the process exit.
Refs: https://github.com/libuv/libuv/pull/3441
Refs: https://github.com/libuv/libuv/pull/3257

process,bsd: handle kevent NOTE_EXIT failure

---

test/run-tests.c
test/test-ipc.c
test/test-list.h

The test is very flaky, both on the CI and on people's local machines.
I spent some time trying to fix it but its design is fairly questionable
and it fails to test what it should more often than not because on fast
machines no queueing of data takes place.
Fixes #2307.

test: remove flaky test ipc_closed_handle

---

SUPPORTED_PLATFORMS.md

We can't realistically claim to support 10.7 or any version that Apple
no longer supports so let's bump the baseline to something more
realistic.
Refs: https://github.com/libuv/libuv/pull/482
Refs: https://github.com/libuv/libuv/pull/3405

darwin: bump minimum supported version to 10.15

---

docs/src/misc.rst
src/win/util.c

Some systems return fractional seconds, some return full seconds.
On windows uptime was artificially rounded down.
As discussed in #3447.

win: uv_uptime return fractional seconds on win

---

src/unix/core.c
src/win/core.c
test/test-loop-time.c

Pending work may be either (on any platform) pending_queue callbacks or
(on unix) watcher_queue handles to add to the io poll object.
Previously, we might have gotten somewhat stuck if the user caused an
event to be added to one of these in the idle or prepare callbacks, or
was embedding libuv.
Refs: https://github.com/libuv/libuv/pull/3234
Refs: https://github.com/libuv/libuv/issues/3101
Refs: https://github.com/libuv/libuv/pull/3308

loop: add pending work to loop-alive check

---

src/win/winapi.c

Currently `LoadLibraryA` call first attempts to load the given DLL from
the application working directory before loading it from the system DLL
path. [1] This may pose a security risk if an attacker is able to place a
malicious DLL into the application working directory as that DLL will
be loaded instead of the system DLL. This is especially dangerous if
the application is running with elevated privileges.
This changes the DLL loading to use `LoadLibraryExA` method with
`LOAD_LIBRARY_SEARCH_SYSTEM32` flag which restricts the DLL load
path to system DLL path, ignoring any DLLs in the application working
directory.
[1]: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications

win: restrict system DLL load paths

---

src/win/error.c

If we try to use `uv_fs_rmdir` on a read-only directory on Windows, it
internally calls `_wrmdir`, which sets `_doserrno` to `ERROR_ACCESS_DENIED`
and `errno` to `EACCES`. However, `ERROR_ACCESS_DENIED` is mapped to `UV_EPERM`,
so I believe it should be remapped to `UV_EACCES`.

win,errors: remap `ERROR_ACCESS_DENIED` to `UV_EACCES`

---

test/benchmark-list.h
test/benchmark-ping-udp.c

- Fixes the declaration of the benchmark in `benchmark-list.h` (it was not previously runnable at all)
- Fixes the benchmark itself hanging infinitely because the data was being dropped via ICMP Destination Unreachable errors (meaning `nread` was always zero in `pinger_read_cb`)
+ The data getting lost was fixed by binding the udp socket
- Properly checks for `UV_UDP_MMSG_CHUNK`, just as an example of what should generally be done (buf_free is actually a no-op as the buf is allocated on the stack)
---
Notes:
- Tangentially related to https://github.com/libuv/libuv/issues/2807 since this benchmark was introduced in https://github.com/libuv/libuv/pull/2532
- It's unclear to me exactly what this is meant to be benchmarking or how it differs from `benchmark-udp-pummel.c`.
- Feel free to treat …

test: fix benchmark-ping-udp

---

src/unix/core.c

I created `uv__backend_timeout` to be used internally for this reason,
then forgot to use it, resulting in flaky tests and excessive trips
around the uv_run loop.
Fix #3472

fix oopsie from #3466

---

SUPPORTED_PLATFORMS.md

Google goes to great lengths to obscure the relationship between the two
so explicitly call out the API version matching Android 7.0.

doc: clarify android api level

---

src/fs-poll.c
src/unix/internal.h
src/unix/pipe.c
src/unix/stream.c
src/unix/tcp.c
src/win/async.c
src/win/core.c
src/win/fs-event.c
src/win/fs.c
src/win/handle-inl.h
src/win/handle.c
src/win/internal.h
src/win/loop-watcher.c
src/win/pipe.c
src/win/poll.c
src/win/process.c
src/win/req-inl.h
src/win/signal.c
src/win/stream-inl.h
src/win/stream.c
src/win/tcp.c
src/win/tty.c
src/win/udp.c
src/win/winapi.c
src/win/winsock.c

Internal functions usually have a uv__ prefix. While `unix/*` was very consistent about this, `win/*` was inconsistent.

win: fix style nits [NFC]

---

test/test-udp-mmsg.c

Take into account that the data may not be already available in the
socket causing the `recvmsg()` / `recvmmsg()` calls to return `EAGAIN`
or `EWOULDBLOCK`.
Fixes: https://github.com/libuv/libuv/issues/3479

test: fix flaky udp_mmsg test

---

test/test-ipc-send-recv.c

The read callback failed to handle the `nread == 0` case, which is rare
to non-existent on the systems we test on but apparently happens often
enough on Solaris on SPARC to draw attention.
Fixes #3469.

test: fix ipc_send_recv_pipe flakiness

---

include/uv.h
test/test-get-passwd.c

Added in https://github.com/libuv/libuv/pull/742, these values are
typically defined as unsigned (since Linux 2.4). Only -1 is special,
representing an invalid id (e.g. see setreuid).

core: change uv_get_password uid/gid to unsigned

---

docs/src/misc.rst
include/uv.h
src/unix/core.c
src/win/util.c
test/test-platform-output.c

Replacement for the usage pattern where people use uv_cpu_info() as an
imperfect heuristic for determining the amount of parallelism that is
available to their programs.
Fixes #3493.
<hr>
You can test the linux behavior with:
```
$ taskset 3 ./build/uv_run_tests_a platform_output platform_output | grep uv_available_parallelism
uv_available_parallelism: 2
$ taskset 0xffffffff ./build/uv_run_tests_a platform_output platform_output | grep uv_available_parallelism
uv_available_parallelism: 12
```

unix,win: add uv_available_parallelism()

---

src/unix/process.c

From user reports, it appears that OpenBSD has a broken kevent NOTE_EXIT
implementation. However, we can simply go back to the old, slower
version therefore.
Fix: https://github.com/libuv/libuv/issues/3504 @jamessan

process: remove OpenBSD from kevent list

---

src/unix/core.c

Introduced earlier today in commit f250c6c7. _SC_NPROCESSORS_ONLN does
not seem to be defined on that platform.
cc @vtjnash @libuv/zos

zos: fix build breakage

---

src/unix/process.c

We can save a syscall on most modern systems (required by POSIX 2008),
but not on all systems.
Should resolved the complaints in https://github.com/libuv/libuv/pull/3257#issuecomment-1058829834
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2232/

process: only use F_DUPFD_CLOEXEC if it is defined

---

src/unix/core.c

FD_CLOEXEC is the only defined flag for fcntl(F_SETFD) so don't bother
getting the status of that flag first with fcntl(F_GETFD), just set it.
cc @vtjnash - as mentioned in #3490

unix: simplify uv__cloexec_fcntl()

---

MAINTAINERS.md

I bought a new Yubikey 5Ci so that I would have a backup key. Note that I signed the new key blob with my old key, to demonstrate authenticity and the new commit here with my new key to demonstrate ownership.

doc: add secondary GPG ID for vtjnash

---

src/unix/core.c
src/unix/internal.h
src/unix/process.c

Now that uv__cloexec_fcntl() is simplified (https://github.com/libuv/libuv/pull/3492), there is no benefit to maintaining duplicate code paths for the same thing.

unix: remove uv__cloexec_ioctl()

---

src/unix/kqueue.c
src/unix/process.c
src/uv-common.h

Bug https://github.com/libuv/libuv/issues/3504 seems to affect more platforms than just OpenBSD. As this
seems to be a race condition in these kernels, we do not want to fail
because of it. Instead, we remove the WNOHANG flag from waitpid, and
track exactly which processes have exited. Should also be a speed
improvement for excessively large numbers of live children.
CI: https://ci.nodejs.org/job/libuv-test-commit-freebsd/2122/
CI: https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/415/

process: fix hang after NOTE_EXIT

---

CMakeLists.txt
Makefile.am
src/unix/internal.h
src/unix/pipe.c
src/unix/stream.c
src/unix/tty.c
test/test-list.h
test/test-tcp-rst.c

Workaround for getsockname() not working for a TCP handle that has received RST from the remote.
Issue: https://github.com/libuv/libuv/issues/3481

Aix, ibmi: Handle server hang when remote sends TCP RST

---

.github/workflows/CI.yml

Github Actions will already hide the output, so we don't need to also suppress the output. That can sometimes hide problems that might have only been visible on inspection.

build: make CI a bit noisier

---

src/unix/process.c

Fix a regression that sneaked into posix spawn changes.
Refs: https://github.com/libuv/libuv/pull/3257

process: reset the signal mask if the fork fails

---

src/unix/atomic-ops.h

We found a runtime bug on z/OS with the atomic operations that was related to the codegen from builtin `__plo_CSST`. So this PR changes `cmpxchgi()` to use use hand-rolled assembly instead of `__plo_CSST` to resolve this bug.

zos: implement cmpxchgi() using assembly

---

m4/libuv-check-flags.m4

Using autoconf 2.71 and automake 1.16.5 the CFLAGS from
CC_CHECK_CFLAGS_APPEND does not get set in the Makefile without AC_SUBST
causing compilation to fail on Solaris due to missing -std=gnu89

build: AC_SUBST for AM_CFLAGS

---

MAINTAINERS.md

I removed people that haven't been active in over a year. Imran's GPG key has never been used to sign a release so should be okay to remove.

doc: update active maintainers list

---

.github/workflows/CI.yml

Refs: https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/
Signed-off-by: Darshan Sen <darshan.sen@postman.com>
cc @vtjnash

build: remove Windows 2016 workflows

---

src/win/error.c

Although the change remapped the error code to the correct one, a lot of
code already depends on the incorrect one, so it's not worth the
breakage.
This reverts commit 04a35efe69001a27e177aebde6c8db6f4cca7e4b.
Refs: https://github.com/nodejs/node/pull/42340
cc @vtjnash

Revert "win,errors: remap ERROR_ACCESS_DENIED to UV_EACCES (#3193)"

---

.github/workflows/CI-unix.yml
.github/workflows/CI-win.yml
.github/workflows/sanitizer.yml

1. filter CI by path, so we only run unix/win if those files even changed
~~2. update RTD to the latest versions and syntax~~
~~3. add CI for docs, so we will observe any build failures early (currently only subtly visible in https://readthedocs.org/projects/libuv/ for v1.x commits)~~

CI: filter by paths and branches

---

.github/workflows/CI-unix.yml

Smokescreen for build errors on iOS, currently ignoring failures due to
aforementioned build errors.
(Preparation for https://github.com/libuv/libuv/pull/3563 @dennycd)

build: add iOS to macos CI

---

.github/workflows/CI-unix.yml
src/unix/process.c

Removing TARGET_OS_IPHONE macro to include posix spawn headers for iOS build. Previously #3257 introduced posix spawn with \_\_APPLE\_\_ platform only, which resulted in a number of spawn related definitions not found for ios (e.g. [uv__posix_spawn_fncs_tag](https://github.com/libuv/libuv/blob/739e441d4d4135e411e94a6e4c190a7fa32ac400/src/unix/process.c#L390)).  
----
cc @drfloob  @HannahShiSFB

process: removes TARGET_OS_IPHONE for process.c ios build break

---

test/test-tcp-rst.c

PR that added the test: https://github.com/libuv/libuv/pull/3482

test: Remove unnecessary declarations in tcp_rst test

---

src/win/udp.c

Warnings are treated as errors on our CI build, so we got some build errors.
Introduced by #3350
```
libuv\src\win\udp.c(1090,40): warning C4133: 'function': incompatible types - from 'sockaddr_storage *' to 'const sockaddr *'
```

win: fix incompatible types warning

---

src/unix/core.c
src/win/core.c
src/win/req-inl.h
test/test-idle.c
test/test-list.h

Wrong accounting of idle handles in uv_run() made it sleep when there
was nothing left to do. Do a non-blocking poll for I/O instead.

unix,win: fix UV_RUN_ONCE + uv_idle_stop loop hang

---

test/test-getsockname.c
test/test-timer.c

This PR includes:
1. separate the static variables by test cases, 
2. add callback for test case timer_start_twice
The static variables were used by multi test cases, it was OK since other languages use fork and count separately. But in iOS test, we have to run all tests in the same process, so we need separate variables to count separately.
https://github.com/grpc/grpc/pull/28570

separate the static variables by test cases

---

SUPPORTED_PLATFORMS.md

Commit 3af55129 from 2017 distinguished between smartos and other sunos
spawn but [0] makes it clear ("a new chapter" - barf) that smartos is
dead.
Stop mentioning smartos and put everything under the sunos umbrella.
[0] https://www.joyent.com/blog/a-new-chapter-begins-for-triton-and-smartos

doc: remove smartos from supported platforms

---

autogen.sh
m4/libuv-check-versions.m4

There was a risk of introducing a regression during the release process itself, as the autogen script might copy older versions of files when making the autotools source. To mitigate that risk, we record here the versions of the tools used, and require that each release must use the same or newer versions of these files. The most common reason for updates is the `config.guess` script.
Use libtoolize --force to ensure it updates m4 directory with the
latest files. Add an option "release" to the autogen.sh script that
checks the versions of the input tools, so that we know they are always
using the latest version for each release.

release: check versions of autogen scripts are newer

---

src/unix/fs.c

OpenBSD doesn't have lutimes so utimensat should be used instead

openbsd: use utimensat instead of lutimes

---

docs/src/guide/utilities.rst

docs: fix the bad line reference to the code `uvwget/main.c`

docs: fix the bad line reference to the code

---

include/uv/win.h
src/win/pipe.c

_From https://github.com/libuv/libuv/pull/3598#issuecomment-1111513567_
>> [test.parallel/test-http-client-abort-unix-socket](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/14497/RUN_SUBSET=1,nodes=win2012r2-COMPILED_BY-vs2019-x86/testReport/(root)/test/parallel_test_http_client_abort_unix_socket/) timeout
>
> this seems somewhat concerning and needs to be investigated
Investigation revealed this to be a somewhat uncommon resource leak. There is a relatively direct fix for that of just adding this to the happy path of `uv__process_pipe_connect_req`:
```
if (handle->flags & UV_HANDLE_CLOSING)
close_pipe(handle);
```
But that might risk hanging for a long time in the background thread waiting for the 30 second (recurring) timeout. Thus I have reordered the logic to check and …

win: Fix pipe resource leak if closed during connect (and other bugs)

---

src/unix/core.c
src/win/core.c
test/test-pipe-set-non-blocking.c
test/test-spawn.c

Previously, Windows would always defer event processing to the loop
after they were received. This could cause confusion for users who were
using prepare and idle callbacks, as seen from this bug in nodejs[^1] and
this discussion in libuv[^2], and even some discrepancies in the libuv
tests too[^3].
[^1]: https://github.com/nodejs/node/pull/42340
[^2]: https://github.com/libuv/libuv/discussions/3550
[^3]: See change to test-spawn.c in this PR
So rather than declare those usages to be wrong, we change libuv to meet
those users expectations.
Replaces: https://github.com/libuv/libuv/pull/3585

loop: better align order-of-events behavior between platforms

---

test/test-embed.c

`uv_backend_fd` is not supported on Aix & IBM i according to docs: http://docs.libuv.org/en/v1.x/loop.html. Avoid using it in embed test and call `uv_run` directly.
Issue: https://github.com/libuv/libuv/issues/3614

Aix & IBM i: Fix embed test

---

src/unix/kqueue.c

On NetBSD with libuv 1.44.1 we see that cmake occasionally hangs waiting for a child process to exit, with libuv waiting forever for kevent() to deliver more events that never come.  The child process has already exited and is waiting to be collected with waitpid().  The symptoms are similar to libuv#3521 but this is a different problem.
This time, the hang occurs when the batch of events returned by one call to kevent() contains both a EVFILT_READ event for an fd and a later EVFILT_PROC record for the PID with the same value as the earlier fd.  What happens is that  uv__platform_invalidate_fd() is called to invalidate events later in the same batch for the fd, but uv__platform_invalidate_fd() invalidates the later EVFILT_PROC event too because it sees the same "ident" value and does not …

kqueue: skip EVFILT_PROC events when invalidating events for an fd.

---

src/unix/atomic-ops.h

This fixes `libuv` build for `ppc64` on Darwin (as well as `+universal` with `ppc+ppc64`).
Definition used for `cpu_relax` borrowed from `libitm`: https://github.com/gcc-mirror/gcc/blob/master/libitm/config/powerpc/target.h
Where, FWIU, it was introduced by @iains
This closes my own ticket: https://github.com/libuv/libuv/issues/3623#issuecomment-1125921373

libuv: fix atomic-ops.h for Darwin, fixes ppc64 build

---

src/unix/process.c

On z/OS, EPERM is returned if the process being killed is a zombie. However, this shouldn't be treated as an error in `uv_kill()` since it's already terminated, so return 0 instead.

zos: don't error when killing a zombie process

---

src/unix/core.c
src/unix/os390.c

This resolves https://github.com/libuv/libuv/issues/3601.
The reason for the failure is because once a change notification is generated for a file, the notification cannot be cancelled by `uv_fs_event_stop()`. This means that change notifications received in `os390_message_queue_handler()` may refer to a `uv_fs_event_t` handle that have already been closed. In that case, their callback should be prevented from being called. So explicitly check if the handle is closed before calling the callback function.

zos: avoid callbacks on closed fs event handles

---

src/unix/core.c

This PR implements `uv_available_parallelism()` for z/OS by leveraging the [`__get_num_online_cpus()`](https://ibmruntimes.github.io/zoslib/zos-sys-info_8cc.html#a3b2ad7fe0aee30edf781eefd73ee5b88) function provided by ZOSLIB to report the number of CPUs that the operating system considers to be online.
`__get_num_online_cpus()` gets this information from the cpu management control table.

zos: implement uv_available_parallelism()

---

src/win/udp.c

Previously it would pass a pointer to uninitialized memory to WSASendTo,
which triggered a compiler warning. However, `addrlen` will be 0, so it
seems unlikely to trigger an error or uninitialized memory access.
Refs: https://github.com/libuv/leps/pull/10
Refs: https://github.com/libuv/libuv/pull/1872
Refs: https://github.com/libuv/libuv/pull/2217

udp,win: fix UDP compiler warning

---

src/unix/os390-syscalls.c
src/unix/os390.c

This PR fixes a bug in z/OS implementation of `epoll_wait()` where it's possible for `reventcount` to become greater than `pollret`. This indicates an early exit of the loop, resulting in some file events not being correctly captured.
The reason this happens is because the previous implementation incremented `reventcount` by 2 when both `POLLIN` and `POLLOUT` revents were set for a fd. However, `reventcount` should still only be incremented by 1 in this case, because `_NFDS` counts as 1 even for fds with multiple revents set. 
Additionally, this PR makes a few minor improvements to remove redundant checks for epoll:
- `lst->size` should never be 0 or negative, so we can remove the check and the `_SET_FDS_MSGS(size, 0, 0)` branch entirely.
- Message queue is always the last entry of …

zos: fix early exit of epoll_wait()

---

src/unix/tcp.c

The errno value is only meaningful if bind() fails and returns -1.
Some bind() implementations may return success but modify errno value
internally, like the socket_wrapper library used by the Samba testsuite.
Signed-off-by: Samuel Cabrero <scabrero@suse.de>

unix,tcp: fix errno handling in uv__tcp_bind()

---

src/unix/stream.c

The UV_ECANCELED codepath had an incorrect comment, and the
implementation was generally less robust (for example, not checking if
`cb` was NULL), so we can merge these codepaths for cleaner code.

shutdown,unix: reduce code duplication

---

src/unix/stream.c
src/unix/tty.c
src/unix/udp.c

Causes compilation errors for people that build libuv with a C89
compiler.
Refs: https://github.com/libuv/libuv/discussions/3666

unix: fix c99 comments

---

src/unix/os390.c

In https://github.com/libuv/libuv/pull/611, changes were made to AIX and other unix systems to defer the signal watcher that is used for process management until after the dispatch of regular i/o watchers.
This PR ports those changes to z/OS as well so that behavior of `uv__io_poll()` on z/OS is more consistent with that of the other unix platforms.

zos: delay signal handling until after normal i/o

---

src/unix/stream.c

Regression caused by 1a91b51976a1adc6972081faa78b6b70022254d3 mistake.
Refs: https://github.com/libuv/libuv/pull/3648
Fixes: https://github.com/libuv/libuv/pull/3648/3671

stream: uv__drain() always needs to stop POLLOUT

---

src/win/internal.h
src/win/pipe.c
src/win/req-inl.h
src/win/stream.c
src/win/tcp.c
src/win/tty.c

Split this off from endgame, so that it can be handled separately and
earlier, rather than trying to detect inside endgame which case we are
in. There appear to be some race conditions on the `handle` field still
however, which this does not yet attempt to address.

win,shutdown: improve how shutdown is dispatched

---

CMakeLists.txt

cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../TC-clang-msvc-cl.cmake -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"
cat CMakeFiles/uv_a.dir/flags.make
will get C_FLAGS = ... /O2 /Ob2 /DNDEBUG -MT ...
and
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../TC-clang-msvc-cl.cmake -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL"
cat CMakeFiles/uv_a.dir/flags.make
will get C_FLAGS = ... /O2 /Ob2 /DNDEBUG -MD ...

Enable MSVC_RUNTIME_LIBRARY setting

---

src/win/fs.c

The `bufs` variable is a `uv_buf_t *`, so this check does not make sense. It also got added in unrelated work https://github.com/libuv/libuv/pull/590, so I am not sure of what the intent of this change was. It was discussed briefly there at https://github.com/libuv/libuv/pull/590#issuecomment-385607866.
Refs: https://github.com/libuv/libuv/pull/1070
CI: https://ci.nodejs.org/job/libuv-test-commit-windows-cmake/438/

[v2] fs: remove incorrect ARRAY_SIZE call

---

src/unix/core.c
src/unix/kqueue.c
src/unix/stream.c
src/unix/tcp.c

After analysis of many real-world programs I've come to conclude that
accepting in a loop is nearly always suboptimal.
1. 99.9% of the time the second accept() call fails with EAGAIN, meaning
there are no additional connections to accept. Not super expensive
in isolation but it adds up.
2. When there are more connections to accept but the listen socket is
shared between multiple processes (ex. the Node.js cluster module),
libuv's greedy behavior necessitated the UV_TCP_SINGLE_ACCEPT hack
to slow it down in order to give other processes a chance.
Accepting a single connection and relying on level-triggered polling to
get notified on the next incoming connection both simplifies the code
and optimizes for the common case.
<hr>
I'm curious if the above lines up with other people's …

unix: don't accept() connections in a loop

---

src/win/util.c

uv_exepath() wrote the nul byte *after* the end of the buffer.
Fixes: https://github.com/libuv/libuv/issues/3691

win: fix off-by-1 buffer overrun in uv_exepath()

---

.github/workflows/CI-unix.yml

The former will be removed by GitHub in August.
Fixes: https://github.com/libuv/libuv/issues/3697

build: switch ci from macos-10.15 to macos-11

---

src/unix/stream.c
src/unix/tcp.c
src/uv-common.h
src/win/pipe.c
src/win/stream.c
src/win/tcp.c
src/win/tty.c

Replace it with a `uv__is_stream_shutting()` macro that checks the
`shutdown_req` field.
It partially fixes: https://github.com/libuv/libuv/issues/3663.

unix,win: remove UV_HANDLE_SHUTTING flag

---

src/win/util.c

This pull request adds Windows 11 support so it can be reported as Windows 11 on `uv_os_uname`.
Although I think this is a workaround, it seems to be as reliable as it gets without dropping the registry key value as the source.
Refs: https://docs.microsoft.com/en-us/answers/questions/586619/windows-11-build-ver-is-still-10022000194.html
"This is correct. Anything above 10.0.22000.0 is Win 11. Anything below is Win 10."
Fixes: https://github.com/libuv/libuv/issues/3381
Node Issue ref: https://github.com/nodejs/node/issues/40862
Suggestions are welcome if this is not the desired solution!

win: support Windows 11 on uv_os_uname()

---

docs/src/misc.rst
src/unix/core.c

Most platforms report it in kilobytes but macOS and Solaris report it in
bytes and pages respectively.
Fixes: https://github.com/nodejs/node/issues/44332
<hr>
Windows, Linux and (Free|Net|Open)BSD all report kilobytes.

unix: fix uv_getrusage() ru_maxrss reporting

---

test/test-dlerror.c

Dynamic loading with musl only works with libc.so because it is
is implemented in musl's dynamic linker, not in libc proper.
libc.a contains just a stub dlopen() that always fails with a "Dynamic
loading not supported" error message. Update the test to handle that.
Fix: https://github.com/libuv/libuv/issues/3706

test: fix musl libc.a dlerror() test expectation

---

.github/workflows/CI-unix.yml

I recently changed it to download a fixed .deb but seems it's updated more frequently than I anticipated because the dfsg-7ubuntu1_package is already gone, replaced with dfsg-7ubuntu2.
Bring back the downloader logic that fetches the filename from the directory listing.

build: restore qemu download logic

---

src/unix/tty.c

Compare-and-exchange is only useful in a loop. Replace it with a simple exchange.

unix: simplify atomic op in uv_tty_reset_mode()

---

CMakeLists.txt

Continuation of https://github.com/libuv/libuv/pull/3698
This makes `LIBUV_BUILD_TESTS` dependent on `LIBUV_BUILD_SHARED`, so tests will be skipped when not building the shared library.
Addresses the comment by @gengjiawen

build: add CMake option LIBUV_BUILD_SHARED to enable/disable shared library

---

src/unix/fs.c
src/unix/linux-syscalls.c
src/unix/linux-syscalls.h

preadv, pwritev, dup3 and utimensat all exist in 2.6.32 kernels, libuv's minimum supported kernel.
The wrapper for utimensat was already gone, only the define remained.

linux: remove unused or obsolete syscall wrappers

---

docs/src/threadpool.rst
src/threadpool.c

Give the threads in the thread pool a stack size that is consistent across platforms and architectures.
Fixes: https://github.com/libuv/libuv/issues/3786

unix,win: give thread pool threads an 8 MB stack

---

include/uv/win.h
src/win/core.c
src/win/tcp.c
src/win/udp.c

It has been disabled for 11 years, I guess it should remain that way.

win,tcp,udp: remove "active streams" optimization

---

src/inet.c

```
libuv/src/inet.c:133:11: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
```

unix,win: fix 'sprintf' is deprecated warning

---

docs/src/handle.rst

Feels like every time I work with libuv I have to check the sources for whether or not this is the case. Figured maybe it could benefit others to have this pointed out in the docs.

docs: mention close_cb can be NULL

---

CMakeLists.txt
Makefile.am
src/win/udp.c
test/test-list.h
test/test-udp-recv-in-a-row.c

Do at most 32 nonblocking udp receive in a row.
Same as https://github.com/libuv/libuv/pull/3724, but target on v1.x branch.

win: optimize udp receive performance

---

src/unix/darwin-stub.h
src/unix/darwin.c

This reverts commit https://github.com/libuv/libuv/commit/87f076515937345fda1a1dbc598f34e65e1b81c7.
This has been reported to be unnecessary, and also returns the wrong answer (off by exactly 100x), so it is not particularly useful. It is simpler to hard-code the answer (2.4 GHz) until Apple fixes their kernel (if they ever choose to). This choice of value should be pretty good (i.e. past and future-proof) anyways.
This also reverts the bugfixes to the original PR:
Revert "darwin: fix iOS compilation and functionality"
This reverts commit https://github.com/libuv/libuv/commit/1addf9b88a17bc32d009d377a14d540ccddd06db.
Revert "macos: fix the cfdata length in uv__get_cpu_speed (https://github.com/libuv/libuv/pull/3356)"
This reverts commit …

darwin: use hw.cpufrequency again for frequency info

---

src/unix/darwin.c
src/unix/freebsd.c
src/unix/netbsd.c
src/unix/openbsd.c
src/win/util.c

fix the return value of uv_get_free_memory and uv_get_total_memory.
cc @bnoordhuis

uinx,win: fix the return value of uv_get_free_memory and uv_get_total_memory

---

docs/src/metrics.rst
include/uv.h
src/unix/aix.c
src/unix/core.c
src/unix/kqueue.c
src/unix/linux.c
src/unix/loop.c
src/unix/os390.c
src/unix/posix-poll.c
src/unix/sunos.c
src/uv-common.c
src/uv-common.h
src/win/core.c
test/test-list.h
test/test-metrics.c

src: add new metrics APIs
The following metrics are now always recorded and available via the new
uv_metrics_info() API.
* loop_count: Number of event loop iterations.
* events: Total number of events processed by the event handler.
* events_waiting: Total number of events waiting in the event queue when
the event provider request was made.
Benchmarking has shown no noticeable impact recording these metrics.
This is a patch we are currently using internally at NodeSource. We have been testing more reliable ways to measure the health of the event loop and have found that tracking the number of events processed, and more importantly, the number of events waiting in the event queue to be processed before the event provider is called is a better measure of event loop health.
Allowing a …

src: add new metrics APIs

---

CMakeLists.txt
configure.ac

Without this change, building for Solaris 10 fails since the SUNOS_NO_IFADDRS macro doesn't get set automatically, and ifaddrs.h was only introduced starting with Solaris 11.

unix: disable usage of ifaddrs.h on Solaris 10 from within configure.ac

---

docs/src/misc.rst
include/uv.h
src/unix/aix.c
src/unix/cygwin.c
src/unix/darwin.c
src/unix/freebsd.c
src/unix/haiku.c
src/unix/hurd.c
src/unix/ibmi.c
src/unix/linux.c
src/unix/netbsd.c
src/unix/openbsd.c
src/unix/os390.c
src/unix/qnx.c
src/unix/sunos.c
src/win/util.c
test/test-get-memory.c

This PR mimicks https://github.com/libuv/libuv/pull/3744, accessing `memory.usage_in_bytes`/`memory.current` (cgroupv1/cgroupv2) and using it to implement a constraint-aware version of `uv_get_free_memory`.
Implements https://github.com/libuv/libuv/pull/3744#issuecomment-1249464780

API for querying available memory + cgroup1 fixes

---

SUPPORTED_PLATFORMS.md
src/unix/freebsd.c
src/unix/internal.h
src/unix/linux.c
src/unix/udp.c

The old Linux baseline was essentially RHEL 6 but that distro has been out of support for two years now. Move to RHEL 7.
This commit also moves FreeBSD to tier 2 because it isn't actually part of libuv's CI matrix, only Node's.
Fixes: https://github.com/libuv/libuv/issues/3822

doc: bump min supported linux and freebsd versions

---

CMakeLists.txt
Makefile.am
configure.ac
include/uv/errno.h
include/uv/unix.h
src/unix/core.c
src/unix/fs.c
src/unix/internal.h
src/unix/process.c
src/unix/tty.c
src/unix/udp.c
test/test-fs-event.c
test/test-poll.c
test/test-tty.c
test/test-udp-ipv6.c
test/test-udp-multicast-interface6.c
test/test-udp-multicast-join6.c

Because kFreeBSD is dead. RIP.
Fixes: https://github.com/libuv/libuv/issues/3833

unix: drop kfreebsd support

---

test/test-fs-event.c

Increase the timer interval. That hopefully ameliorates the problem of FSEvents.framework missing events on the macOS CI buildbot.
Not really a fix, more a mitigation.
Fixes: https://github.com/libuv/libuv/issues/3862

test: try fixing flaky fs_event_watch_dir test

---

src/unix/fsevents.c

One hasn't been in use since 2017, the other since 2013.

darwin: remove unused fsevents symbol lookups

---

include/uv.h

reopen of #3730, which was accidentally closed

Predefine UV_EXTERN to  ignore export

---

test/test-platform-output.c

The test was disabled because of a qemu bug that is presumed to have since been fixed.
Refs: https://github.com/libuv/libuv/pull/3861

build: enable platform_output test on qemu

---

src/unix/linux.c
src/uv-common.c
src/uv-common.h

On Linux, CPUs can come online or go offline while uv_cpu_info() is busy gathering data. Change uv_cpu_info() in the following ways:
1. Learn online CPUs from /proc/stat
2. Get the model name from /proc/cpuinfo when it has a matching CPU, or default to "unknown"
3. Get speed from /sys/devices/system/cpu/cpu%u/cpufreq/scaling_cur_freq when it exists, or default to 0
Before this commit, libuv read the speed from /proc/cpuinfo but that reports the base frequency, not the actual frequency. My system has two cores running permanently at 3.6 GHz but libuv thought all 12 ran at 2.2 GHz.
Fixes: https://github.com/libuv/libuv/issues/2351
Fixes: https://github.com/libuv/libuv/issues/3858
<hr>
I regret that the diff is not very pretty; it looks better with `git diff --histogram` or side-by-side.

linux: handle cpu hotplugging in uv_cpu_info()

---

CMakeLists.txt

All cmake policies up to CMP0065 are set to NEW by default since the
minimum required version is 3.4.

build: remove unnecessary policy setting

---

src/win/core.c
src/win/process.c

In order to properly generate minidumps during actual events, it is necessary to disable the call to `SetErrorMode()` during libuv initialization and to remove the job flag
`JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION`, both of which interfered in the normal handling of exceptions.  Finally, it was determined prudent to include `CREATE_DEFAULT_ERROR_MODE` when spawning new processes, to ensure that whatever error handling mode was set in the current process is not inherited by subprocesses.

[Windows] Allow exceptions through to the OS

---

README.md

`libuv` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `libuv` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `libuv`, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/libuv/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)

[document] Add vcpkg instruction step

---

src/win/error.c
src/win/fs.c
test/test-fs.c

In Node.js, `fs.readlink()` on a non-symlink file used to throw an `UNKNOWN`
error on Windows. This change maps `ERROR_NOT_A_REPARSE_POINT` to
`UV_EINVAL`, so that now it throws `EINVAL` just like all the other
platforms.
cc @vtjnash

win: return `UV_EINVAL` from `uv_fs_readlink()` on a non-symlink file

---

include/uv.h
src/unix/core.c
src/unix/internal.h
src/uv-common.c
src/win/internal.h
src/win/util.c
test/test-get-passwd.c
test/test-list.h
test/test-platform-output.c

File system operations may return uid and gid values, which we may want
to pretty-print. We already have the code for getting information for
the current user, so just need to add a parameter to make it exposed for
every user. We expose information about groups in a similar manner also.
See here for example usage: https://github.com/JuliaLang/julia/pull/39463/files#diff-16ee8fceb01f720774f142d023997ead47e5bfdb1e7a07ee9e8670f43f4db5e5R352

misc: extend getpw to take uid as an argument

---

docs/src/misc.rst
include/uv.h
src/unix/aix.c
src/unix/bsd-ifaddrs.c
src/unix/linux-core.c
src/unix/sunos.c
src/win/util.c
test/test-platform-output.c

Not using the correct broadcast address in applications can cause
disasterous results. Rather than letting the programmer guess at
the broadcast address and try to derive it correctly, allow him to
query the system instead for the correctly configured state.
This addresses compliance per Host Requirements, "Broadcasts"
(RFC-1122, Section 3.3.6).

libuv: expose broadcast address on interfaces

---

src/uv-common.h

Fixes: https://github.com/libuv/libuv/issues/3131

unix,win: use static_assert when available

---

CMakeLists.txt
LICENSE-extra
Makefile.am
README.md

GitHub gets confused by the non-standard format of the LICENSE file. Move the extra bits into the creatively named LICENSE-extra file.
Fixes: https://github.com/libuv/libuv/issues/3875

doc: clean up license file

---

test/test-idna.c
test/test-ip6-addr.c

libuv/test/test-idna.c:107:3: note: in expansion of macro 'ASSERT_EQ'
libuv/test/task.h:119:26: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
libuv/test/test-ip6-addr.c:106:40: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]

test: Fixes warnings when compiling test suites

---

CMakeLists.txt

I believe this was an oversight when the `install(EXPORT` was added last year in https://github.com/libuv/libuv/pull/3293. @pemensik please correct me if I'm wrong about that.

Add libuv:: namespace to exported libuvConfig.cmake

---

.github/workflows/CI-unix.yml
configure.ac
test/test-fs-copyfile.c
test/test-pipe-connect-error.c

When run under distcheck, the libuv source permissions are read-only, which makes this test copyfile fail without explicit correction to the permissions.
The undefined behavior that was previously failing here was now defined and fixed (https://github.com/libuv/libuv/issues/2199#issuecomment-466134438), so it is time we now promoted this to a mandatory test!

build,test: fix distcheck errors

---

src/unix/core.c
src/unix/internal.h
src/unix/kqueue.c
src/unix/loop.c
src/unix/process.c
src/unix/signal.c

Since we are emulating this event, but are not using the pending_queue, we need to make sure it is accounted for properly. Also DRY some of the reset_timeout code here.
This was observed to cause a hang in certain rare cases, particularly on M1 machines.
Fixes: https://github.com/JuliaLang/julia/issues/45118

darwin,process: feed kevent the signal to reap children

---

src/unix/posix-hrtime.c

Per standard libuv operating procedures, abort on unexpected failure. Don't silently ignore the error and return garbage.

unix: abort on clock_gettime() error

---

src/unix/internal.h
src/unix/tcp.c
src/unix/udp.c

The conditional bind-to-port logic in tcp.c had an error path that closed the socket file descriptor while it was still owned by the uv_tcp_t handle.
Fix that by not closing the file descriptor and refactoring the code so it is hopefully harder to get wrong in the future.
The refactoring also makes the code a little flatter, removes duplicated code, and, arguably, is in a more idiomatic libuv style.
Fixes: https://github.com/libuv/libuv/issues/3461
Replaces: https://github.com/libuv/libuv/pull/3462
Co-authored-by: Jameson Nash <vtjnash@gmail.com>

unix: DRY and fix tcp bind error path

---

src/win/util.c

The call to uv__cwd() always returns a new allocation. The previously allocated utf16_buffer needs to be free'd before passing it in to receive the next allocation.

win: fix leak in uv_chdir

---

test/test-fs.c

Missing a call to MAKE_VALGRIND_HAPPY() to silence valgrind output.

test: make valgrind happy

---

CMakeLists.txt
Makefile.am
include/uv/win.h
src/thread-common.c
src/unix/thread.c
src/win/thread.c
test/test-barrier.c

This code would previously get confused between rounds of the barrier being called and a thread might incorrectly get stuck (deadlock) if the next round started before that thread had exited the current round.
Avoid that by not starting the next round in++ before out-- has reached zero indicating that all threads have left the prior round.
And fix it that on Windows by replacing the implementation with the one from unix. There are some awkward platform-specific redirection here with an extra malloc that is not needed on Win32, but that will be fixed in libuv v2.
Fixes: https://github.com/libuv/libuv/issue/3872

barrier: wait for out before in

---

src/unix/fs.c

Trying to copy a read-only file onto a ceph-fuse filesystem fails, returning an `EACCES` error. This happens when the destination doesn't exist yet, and a new file is created.
By checking that the error matches, and that the destination file is empty, we can fix this issue while waiting for a proper Ceph fix to be upstreamed.
Fixes: https://github.com/libuv/libuv/issues/3919
Refs: https://github.com/nodejs/node/issues/37284
Refs: https://github.com/libuv/libuv/issues/3117
Refs: https://github.com/libuv/libuv/issues/3322

fs: fix ceph copy error truncating readonly files

---

LINKS.md

Add the libuv wrapper nsuv to the list, along with other C++ apps that were found to use libuv extensively and have been maintained recently.

doc: add entries to LINKS.md

---

src/unix/linux.c

This was removed before in 2018 but then reinstated again in 2019 to fix building with old Android SDKs. Well, time marches on; this time it's gone for good.
Refs: https://github.com/libuv/libuv/pull/1372
Refs: https://github.com/libuv/libuv/pull/2358

linux: remove epoll_pwait() emulation code path

---

src/unix/internal.h
src/unix/linux.c

Replace the throw-type-safety-to-the-wind CAST() macro with an inline function that is hopefully harder to misuse. It should make the inotify code slightly more legible if nothing else.
<hr>
I flattened some code. Should be easier to read with ?w=1 (no whitespace changes)

linux: replace unsafe macro with inline function

---

src/unix/linux.c

The last major distro that supported the oabi calling convention was Debian 5 (Lenny) and that went out of support in February 2012. It seems like a fairly safe assumption that nothing speaks oabi anymore in this day and age.
Fixes: https://github.com/libuv/libuv/issues/3935

linux: remove arm oabi support

---

src/unix/core.c
src/unix/fs.c
src/unix/kqueue.c
src/unix/linux.c
src/uv-common.c
src/uv-common.h

Unfortunately MSVC only started supporting C11 atomics in VS2022 version
17.5 Preview 2 as experimental. So resort to using the Interlocked API
if possible. There is no Interlocked API for storing a value. The best
method I could find is to cast it as a `volatile` and store it directly.
Ref: https://devblogs.microsoft.com/cppblog/c11-atomics-in-visual-studio-2022-version-17-5-preview-2/
Fixes: https://github.com/libuv/libuv/issues/3948

Fix atomics to use C11 where possible

---

test/benchmark-async-pummel.c
test/benchmark-async.c
test/benchmark-fs-stat.c
test/benchmark-million-async.c
test/benchmark-queue-work.c
test/runner.c
test/task.h

Don't use a static buffer to hold human-readable "big" numbers.
The buffer isn't big enough for benchmarks like fs_stat that print a large number of them. Have the caller pass in a buffer instead.

test: don't use static buffer for formatting

---

docs/src/fs.rst
src/threadpool.c
src/unix/fs.c
src/unix/internal.h
src/unix/linux.c
src/uv-common.h
test/test-threadpool-cancel.c

Add io_uring support for several asynchronous file operations:
- read, write
- fsync, fdatasync
- stat, fstat, lstat
io_uring is used when the kernel is new enough, otherwise libuv simply
falls back to the thread pool.
Performance looks great; an 8x increase in throughput has been observed.
This work was sponsored by ISC, the Internet Systems Consortium.

linux: introduce io_uring support

---

src/unix/linux.c

Fix a valgrind warning that only manifested with clang (not gcc!) by explicitly passing 0L instead of plain 0 as the |sigsz| argument to io_uring_enter(). That is, pass a long instead of an int.
On x86_64, |sigsz| is passed on the stack (the other arguments are passed in registers) but where gcc emits a `push $0` that zeroes the entire stack slot, clang emits a `movl $0,(%rsp)` that leaves the upper 32 bits untouched.
It's academic though since we don't pass IORING_ENTER_EXT_ARG and the kernel therefore completely ignores the argument.
Refs: https://github.com/libuv/libuv/pull/3952

linux: fix academic valgrind warning

---

test/test-signal-multiple-loops.c

The signal_multiple_loops test is flaky when run under AddressSanitizer and MemorySanitizer. Sometimes thread creation fails, other times it simply times out.
Fixes: https://github.com/libuv/libuv/issues/3956

test: disable signal test under ASan and MSan

---

src/threadpool.c
src/unix/aix.c
src/unix/kqueue.c
src/unix/linux.c
src/unix/os390.c
src/unix/posix-poll.c
src/uv-common.h
src/win/core.c
test/task.h
test/test-list.h
test/test-metrics.c

```
The worker pool calls all callbacks locally within the queue. So the
value of nevents doesn't properly reflect that case. Increase the number
of events directly from the worker pool's callback to correct this.
In order to properly determine if the events_waiting counter needs to be
incremented, store the timeout value at the time the event provider was
called.
Remove have_iou_events because by incrementing nevents the same result
is achieved.
```
I don't love the solution of storing `timeout` on the loop's internal field `current_timeout`, but it is the best I could think of. Any thoughts on an alternative fix?
side note: Added a patch I've had locally for a while that adds `ASSERT_OK()` since needed to add a new test. Will be fine to remove it if there is an objection.

src: fix events/events_waiting metrics counter

---

docs/src/fs.rst
docs/src/misc.rst
include/uv.h
src/unix/core.c
src/win/util.c
test/test-hrtime.c
test/test-list.h

Fixes: https://github.com/libuv/libuv/issues/1674
<hr>
Works on my machine (which isn't a Windows machine. Let's see if it compiles.)

unix,win: add uv_clock_gettime()

---

src/win/tty.c

This fixes #3970. It moves the initialization of two things to the point before where a thread task is spawned.
The existing code has a race condition. Calling `QueueUserWorkItem` queues a work item on a thread pool.  It's possible for that work item to begin executing even before the `QueueUserWorkItem` function returns.
On heavily-loaded systems, especially VMs where scheduling can be unpredictable due to hypervisor interrupts, it is possible for the worker function that is queued by `QueueUserWorkItem` to query the console size and attempt to acquire `uv__tty_console_resize_mutex` before it is initialized.  That's undefined behavior, and in practice, it can cause a crash.  Separately, the worker code also asserts that the `uv_tty_console_width` (and height) variables have been …

Fix race condition in uv__init_console

---

src/unix/linux.c
src/uv-common.h

This work was sponsored by ISC, the Internet Systems Consortium.

linux: use io_uring to batch epoll_ctl calls

---

SUPPORTED_PLATFORMS.md

Only support the versions still maintained by Apple.
`fs_copyfile` already fails in `10.15`.

macos: update minimum supported version

---

CMakeLists.txt
configure.ac
include/uv/win.h
src/win/process.c

This commit adds the ability to dump core when sending the `SIGQUIT` signal on Windows.  The change reads in the current registry setting for local dumps, and attempts to write out to that location before killing the process.  See [collecting-user-mode-dumps] for registry and pathing details. This behavior mimics that of the dumps created by the typical Windows Error Reporting mechanism.
[collecting-user-mode-dumps]: https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

[Windows] Write out minidumps on reception of SIGQUIT

---

docs/src/misc.rst
src/unix/linux.c

Document that we return UINT64_MAX if the cgroup limit is set to the
max. For cgroupv2, that happens if we encounter `max`, while cgroupv1
returns 9223372036854771712 when no limit is set (which according to
[this StackExchange discussion] is derived from LONG_MAX and
PAGE_SIZE). So make sure we also detect this case for cgroupv1.
[this StackExchange discussion]: https://unix.stackexchange.com/questions/420906/what-is-the-value-for-the-cgroups-limit-in-bytes-if-the-memory-is-not-restricte
Addresses: https://github.com/libuv/libuv/pull/3744/files#r974062912

Document return value of uv_get_constrained_memory if no limit is set.

---

src/win/process.c

It fixes the build in our `Windows Server 2012r2` bots. Refs: https://github.com/libuv/libuv/issues/3887#issuecomment-1549438691

win: define MiniDumpWithAvxXStateContext always

---

include/uv/errno.h

`FreeBSD` defines `ENODATA` in /usr/include/c++/v1/errno.h which is only visible if C++ is the compilation unit. This can cause interop issues when integrating libuv build with C on a C++ project. Avoid this issue by directly defining with the value defined in the file previously mentioned.

freebsd: hard-code UV_ENODATA definition

---

src/unix/linux.c

io_uring sometimes erroneously returns EOWNERDEAD when the intention was to return 0. It's harmless and fixed in linux 5.14 so just ignore the error.
Fixes: https://github.com/libuv/libuv/issues/4001
Refs: https://github.com/torvalds/linux/commit/21f965221e

linux: work around EOWNERDEAD io_uring kernel bug

---

src/unix/linux.c

In the case of trying to write more than `IOV_MAX` buffers, the `IORING_OP_WRITEV` operation will return `EINVAL`. As a temporal fix, fallback to the old ways. In the future we might implement this by linking multiple `IORING_OP_WRITEV` requests using `IOSQE_IO_LINK`.

linux: fix WRITEV with lots of bufs using io_uring

---

test/test-thread.c

The threadpool_multiple_event_loops test already calls RETURN_SKIP when needed. Remove it from the callback function where it isn't needed work (nor works) and generates a build warning when compiling for qemu.
Fixes: https://github.com/libuv/libuv/issues/4014

test: remove erroneous RETURN_SKIP

---

src/unix/linux.c

Android's zealous seccomp filter blocks the io_uring_setup system call.
Fixes: https://github.com/libuv/libuv/issues/4010

android: disable io_uring support

---

configure.ac

This was requested, to make it easier to use our `make dist` packages. There is significant debate online regarding whether this flag is "not cool"[^1] to include, including by the flag's original author and the documentation for the flag itself[^2]. But this setting means that nothing changes by default, except that libuv gains support for the `--disable-maintainer-mode` command line flag. So it seems quite reasonable to include here, despite some blogs arguing that this makes libuv "less cool".
[^1]: https://blogs.gnome.org/desrt/2011/09/08/am_maintainer_mode-is-not-cool/
[^2]: https://www.gnu.org/software/automake/manual/automake.html#maintainer_002dmode

build: add autoconf option for disable-maintainer-mode

---

src/unix/linux.c

Just cap it to `IOV_MAX` as it's already done when performing reads using the threadpool.

linux: fs_read to use io_uring if iovcnt > IOV_MAX

---

src/unix/core.c

Apple's documentation claims ru_maxrss is reported in kilobytes but the XNU source code suggests the actual unit is bytes, like macOS.
Fixes: https://github.com/libuv/libuv/issues/4025

ios: fix uv_getrusage() ru_maxrss calculation

---

docs/src/pipe.rst
include/uv.h
include/uv/unix.h
src/unix/pipe.c
src/win/pipe.c
test/test-pipe-getsockname.c

Add two new APIs for binding and connecting to abstract UNIX sockets.
Fixes: https://github.com/libuv/libuv/issues/4028
<hr>
TODO: add docs

linux: support abstract unix sockets

---

docs/src/errors.rst
include/uv.h
include/uv/errno.h

Refs: https://github.com/nodejs/node/pull/48050
EUNATCH is referenced here: https://man7.org/linux/man-pages/man3/errno.3.html
CC @libuv/ibmi

include: add EUNATCH errno mapping

---

src/unix/fs.c
src/unix/linux.c

Work around a poorly understood bug in older kernels where closing a file descriptor pointing to /foo/bar results in ETXTBSY errors when trying to execve("/foo/bar") later on.
The bug seems to have been fixed somewhere between 5.15.78 and 5.15.98. I couldn't pinpoint the responsible commit but good candidates are the several data race fixes.
Interestingly, it seems to manifest only when running under Docker so the possibility of Docker bug can't be completely ruled out either.
This commit moves uv__kernel_version() from fs.c to linux.c because the latter now uses it more than the former.
Fixes: https://github.com/nodejs/node/issues/48444

linux: work around io_uring IORING_OP_CLOSE bug

---

src/win/error.c

This reverts commit a6ba1d709eea338df4a6ba125a01efa20de34ad7 (#3565) This revert was supposed to happen only on libuv v1.x, not libuv master. Refs #3193.

Reland "win,errors: remap ERROR_ACCESS_DENIED to UV_EACCES (#3193)"

---

AUTHORS
ChangeLog
configure.ac
include/uv/version.h

Finalize `v1.46.0`. Already tagged, pushed and artifacts published, but the `v1.x` branch is protected so I need a PR for this.

Release v1.46.0 

---

src/win/fs.c

We forgot to mask off the high bits from the first byte, so we ended up always failing the subsequent range check.
Refs: #2970 (need to fix this in the commit message when merging)
Fixes: https://github.com/nodejs/node/issues/48673

fs: fix WTF-8 decoding issue

---

CMakeLists.txt

CMake 3.27 now warns that "Compatibility with CMake < 3.5 will be removed from a future version of CMake." (https://cmake.org/cmake/help/latest/release/3.27.html#deprecated-and-removed-features)
This PR adds 3.5 as an allowable minimum CMake version, keeping the "minimum minimum" at 3.4.
Background: GitHub recently upgraded the version of CMake on their Ubuntu 22.04 container image to 3.27 (https://github.com/actions/runner-images/commit/79252fad3a14bc2c1893881d39d51905c4d2d50d), and this broke the build for some projects that include libuv with `-Werror=dev` (e.g. https://github.com/WebAssembly/wabt/pull/2273).
Could also just bump the minimum up to 3.5 (or higher) if you prefer. It was last updated in https://github.com/libuv/libuv/pull/2495

build: silence CMake deprecation warning

---

src/unix/kqueue.c
src/unix/linux.c

Made this PR more for discussion about the kqueue and epoll implementations. They're very similar, but the ~~addition~~ changed location of a check in 42cc412c ~~has caused a~~ is crashing as reported in  https://github.com/nodejs/node/issues/48490. It's unknown why this is happening, and the `assert()` has been moved to be directly after `kevent()` to make reasoning easier while debugging the crash. Instead of making the `assert()` conditional on the state of `reset_timeout`.
I'm currently trying to replicate the crash in the linked node issue. So far have been unsuccessful. Also, by removing the early return we enforce updating the timestamp. Not sure if that would have been considered a bug.
Then main question is, should `timeout` never be `-1` if `nfds == 0`?

unix: match kqueue and epoll code

---

docs/requirements.txt
docs/src/conf.py

It's responsive and the content is centered on the screen. Also, dark mode!

doc: switch to Furo, a more modern Sphinx theme

---

src/win/fs.c

Adjust include order to avoid redefining `CTL_CODE`, `FILE_READ_ACCESS`, and `FILE_WRITE_ACCESS`.

win,fs: avoid winapi macro redefinition

---

src/unix/linux.c

Specifically on non-longterm kernels between 5.16.0 (non-longterm) and 6.1.0 (longterm). Starting with longterm 6.1.0, the issue is solved.

unix: disable io_uring close on selected kernels

---

src/unix/signal.c
test/test-fork.c
test/test-list.h

If a signal was received but was not dispatched before fork then
caught_signals counter should be reset. Closing of signal pipe makes
imposible to receive the signal that was counted.
There is no need in this signal because it was sent to parent process
See full description in issue #3483
https://github.com/libuv/libuv/issues/3483

signal: reset signal counters after fork (#3483)

---

src/win/process.c

Make sure this handle is functional. The Windows kernel seems to have a bug that if the first use of AssignProcessToJobObject is for a Windows Store program, subsequent attempts to use the handle with fail with INVALID_PARAMETER (87). This is possilby because all uses of the handle must be for the same Terminal Services session. We can ensure it is tied to our current session now by adding ourself to it. We could remove ourself afterwards, but there doesn't seem to be a reason to.
Secondly, we start the process suspended so that we can make sure we added it to the job control object before it does anything itself (such as launch more jobs or exit).
Fixes: https://github.com/JuliaLang/julia/issues/51461

win,process: avoid kernel bug with starting Windows Store apps

---

src/uv-common.c

Make printing handles from gdb a little easier because it doesn't always know how to locate the stdout or stderr globals from libc.
With this commit `call uv_print_all_handles(0, 0)` prints the handles from the default loop to stderr.

src: default to stream=stderr in handle printer

---

src/unix/os390.c

This PR instead calls `__get_cpu_model()` from ZOSLIB, which uses PCCA to correctly get the cpu model.
Also resolves: https://github.com/libuv/libuv/issues/4102

zos: correctly get cpu model in uv_cpu_info()

---

test/test-get-passwd.c

Part of https://github.com/libuv/libuv/issues/4143
uid 0 is qsecofr on IBM i

test: fix get_passwd2 on IBM i

---

test/benchmark-pump.c
test/run-tests.c
test/task.h
test/test-fs-readdir.c
test/test-fs.c
test/test-getters-setters.c
test/test-idna.c
test/test-ipc-send-recv.c
test/test-spawn.c
test/test-tcp-close-after-read-timeout.c
test/test-tcp-close-reset.c
test/test-tcp-create-socket-early.c
test/test-thread.c
test/test-tty-duplicate-key.c
test/test-tty-escape-sequence-processing.c
test/test-tty.c
test/test-udp-create-socket-early.c

Following the switch to new-style ASSERT macros some warnings appeared for tests on pointers
Using ASSERT_PTR_* for those tests

test: switch from ASSERT_* to ASSERT_PTR_* for tests using pointer operands

---

src/unix/thread.c

Under heavy workloads `pthread_cond_wait` on macOS can return `EINVAL` while all the input parameters are correct.
As it happens due to a syscall having an `errno` of `EBUSY` we can detect it and workaround it.
Fixes #4165

darwin: workaround apple pthread_cond_wait bug

---

test/test-udp-send-hang-loop.c

section 3 of rfc 5737 lists 192.0.2.0/24 as TEST-NET-1, fix confusion about /8 and /24

doc fix 192.0.2.0/24 is the actual -TEST-NET-1

---

docs/src/pipe.rst

reStructuredText requires a `::` (double-colon) to read something as a valid directive. Otherwise, it assumes that the text is just a comment.
Fixes: 66319cf494d7875a6ffc8653928d31ffbd07187f
_Changed in version 2.0.0: long filenames will lead to an error rather than being truncated_ isn't shown.
_Changed in version 2.0.0: long filenames will lead to an error rather than being truncated_ is shown.

[v2] docs: fix bad reStructuredText directive

---

src/unix/fs.c

Implement in terms of pread/pwrite and only try to read/write the first
buffer. Callers are supposed to handle partial reads and writes.
(Our own fs_read_bufs test doesn't but that's fine because this commit
is a fix-up for unsupported platforms that aren't in our CI matrix.)
Fixes: https://github.com/libuv/libuv/issues/4176
<hr>
The second and third commit are cleanup.

unix: add back preadv/pwritev fallback

---

CMakeLists.txt
configure.ac

The recently added support for minidumps use SHGetKnownFolderPath which requires shell32.lib - for some reason the builds work without that on x64, while failing on arm64.

build,win: we need to link against shell32.lib

---

src/unix/fs.c

This PR tweaks the logic introduced in commit 8d69f256d18d4a2fc8295399224d433748b8a466 addressing https://github.com/libuv/libuv/issues/4176.
* The workaround for preadv/pwritev is needed only for Solaris, not illumos, so avoid it on illumos; these systems define `__illumos__` which can be used to differentiate them from Sun Solaris systems.
* Also, while the currently released [Haiku](https://www.haiku-os.org/get-haiku/) version requires the workaround, the upcoming Release 1 Beta 5 will provide preadv and pwritev functions; only use the workaround on lower versions.

unix: No preadv/pwritev workaround if not needed.

---

src/unix/linux.c

It's been reported that no released kernels are bug-free enough to use io_uring without causing regressions.
Fixes: https://github.com/libuv/libuv/issues/4158

linux: disable io_uring on 32 bits arm systems

---

.github/workflows/sanitizer.yml
test/test-fs-event.c

Opening as draft because there are some known tsan issues, particularly around our fsevents integration.

build: run sanitizers on macos ci

---

docs/src/misc.rst
include/uv.h
src/idna.c
src/idna.h
src/win/dl.c
src/win/fs-event.c
src/win/fs.c
src/win/getaddrinfo.c
src/win/getnameinfo.c
src/win/internal.h
src/win/pipe.c
src/win/process.c
src/win/tty.c
src/win/util.c
test/test-idna.c

As promised in https://github.com/libuv/libuv/pull/2970, this attempts to migrate code to a common set of utilities in a common place in the code and use them everywhere. This also exports the functionality, since the Windows API with WideCharToMultiByte is fairly verbose relative to what libuv and libuv's clients typically need, so it is useful not to require clients to reimplement this conversion logic unnecessarily (and because Windows is not 64-bit ready here, but this implementation is.)

[RFC] export WTF8 conversion utilities

---

CMakeLists.txt

This makes cmake more consistent about how to name this file, otherwise sometimes it names it uv.lib and sometimes libuv.a depending on which compiler is selected or if ./configure is used.
Refs: https://github.com/libuv/libuv/pull/2085#issuecomment-1735276640

build: fix libuv.a file name for cmake

---

src/win/util.c

> uv_os_uname() on Windows queries the registry value "HKEY_LOCAL_MACHINE\ SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName" to fill uv_utsname_t. If calling application was compiled for x86 and run on a x86_64 host, that query is redirected to "Computer\HKEY_LOCAL_MACHINE\ SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\ProductName" instead.
>
> For whatever reason, the value of 'ProductName' in the 32-bit registry section on 64-bit Windows sometimes differs from the 64-bit equivalent value and is inaccurate (e.g. containing the data
"Windows 10 Enterprise" while the 64-bit value accurately contains "Windows 10 Pro").
>
> Adds the 'KEY_WOW64_64KEY' security descriptor when opening the appropriate registry key so that the value of ProductName is always taken from the …

win: improve accuracy of ProductName between arch

---

.github/workflows/CI-win.yml

uv_run_tests.exe fails to start up with exit code 0xC0000135 a.k.a. STATUS_DLL_NOT_FOUND, suggesting it cannot find the ASAN runtime libraries. Disable the buildbot until we figure out how to fix that.
Refs: https://github.com/libuv/libuv/issues/4210

build: disable windows asan buildbot

---

test/test-tcp-writealot.c

The test is prone to time out at the best of times, never mind when running under MemorySanitizer.

test: don't run tcp_writealot under msan

---

configure.ac

I suggested in https://github.com/libuv/libuv/pull/4182 to add the flag to configure.ac as well but seems we already link to it.
I've removed the first one, not the second one, in case libuv is linked with --as-needed.

build,win: remove extraneous -lshell32

---

src/unix/tcp.c

Passing this to uv__is_ipv6_link_local() is causing a segmentation fault. Note that the documentation for getifaddrs() explicitly states that this value may be NULL.

ipv6_link_local: Ignore ifaddrs with NULL ifa_addr

---

src/unix/pipe.c
src/win/pipe.c
test/test-pipe-bind-error.c

This was incorrectly dropped by #4030, where previously connecting to "" might fail eventually, now instead it would return EINVAL and then fail to initialize the struct or call the callback.

pipe: add back error handling to connect / bind

---

src/unix/linux.c

First kernel with support is 6.1, was only fully functional from .51 onwards: https://lore.kernel.org/all/cb912694-b1fe-dbb0-4d8c-d608f3526905@gmx.de/
cc @thesamesam

linux: disable io_uring on hppa below kernel 6.1.51

---

src/unix/pipe.c
src/win/pipe.c
test/test-pipe-getsockname.c

Passing a socket name without a trailing nul byte to uv_pipe_bind2() or (on Windows) uv_pipe_connect2() resulted in reading beyond the end of the name buffer when copying or converting it.
This commit also fixes a small memory leak in the Windows error path of uv_pipe_bind2().

unix,win: fix read past end of pipe name buffer

---

src/unix/fs.c

@bnoordhuis @johnsonjh Could we have this fixed, please?

unix: unbreak macOS < 10.14

---

src/unix/tcp.c

aix does not implement ifaddrs and when retrieving the network interfaces with uv_interface_addresses there was a test failure in tcp_connect6_link_local.
Ref: https://github.com/libuv/libuv/pull/4222#issuecomment-1812962233
For now disable ipv6 link local on aix to:
1) fix broken aix build
2) stop blocking libuv upgrade in node
Ref: https://github.com/nodejs/node/pull/50650
I've got a PR open to use `uv_interface_addresses` on AIX. 
Ref: https://github.com/libuv/libuv/pull/4222
This is still a work in progress and will need more review and testing before merging. 
In the meantime, we can skip ipv6 link local on AIX and IBM i to prevent blocking libuv upgrade in node.
CC
@richardlau 
@mhdawson 
@libuv/ibmi
@libuv/aix

aix: disable ipv6 link local

---

src/unix/fs.c

Amendment to #4230.
Correct version bounds based on the function annotations:
```
ssize_t pwritev(int, const struct iovec *, int, off_t) __DARWIN_NOCANCEL(pwritev) __API_AVAILABLE(macos(11.0), ios(14.0), watchos(7.0), tvos(14.0));
```
Also don't apply the logic to iOS, where `MAC_OS_X_VERSION_MIN_REQUIRED` may not be defined:
https://github.com/libuv/libuv/blob/4785ad6337aac8b78224291f0848f25fc8cb41c9/src/unix/internal.h#L74-L76
or otherwise default to something prehistoric like 10.4.
---
I agree though with the comment that perhaps in the future it may be worth switching to runtime checking (or configure/cmake checking), as it could be written OS agnostically. I wouldn't be suprised if there's other fringe platforms.

unix: correct pwritev conditional

---

test/test-fs.c

On Fedora's build system, the build environment runs on btrfs. This revealed a bug in the test on i686 systems, where this comparison was being performed as a comparison of two signed integers, but the filesystem type of btrfs happens to use the higher-order bits, resulting in it appearing as a negative value.
BTRFS_SUPER_MAGIC     0x9123683e

test_fs.c: Fix issue on 32-bit systems using btrfs

---

src/win/process.c

Refer to this https://github.com/nodejs/node/issues/46264 , Windows always execute executable on current directory without path prefix. This behavior is dangerous.  this change is validate environment variable `NoDefaultCurrentDirectoryInExePath` is set or not.
Before changes:
If you have notepad.exe in current directory, and then execute it. it will return executable path on current directory.
After changes:
This change return original path to notepad.exe if `NoDefaultCurrentDirectoryInExePath` is set.

win: provide NoDefaultCurrentDirectoryInExePath env var on Windows

---

src/idna.c

w_target_len is set but unsued in release mode.

idna: fix compilation warning

---

test/test-tcp-write-in-a-row.c

On IBM i this test fails asserting the write queue size. The test expects the queue size to be greater than 0 but the queue size is 0 on IBM i.
https://github.com/libuv/libuv/blob/66160d6973b41040f6b2066a84359147258f60c3/test/test-tcp-write-in-a-row.c#L75
The test expects the write to get queued because the size of the data is larger than the send and receive buffers.
https://github.com/libuv/libuv/blob/66160d6973b41040f6b2066a84359147258f60c3/test/test-tcp-write-in-a-row.c#L39-L40
For some reason the request does not seem to get queued on IBM i. The root cause of the issue will need further investigation.
Part of #4143 
CC
@libuv/ibmi 
@richardlau

test: skip tcp-write-in-a-row on IBM i

---

CMakeLists.txt
configure.ac
src/win/process.c

Fixes #4259. See the report and discussion in that issue. This patch is as suggested by @bnoordhuis in https://github.com/libuv/libuv/issues/4259#issuecomment-1862617768.
This patch fixes the build for us on MinGW.
I took the GUID value from MinGW's `shlobj.h`. I based the indentation on
https://github.com/libuv/libuv/blob/1479b76310a38d98eda94db2b7f8a40e04b3ff32/src/win/poll.c#L31-L40

build,win: work around missing uuid.dll on MinGW

---

CMakeLists.txt
src/win/fs-event.c
src/win/fs.c
src/win/pipe.c
src/win/process.c
src/win/tty.c
test/run-tests.c
test/runner-win.c
test/test-fs-copyfile.c
test/test-fs-event.c
test/test-fs-readdir.c
test/test-fs.c
test/test-getters-setters.c
test/test-metrics.c
test/test-poll.c
test/test-spawn.c
test/test-threadpool-cancel.c

On Windows, the non-leading-underscore names of the Unix functions are deprecated and become unavailable by default starting from C11.
Also, this changes the build configuration so we diagnose usage of these names.

win: stop using deprecated names

---

src/unix/pipe.c
test/test-pipe-getsockname.c

The `\0` character has no special significance in abstract sockets, so the addrlen field in both `bind()` and `connect()` should take that into account.

linux: fix bind/connect for abstract sockets

---

include/uv/win.h

Make comments compliant with ANSI C89/90.
Fixes #4269.

Update win.h to fix comments

---

.gitignore

The clangd index, before creating the `compile_commands.json` file will create the indexes under a `.cache` folder. This does not need to be tracked by the repo.
I know this may be very trivial, but I find it very annoying always double-check that I don't add that freaking folder to the stage.

build: add `.cache` clangd folder to `.gitignore`

---

src/unix/tcp.c

Solaris claimed it supported the TCP-Alives mechanism, but TCP_KEEPIDLE, TCP_KEEPINTVL, and TCP_KEEPCNT were not available on Solaris until the latest version 11.4. Therefore, we need to simulate the TCP-Alives mechanism on other platforms via TCP_KEEPALIVE_THRESHOLD + TCP_KEEPALIVE_ABORT_THRESHOLD.
- [Solaris 11.3](https://docs.oracle.com/cd/E86824_01/html/E54777/tcp-7p.html)
- [Solaris 11.4](https://docs.oracle.com/cd/E88353_01/html/E37851/tcp-4p.html)

unix: support full TCP keep-alive on Solaris

---

src/unix/kqueue.c

the new F_KINFO flag does not seem to work with directories nor with deleted entries.

uv__fs_event freebsd fix proposal.

---

src/unix/fs.c
src/unix/internal.h
src/unix/linux.c

Fallback to the threadpool if it returns `EOPNOTSUPP`.
Fixes: https://github.com/nodejs/node/issues/50876
Observed when performing a write in a `vboxsf` filesystem as reported in the nodejs issue.

linux: retry fs op if unsupported by io_uring

---

src/unix/kqueue.c

KINFO_FILE_SIZE is only defined on intel archs.
close #4274.

fix kqueue build on freebsd/non intel archs.

---

src/unix/tcp.c

Reduce the amount of code being compiled and trim trailing whitespace in passing.

Optimize preprocessor directives on Solaris for uv__tcp_keepalive

---

src/unix/linux.c

Since `io_uring` support was added, libuv's signal handler randomly segfaults on
ppc64le when interrupting `epoll_pwait`.  Disable it pending further investigation.
Issue: https://github.com/libuv/libuv/issues/4283

linux: disable io_uring on ppc64 and ppc64le

---

.github/workflows/CI-win.yml
CMakeLists.txt
Makefile.am
docs/src/process.rst
include/uv.h
src/unix/process.c
src/win/process.c
test/test-list.h
test/test-spawn.c

Add a `UV_PROCESS_WINDOWS_FILE_PATH_EXACT_NAME` flag to enable the optional behavior.
Prompted by https://gitlab.kitware.com/cmake/cmake/-/issues/25450#note_1451473.  Continuing from #4241.

win/spawn: optionally run executable paths with no file extension

---

src/unix/signal.c

This reverts commit b9421d70665352138557d2d2338656a38ac70691.
Refs: https://github.com/libuv/libuv/issues/4299
Refs: https://github.com/libuv/libuv/issues/4248

Revert "unix: restore signal disposition to previous one (#4216)"

---

src/timer.c

As there were instances where this didn't happen and could cause memory corruption issues.
Refs: https://github.com/libuv/libuv/issues/4248

unix,win: reset the timer queue on stop

---

test/test-spawn.c

The return value from signal(2) is a pointer. Use the right macro.

test: fix -Wpointer-to-int-cast on 32 bits systems

---

src/thread-common.c

the local uv_barrier_t implementation is used: for AIX, OpenBSD and any system not defining PTHREAD_BARRIER_SERIAL_THREAD.
as the uv_barrier_t struct was modified and it isn't a pointer anymore, the check for uv_barrier_t size isn't right anymore for systems not using local uv_barrier_t implementation. so move the check inside the block implementing uv_barrier_t using pthread_barrier_t.
tested on OpenBSD, where the build failed due to the STATIC_ASSERT().

test uv_barrier_t size in right block

---

src/unix/udp.c

Issue:
1. uv__io_poll calls uv__udp_io with revents == POLLIN + POLLOUT
2. uv__udp_io calls your recv_cb
3. you close the handle in callback
4. uv__udp_io calls uv__udp_sendmsg
5. uv__udp_sendmsg calls uv__io_feed
6. kaboom!

DON'T sendmsg with udp closed

---

src/unix/cygwin.c

According to the documentation for Cygwin, the penultimate field of [/proc/pid/stat](http://www.cygwin.com/cygwin-ug-net/proc.html) corresponds to the RSS, so the method is basically the same as in the Linux version. The only difference is that [`getpagesize()`](https://cygwin.com/cgit/newlib-cygwin/tree/winsup/cygwin/syscalls.cc#n2836) will return `wincap.allocation_granularity()`, but in this mapping, RSS is calculated using [`wincap.page_size()`](https://cygwin.com/cgit/newlib-cygwin/tree/winsup/cygwin/fhandler/process.cc#n1185), which can be accessed by [`sysinfo.mem_unit`](https://cygwin.com/cgit/newlib-cygwin/tree/winsup/cygwin/sysconf.cc#n815).

unix: implementation of uv_resident_set_memory for cygwin

---

src/win/process.c

It might happen that only using `WaitForSingleObject()` with timeout 0 could return WAIT_TIMEOUT as the process might not have been signaled yet. To improve things, first use `GetExitCodeProcess()` and check that `status` is not `STILL_ACTIVE`. Then, to cover for the case that the exit code was actually `STILL_ACTIVE` use `WaitForSingleObject()`. This could still be prone to the race condition but only for that case.
Fixes: https://github.com/nodejs/node/issues/51766

win: almost fix race detecting ESRCH in uv_kill

---

test/test-env-vars.c

The test hits an honest-to-$deity kernel bug, see the investigation in the linked issue.
Fixes: https://github.com/libuv/libuv/issues/4338

test: disable env var test under win32+asan

---

src/unix/fs.c
src/unix/fsevents.c

Make sure we allocate the memory with uv__malloc so it's in turn freed with uv__free.
Fixes: https://github.com/libuv/libuv/issues/4329

unix,fs: fix realpath calls that use the system allocator

---

src/unix/linux.c

The filename of the executable may contain parentheses. If so, `*rss` will be invalid.

unix-linux: Fix uv_resident_set_memory executable name

---

.github/workflows/sanitizer.yml
test/test-platform-output.c

The new Ubuntu 22.04 image seem to ship a buggy version of ASAN that spams thousands of "AddressSanitizer:DEADLYSIGNAL" warnings to the console for no apparent reason when the barrier_3 test runs.
Pin the sanitizers to the old Ubuntu LTS for now.
This commit also fixes a small bug in the platform_output test where the cgroups v1 logic did not handle the "unlimited quota" special case properly. Ubuntu 20.04 still uses cgroups v1.

test,ci: fix [AM]San, disable ASLR

---

CMakeLists.txt
Makefile.am
src/unix/linux.c
test/test-iouring-pollhup.c
test/test-list.h

Perform EPOLL_CTL_DEL immediately instead of going through io_uring's submit queue, otherwise the file descriptor may be closed by the time the kernel starts the operation.
<hr>
I still need to ~~steal~~ adopt Santi's test case but I ran out of time for the day.

linux: don't delay EPOLL_CTL_DEL operations

---

docs/src/udp.rst

uv_udp_init() creates the UDP socket lazily but to set socket options there must be, well, a socket to set the options on. Document how and when that requirement is met.
Fixes: https://github.com/libuv/libuv/issues/4370

doc: correct udp socket options documentation

---

src/win/util.c

Observed on the Windows 2022 ASAN buildbot but does not reproduce elsewhere.
My hypothesis is that something clobbers the thread-local error variable so restructure the loop to capture it as soon as possible.
Fixes: https://github.com/libuv/libuv/issues/4338

win: robustify uv_os_getenv() error checking

---

test/test-fs-event.c

Should hopefully make it easier to debug CI flakiness because currently the test sometimes fails without a clear indication why.

test: use newer ASSERT_MEM_EQ macro

---

src/unix/process.c

Our platform-specific headers provide a dedicated indicator.

process: de-duplicate conditions for using kqueue

---

.mailmap
src/unix/darwin.c

mach_continuous_time is available since macOS 10.12, but our minimum version is 11, so no need for a workaround.
Also, prefer that to `clock_gettime_nsec_np(CLOCK_MONOTONIC_RAW)` which the documentation suggests
(https://developer.apple.com/documentation/driverkit/3438077-mach_continuous_time) since the latter calls mach_timebase_info every time, unnecessarify: https://github.com/apple-open-source/macos/blob/49dcc07a40d19fa97384033a8398dae5d00d11a1/Libc/gen/clock_gettime.c#L107

darwin: simplify uv_hrtime

---

src/win/tcp.c

Windows 7 is no longer supported.

win: remove no longer needed define

---

src/unix/fs.c
test/test-fs-copyfile.c

This commit changes the timestamps in the file, the ownership and the group.
Fixes: https://github.com/libuv/libuv/issues/3125
Am I missing any metadata here?
```sh
juan@ubuntu:/tmp$ ls -l | grep cop
-rwxrwxrwx 1 juan testing  811 Apr 26 22:12 copied
-rwxrwxrwx 1 juan testing  811 Apr 26 22:12 copied2
-rwxrwxrwx 1 juan testing  811 Apr 26 21:47 copyFile.c
```

linux,darwin: make `uv_fs_copyfile` behaves like `cp -r`

---

src/unix/udp.c

We shouldn't enable SO_REUSEPORT on `DragonflyBSD` because that socket option has different semantics from other *BSD: [it shares the port rather than steals it.](https://gitweb.dragonflybsd.org/dragonfly.git/commit/740d1d9f7b7bf9c9c021abb8197718d7a2d441c9)

dragonfly: disable SO_REUSEPORT for UDP socket bindings

---

test/test-fs-event.c

This macro was first introduced by 4741a112ad7116486977361691738d6bb3f0c729 and should've been removed in ad20b96a8f258db79f67d7465a7373737e253802, but somehow it got left out.

test: remove the obsolete HAVE_KQUEUE macro

---

src/unix/tcp.c

Stuffing `SOCK_NONBLOCK` and `SOCK_CLOEXEC` into the `type` argument when calling `socketpair()` is widely supported across UNIX-like OS: Linux, *BSD, Solaris, etc., as is the `socket()`. [`socket()`](https://pubs.opengroup.org/onlinepubs/009604499/functions/socket.html) and [`socketpair()`](https://pubs.opengroup.org/onlinepubs/009604499/functions/socketpair.html) share the SOCK_* flags under the hood.
Currently, we detect the presence of `SOCK_NONBLOCK` and `SOCK_CLOEXEC` for `socket()`:
https://github.com/libuv/libuv/blob/bf61390769068de603e6deec8e16623efcbe761a/src/unix/core.c#L494-L499
while checking the specific OS macros for `socketpair()`. We keep them in sync to expand the scope of SOCK_* flags for `socketpair()`.
- [socketpair(2) on …

unix: use the presence of SOCK_* instead of OS macros for socketpair

---

src/unix/pipe.c

Before this PR, `pipe2()` is only enabled on Linux and FreeBSD while `pipe2()` is available on *BSD.
This PR enables `pipe2()` for the rest of *BSD: DragonFlyBSD, NetBSD and OpenBSD.
- [pipe2 on DraonFlyBSD](https://man.dragonflybsd.org/?command=pipe&section=2)
- [pipe2 on  NetBSD](https://man.netbsd.org/pipe.2)
- [pipe2 on OpenBSD](https://man.openbsd.org/pipe.2)
---------
Signed-off-by: Andy Pan <i@andypan.me>

bsd: support pipe2() on *BSD

---

CMakeLists.txt
Makefile.am
docs/src/tcp.rst
include/uv.h
src/unix/tcp.c
src/win/tcp.c
test/test-list.h
test/test-tcp-reuseport.c

For #386, #570, #1229
Relevant issue: nodejs/node#12228
---------
The time was not ripe for introducing the `SO_REUSEPORT` TCP in #386 because `SO_REUSEPORT`s on platforms other than Linux didn't have the capabilities of load balancing, but as time went by, other systems started to extend the `SO_REUSEPORT` to distribute workload across all listening sockets: DragonFlyBSD 3.6.0 (2013), FreeBSD 12.0 (2018), Solaris 11.4 (2018), AIX 7.2.5 (2020). #400 was made as a workaround for those who only wanted to enable `SO_REUSEPORT` on Linux by creating the socket beforehand, and of course, what it does is beyond the `SO_REUSEPORT`. Therefore, I think it's time to reconsider officially supporting this feature.
- [DragonFlyBSD 3.6.0 Release notes](https://www.dragonflybsd.org/release36/)
- [socket: …

unix: support SO_REUSEPORT with load balancing for TCP

---

test/test-tcp-reuseport.c

Start connecting to the peers after all threads
to poll for accepting connections.
For #4407

test: fix the flaky test-tcp-reuseport

---

CMakeLists.txt
Makefile.am
docs/src/tcp.rst
docs/src/udp.rst
include/uv.h
src/unix/core.c
src/unix/internal.h
src/unix/tcp.c
src/unix/udp.c
src/win/udp.c
test/test-list.h
test/test-tcp-reuseport.c
test/test-udp-reuseport.c

unix: support SO_REUSEPORT with load balancing for UDP

---

src/unix/core.c
src/unix/internal.h
src/unix/tcp.c

DragonFly BSD changed the time unit for TCP keep-alive from milliseconds to seconds since v5.8 and Solaris 11.4 added `TCP_KEEPIDLE`, `TCP_KEEPINTVL`, and `TCP_KEEPCNT` with time units in second while Solaris <11.4 still use `TCP_KEEPALIVE_THRESHOLD` and `TCP_KEEPALIVE_ABORT_THRESHOLD` with time units in millisecond.
Currently, we don't differentiate among DragonFly BSD versions but set the keepalive options with seconds, which will result in unexpected behaviors on DragonFlyBSD <5.8. This PR intends to fix the wrong usage of time units of TCP keepalive options on DragonFly BSD <5.8 and consolidate the logic of time units conversion for TCP keepalive across platforms.
In addition, this PR introduces a new custom macro for determining Solaris 11.4. This macro is expected to help us …

tcpkeepalive: distinguish OS versions and use proper time units

---

src/win/error.c

`CreateProcessW()` in `uv_spawn()` on Windows will fail with `ERROR_BAD_EXE_FORMAT` if attempting to run a file that is not executable.
Refs: https://github.com/libuv/libuv/issues/2348

win: map ERROR_BAD_EXE_FORMAT to UV_EFTYPE

---

README.md

Greetings, fellow community!
We have just added the latest version of libuv to [Conan Center](https://conan.io/center/recipes/libuv?version=1.48.0) and thought it would be a nice addition to include instructions on how to install libuv via Conan in the README file.
Please let me know if this is okay, or if you would prefer it placed elsewhere.
Regards!

[docs] Add instruction how to install libuv using Conan

---

src/random.c
src/threadpool.c
src/unix/fs.c
src/unix/getaddrinfo.c
src/unix/getnameinfo.c
src/unix/linux.c
src/unix/stream.c
src/unix/udp.c
src/uv-common.h
src/win/fs.c
src/win/getaddrinfo.c
src/win/getnameinfo.c
src/win/pipe.c
src/win/req-inl.h
src/win/stream.c
src/win/tcp.c
src/win/tty.c
src/win/udp.c

`req` parameter is unused in uv__req_register and uv__req_unregister macros. So, I suggest to remove it.

Remove unused parameter from uv__req_register and uv__req_unregister macros

---

.github/workflows/CI-unix.yml

It's complaining in the post-run step about a missing symbol:
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version
`GLIBC_2.28' not found (required by /__e/node20/bin/node)
Which is likely coming from the obsolete actions/checkout@v2 because the runner itself is using ubuntu-latest and that comes with a new enough glibc.

build: fix android ci build

---

include/uv.h

Mark them UV_EXTERN so they are visible on Windows.
Fixes: https://github.com/libuv/libuv/issues/4436

unix,win: export wtf8 functions properly

---

CMakeLists.txt
src/unix/process.c

This PR defines some macro prerequisites and a header include to get libuv compile again on gnu-hurd.
- ptsname() needs _XOPEN_SOURCE >= 500
- setenv() needs _POSIX_C_SOURCE >= 200112
- setgroups() needs grp.h

[hurd] includes and macro prerequisites

---

src/unix/core.c

On GNU/Hurd, the scheduling priorities on pthreads are not implemented. As we don't want all applications to have to handle this particular case, libuv falls back on simulating a success and no-op.

[hurd] Replace uv_thread_setpriority() by a stub

---

.github/workflows/CI-unix.yml
.github/workflows/sanitizer.yml

macOS 11 is gone: https://github.com/actions/runner-images/pull/10198

ci: use macOS 12 for macOS and iOS builds

---

src/unix/fs.c

Disable sendfile() on iOS with ARM architecture
to avoid crashes caused by throwing SIGSYS signal.
Fixes: #3187

darwin: fix crash on iOS(arm64)

---

docs/src/fs.rst

The docs there link to GetFinalPathNameByHandleA() and CreateFileA(), but src/win/fs.c uses GetFinalPathNameByHandleW() and CreateFileW().

doc: correct names of Win32 APIs in fs.rst

---

src/win/error.c

This was incorrectly mapped originally, which makes for confusing error messages about an EPIPE if a program happens to (unwisely) set PIPE_NOWAIT on the handle. It is unclear to me if libuv should try to handle this in some meaningful way (as would normally be done on unix platforms) since the OS documents that it is not possible to handle correctly (the OS just documents that this flag should never be set because it cannot be handled correctly), and so it is very unclear what that way would look like. But this goal is to at least expose this errno to the caller with the correct translation.
This error shouldn't be possible to trigger currently, so I don't think this is breaking, but it is intended to be clearer for anyone else who happens to run into #4467 being caused by running a …

win,error: remap ERROR_NO_DATA to EAGAIN

---

test/test-udp-recv-in-a-row.c

Under rare but benign circumstances, incoming datagrams are dropped by the operating system after libuv has been notified of their arrival but before it has had a chance to receive them.
Fixes: https://github.com/libuv/libuv/issues/4219

test: handle zero-length udp datagram

---

test/test-udp-multicast-join.c

The test is skipped in its entirety on OpenBSD so there is no point in compiling out code on said platform later on, it's not run anyway.

test,openbsd: remove superfluous ifdef guard

---

src/win/util.c
test/test-homedir.c
test/test-tmpdir.c

If the corresponding environment variables are empty, the `uv_us_homedir()` and `uv_os_tmpdir()` return garbage values. The reason for this situation is the Windows API which doesn't return an error even if the path is empty.
This PR fixes this problem by checking the return value of the API call. If it is not an error and the length of the value is less than  3, `uv_us_homedir()` and `uv_os_tmpdir()` will return `UV_ENOENT`.
Fixes: https://github.com/libuv/libuv/issues/2328

win: fix env var in uv_os_homedir and uv_os_tmpdir

---

src/unix/fsevents.c
src/win/fs-event.c
test/test-fs-event.c
test/test-list.h

Which was broken both in `windows` and `macos`.
Fixes: https://github.com/nodejs/node/issues/52055

fsevents: detect watched directory removal

---

src/unix/async.c
src/unix/linux.c

Register the eventfd with EPOLLET to enable edge-triggered notification where we're able to eliminate the overhead of reading the eventfd via system call on each wakeup event.
When the eventfd counter reaches the maximum value of the unsigned 64-bit, which may not happen for the entire lifetime of the process, we rewind the counter and retry.
This optimization saves one system call on each event-loop wakeup, eliminating the overhead of read(2) as well as the extra latency for each epoll wakeup.
---------
Signed-off-by: Andy Pan <i@andypan.me>

linux:  exploit `eventfd` in `EPOLLET` mode to avoid syscall per wakeup

---

src/unix/pipe.c
test/test-pipe-bind-error.c

~~I've added a check to ensure long file names
are not larger than NAME_MAX.~~
This issue was discovered when debugging
a failing test case on AIX.
ref: https://github.com/libuv/libuv/issues/4231
On AIX saddr.sun_path is set to a large buffer size but file names cannot be greater than NAME_MAX.
NAME_MAX is a standard posix constant that we can get the value of using pathconf.
https://linux.die.net/man/3/pathconf
~~The code now returns EINVAL when the name length
is greater than the NAME_MAX.~~
~~Test Build on AIX now passes: https://ci.nodejs.org/job/libuv-test-commit-aix/nodes=aix72-ppc64/lastBuild/console~~
This PR was orginally a code change but now its been adjusted to be a test case change see: https://github.com/libuv/libuv/pull/4442#issuecomment-2240492087 
fixes …

test: pipe_overlong_path handle ENAMETOOLONG

---

src/win/fs.c
src/win/winapi.c
src/win/winapi.h

Windows added a new API for file information, which doesn't have to open the file thus greatly improving performance: https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfileinformationbyname .
This PR implements this improvement on libuv. This was based on the Python implementation: https://github.com/python/cpython/blob/3a72fc36f93d40048371b789e32eefc97b6ade63/Modules/posixmodule.c#L2089-L2120 .
The stat functions are already covered by tests, so no test was added here. I considered comparing the result of old and new code, but that would require exposing internal fs functions, and we would be testing Windows functionality, not libuv.

win,fs: use the new Windows fast stat API

---

src/win/pipe.c

This fixes a race condition if multiple threads are reading from the same NamedPipe, which could previously lead to a deadlock situation. We could also substantially improve performance now also, since the PeekFile call is unnecessary overhead with this change.
Related to #4467, though doesn't address any of the problems there. I believe that someone could now implement `uv__pipe_try_write` using exactly this same code pattern however.
The various `*= 2;` are to prove that this works and fixes the bug, but should be removed before merging. A small bit of additional code cleanup may be possible as well now?

win,pipe: fix race with concurrent readers

---

src/win/tty.c

The Event should be reset before reading the value, or libuv might miss an update that occurred too rapidly after the previously one.
This thread and the delay here seems to have been added in https://github.com/libuv/libuv/pull/2381 by @bzoz, but I don't see a justification there for why 30 fps is correct, or why libuv shouldn't just assume the system will limit to the USB polling and thread-switching frequencies anyways. In libuv, it seems to be causing strictly more work for the system by limiting it to 30 fps, since it has to jump through an extra thread, when SIGWINCH should be coalescing these events anyways. I am somewhat inclined thus to say we should just delete the extra thread and the delay (alternatively, libuv could also use MsgWaitForMultipleEvents with a 33 ms timeout to …

win,signal: fix data race dispatching SIGWINCH

---

docs/src/fs.rst
docs/src/loop.rst
include/uv.h
src/unix/internal.h
src/unix/linux.c
src/unix/loop.c

The SQPOLL io_uring instance wasn't providing consistent behaviour to users depending on kernel versions, load shape, ... creating issues difficult to track and fix. Don't use this ring by default but allow enabling it by calling `uv_loop_configure()` with
`UV_LOOP_ENABLE_IO_URING_SQPOLL`.
Refs: https://github.com/libuv/libuv/pull/4421#issuecomment-2225860128

linux: disable SQPOLL io_uring by default

---

src/win/fs.c

Refactor / cleanup arithmetic for unix -> win filetime conversion in order to avoid multiplication overflow.
Fixes:
```
src/win/fs.c:106:48: runtime error: signed integer overflow: 1702781567 * 10 cannot be represented in type 'long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/win/fs.c:106:48 in
```

win: fix fs.c ubsan failure

---

test/test-fs-event.c
test/test-fs.c

- [test: rmdir can return EEXIST or ENOTEMPTY](https://github.com/libuv/libuv/commit/8bbd7dae57c80368b46f77973a7a29b8ee61632f) 
POSIX allows `rmdir` to return `EEXIST` or `ENOTEMPTY` for a non-empty
directory, so the test needs to allow both.
- [test: check for UV_CHANGE or UV_RENAME event](https://github.com/libuv/libuv/commit/a0c6eb19328da10da1f3e9ad7cee864dec80d27a) 
All other checks for `UV_RENAME` in `test-fs-event` also allow
`UV_CHANGE`.
Fixes: https://github.com/libuv/libuv/issues/4483
Fixes: https://github.com/libuv/libuv/issues/4484

fs test fixes

---

src/unix/async.c
src/unix/core.c
src/unix/internal.h
src/unix/kqueue.c

Eliminate the kernel overhead of `pipe` if we can.

kqueue: use EVFILT_USER as wakeup event if available

---

src/win/util.c

Electron builds on Windows with clang, not msvc, and likewise hits this issue without this extra handling. This would allow us to remove a [patch](https://github.com/electron/electron/blob/9c94fd7afb4706c2d2228a455f0874a0370cfe1d/patches/node/fix_suppress_clang_-wdeprecated-declarations_in_libuv.patch#L6)

fix: suppress clang -Wdeprecated-declarations in libuv

---

docs/src/loop.rst
docs/src/misc.rst
docs/src/request.rst

I use python to scan rst files for generating nim binding.
Some data types are not described in the rst file so the generated code needs to be maintained manually.
I added the `uv_loop_option` in the `Data types` section.
I modified the `uv_group_s` in the document to `uv_group_t`.
I moved the description of `uv_req_type` to the `Data types` section for easier parsing.

Adjust paragraph format and document enum type uv_loop_option

---

docs/src/handle.rst
docs/src/loop.rst
docs/src/request.rst

They have no return value.
https://github.com/libuv/libuv/blob/1790abb3b233d87a947074a79e8ea68bd3885862/include/uv.h#L488
https://github.com/libuv/libuv/blob/1790abb3b233d87a947074a79e8ea68bd3885862/include/uv.h#L492
https://github.com/libuv/libuv/blob/1790abb3b233d87a947074a79e8ea68bd3885862/include/uv.h#L1932

Fix docs: The `uv_*_set_data` series of functions have no return value

---

docs/src/fs.rst
docs/src/fs_event.rst
docs/src/handle.rst
docs/src/poll.rst
docs/src/process.rst
docs/src/request.rst
docs/src/tcp.rst
docs/src/tty.rst
docs/src/udp.rst

I'm sorry, I've been filing various documentation issues lately, and these trivial issues caused my script to generate incorrect code.
Correct version:

Fix docs: Some `c:enum` types are incorrectly annotated as `c:type`.

---

src/win/util.c

uv_os_getppid uses CreateToolhelp32Snapshot to enumerate processes and find the parent process PID. However, CreateToolhelp32Snapshot has poor performance. To optimize the performance of subsequent calls, a static variable is used to cache the result.
While analyzing the performance of an Electron application, I discovered that calling Node.js process.ppid invokes uv_os_getppid, which in turn calls CreateToolhelp32Snapshot, a function known for its relatively poor performance.

win, util: optimize the performance of uv_os_getppid

---

src/win/pipe.c

In #4470, I accidentally copied the bug from unix, where calling uv_stream_set_blocking can cause the whole process to hang on a read. However, unlike unix, where libuv attempts to set the O_NONBLOCK flag in uv_pipe_open (as long as the handle never gets passed to uv_spawn), the NT kernel is not capable of enabling OVERLAPPED operation later (but fortunately, it also cannot disable it later too).
This implementation might be good to copy to unix (using FIONREAD) to address the same bug that happens there if the user has called uv_spawn or uv_stream_set_non_blocking on this handle in the past.

win,pipe: restoring fallback handling for blocking pipes

---

include/uv/tree.h
src/unix/signal.c
src/win/signal.c

The PR removes unused parameters from RB-trees macros: RB_NEXT and RB_PREV.

Remove unused parameters from RB-trees macros

---

src/win/util.c
src/win/winapi.h

Get parent process ID using NtQueryInformationProcess is faster than using CreateToolhelp32Snapshot.
My colleague suggested using NtQueryInformationProcess to implement uv_os_getppid, claiming it would be much faster. I ran some tests and found that NtQueryInformationProcess took only 0.00027 ms, while CreateToolhelp32Snapshot took 3.6 ms.

win, util: uv_os_getppid use NtQueryInformationProcess

---

src/win/pipe.c

Otherwise this accidentally results in `r == 1` (aka UV_EISDIR) on this code path, which can be quite confusing for the caller indeed. I now ran all of the neovim tests locally this time, and none hang (some fail, but seems like that is because it expects some test dependencies to be installed, and I don't know what they are)

win,pipe: fix missing assignment to success

---

src/win/util.c

Fixes commit 58dfb6c89b from a few days ago. DWORD_PTR is 32 bits on x86 Windows. Use the right bit count when checking the population count.
Interestingly enough, it manifested itself as double counting available processors, presumably because the compiler emits a ROR instead of SHR.
Fixes: https://github.com/libuv/libuv/issues/4524

win: fix uv_available_parallelism on win32

---

src/win/pipe.c

Yet another followup to #4511. `functional/legacy/increment_spec.lua` failed most of the time without this. You would think I had never written software before or something. Hopefully this is the last fix to this PR🤞

win,pipe: fix another missing assignment to success

---

src/unix/kqueue.c
test/test-poll.c

We learned it the [hard way in Go](https://github.com/golang/go/blob/7fcd4a7007979e4aaa9e8893bd0088f5f28627e7/src/os/file_unix.go#L175-L208), and I hope Node.js, Julia or anything else built on top of `libuv` don't have to go through what Go has been through.

kqueue: disallow a few ill-suited kinds of file descriptor

---

src/unix/core.c
src/unix/internal.h
src/unix/tty.c

Libuv stores the `struct termios` for use inside uv_tty_reset_mode().
Node.js uses said function to restore the tty to its original mode on SIGINT or SIGTERM, when there is no opportunity to shut down the process normally.
Track uv_tty_t handle closing, otherwise we might be trying to use a stale termios.
The current solution is not ideal because there can be multiple handles that refer to the same tty/pty and, for various reasons, we can't really determine when we close the last handle. The last handle may not even be inside the current process.
Still, all things considered, it's probably (hopefully!) an improvement over the status quo.
Refs: https://github.com/libuv/libuv/issues/4398

unix: restore tty attributes on handle close

---

src/unix/fs.c

Both gcc 11 and 12 emit wrong code for a function call pointer in one very specific context.
Fixes: https://github.com/libuv/libuv/issues/4532

unix: work around arm-linux-gnueabihf-gcc bug

---

Makefile.am

Overlooked in commit 1c778bd0 ("darwin: add udp mmsg support") from earlier this month.
Fixes: https://github.com/libuv/libuv/issues/4544
@santigimeno probably warrants a point release?

build: add darwin-syscalls.h to release tarball

---

src/win/util.c

Reverts libuv/libuv#4512 since this was accidentally merged into master, which will likely cause annoying conflicts after merging https://github.com/libuv/libuv/pull/4514 to v1.x

Revert "win, util: optimize the performance of uv_os_getppid" (in favor of #4514)

---

src/unix/linux.c
src/uv-common.h

Introduced in Linux 6.6, it tells the kernel to omit the sqarray from the ring buffer.
Libuv initalizes the array once to an identity mapping and then forgets about it, so not only does it save a little memory (ca. 1 KiB per ring) but it also makes things more efficient kernel-side because it removes a level of indirection.

linux: use IORING_SETUP_NO_SQARRAY when available

---

src/unix/fs.c
src/unix/internal.h
src/unix/linux.c
src/uv-common.h

Route ftruncate() system calls through io_uring instead of the thread pool when the kernel is new enough to support it (linux >= 6.9).
This commit harmonizes how libuv checks if the kernel is new enough. Some ops were checking against `uv__kernel_version()` directly while others stored the result of the version check as a feature flag.
Because the kernel version is cached, and because it is more direct than a feature flag, I opted for the former approach.

linux: use IORING_OP_FTRUNCATE when available

---

src/win/winapi.c

Fixed incorrect verification of the pNtQueryDirectoryFile pointer.

win: fix pNtQueryDirectoryFile check

---

src/win/error.c
src/win/fs.c
src/win/internal.h
src/win/stream.c

Translate `ERROR_BROKEN_PIPE` and `ERROR_NO_DATA` to `UV_EPIPE` instead of their default translation, which will be used for the rest of cases.
Refs: https://github.com/libuv/libuv/issues/4548#issuecomment-2383998849

win: fix WriteFile() error translation

---

src/win/fs.c
test/test-fs.c

After commit 18266a6969, it changed to return `ENOTDIR`, which makes it consistent with other platforms but it also can be considered a breaking change.

win,fs: uv_fs_rmdir() to return ENOENT on file

---

src/win/pipe.c

The implementation of IPC pipe in libuv on Windows does not properly support async reading. This means we cannot set the more parameter without likely causing hangs. Sorry this is yet another followup to #4511.
Fixes #4548

win,pipe: ipc code does not support async read

---

src/win/fs.c
test/test-fs-readdir.c
test/test-list.h

`isSymbolicLink()` was returning wrong values for the symlink folders. I've updated the order of the conditions to be consistent with `fs__scandir` in order to fix this issue.
Refs: https://github.com/nodejs/node/issues/48799

win,fs: fix bug in fs__readdir

---

README.md
src/unix/fs.c

Disable optimization on `uv__preadv_or_pwritev`.
Fixes: https://github.com/libuv/libuv/issues/4532
Fixes: https://github.com/libuv/libuv/issues/4550

unix: workaround gcc bug on armv7 (part 2)

---

src/unix/internal.h

Make sure `UV__SOLARIS_11_4` is not set for `smartOS`/`illumOS`. In our codebase is used only twice:
- Detect correct implementation of `SO_REUSEPORT`, which is not even implemented on `illumOS`.
- Detect the time unit used for the TCP keepalive options. If set to `0`, which was the case for `illumOS`, it chose milliseconds, which is not correct for `illumOS` either as it uses seconds.
/cc @panjf2000

unix: fix uv_tcp_keepalive in smartOS

---

src/unix/core.c

This appears to be a simple math error that bugged me! I tested on omnios but `rusage->ru_maxrss` there was always 0 so the change didn't make any difference! Still might be good to fix.

Fix uv_getrusage's ru_maxrss calculation on Solaris

---

src/win/fs.c
test/test-fs.c

I've investigated why this trailing slash was added originally, but I couldn't find any reason.
Fixes: https://github.com/libuv/libuv/issues/3329

win,fs: remove trailing slash in junctions

---

src/win/getaddrinfo.c

The logic in #4254 is incorrect, and results in the addrinfo linked list only having a single result. Fix this by correcting the logic.
Closes #4577

Fix linked list logic in windows getaddrinfo

---

src/win/winapi.h

Compilation against the 24H2 SDK is broken by #4327
Fix that issue by only conditionally defining the new values.
Closes #4575

Fix compilation against Windows 24H2 SDK

---

src/win/error.c
test/test-error.c

It seemed incorrect to map a segfault to EACCES, since posix would typically map this to EFAULT. The ERROR_BUFFER_OVERFLOW is literally "the filename is too long", and is not typically an invalid parameter in posix.
Test originally added in #1060 to test the API, not the value.
Refs: https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--500-999-

win: remap ERROR_NOACCESS and ERROR_BUFFER_OVERFLOW

---

include/uv.h
src/unix/process.c
src/win/process.c

Add UV_PROCESS_WINDOWS_CATCH_EXCEPTIONS to allow the user to suppress Windows Error Reporting. Windows Error Reporting may display interactive popups when a fatal error occurs.
Related to https://github.com/libuv/libuv/pull/3838 (This MR makes these changes configurable, instead of being applied unconditionally)
Also related to https://github.com/libuv/libuv/issues/1327 and https://github.com/libuv/libuv/issues/2829
Default behavior is unchanged.

Windows: Allow users to configure crash handling

---

src/win/fs.c

Refs: #4582
@santigimeno Does this fix the test for you? I am just going by eye, but looks like the intent of this nodejs test is to make sure the trailing slash in readlink matches up exactly with what the user specified in mklink (modulo replacing `[/\\]+` runs with `\`)

win,fs: match trailing slash presence in junctions to user input

---

CMakeLists.txt

Fixes a deprecation warning with new cmake versions.
Changing the minimum from 3.9 to 3.10 should be safe because there isn't even a non-EoL'd distro left that ships 3.10, let alone 3.9.
Fixes: https://github.com/libuv/libuv/issues/4603

build: update minimum cmake to 3.10

---

src/unix/async.c
src/unix/internal.h
src/unix/kqueue.c

Establishes a user event for kqueue to eliminate the overhead of the pipe and the system call read(2) per wakeup event.
Relands commit 27134547ff using VSCode merge, since it shows the conflict is just on the order of #ifdef calls.

kqueue: use EVFILT_USER for async if available

---

src/idna.c
test/test-idna.c
test/test-list.h

uv_wtf8_length_as_utf16() checks if codepoints are > 0xFFFF (to see if it should be encoded as a surrogate pair), therefore uv_wtf8_to_utf16() should too. Instead it checked > 0x1000. Harmonize the checks.
Fixes: https://github.com/nodejs/node/issues/55914
<hr>
The wtf8 code seems to have no tests at all? Did I overlook them?

unix,win: fix off-by-one in uv_wtf8_to_utf16()

---

src/unix/async.c

The compile-time detection check from commit 7b75935 ("kqueue: use EVFILT_USER for async if available") was not actually used, breaking numerous operating systems.

unix: fix build breakage on haiku, openbsd, etc

---

src/unix/pipe.c
test/test-pipe-getsockname.c

Fixes: https://github.com/libuv/libuv/issues/4610

unix,pipe: fix handling null buffer in uv_pipe_get{sock,peer}name

---

src/fs-poll.c
src/unix/core.c
src/uv-common.c
src/win/pipe.c
src/win/util.c
test/test-fs-event.c

For any API that takes a buffer and size pointer, check both pointers and the pointed-to size and return UV_EINVAL in case of error.
Example:
```
int uv_foo(char* buffer, size_t* size) {
if (buffer == NULL || size == NULL || *size == 0)
return UV_EINVAL;
...
}
```
In order to "peek" the necessary size for dynamic allocation, the following pattern can be used:
```
char *buf;
char scratch[1];
size_t len = sizeof(scratch);
int r;
r = uv_foo(scratch, &len);
assert(r == UV_ENOBUFS);
buf = malloc(len);
r = uv_foo(buf, &len);
...
```

unix,win: harmonize buffer checking

---

.github/workflows/CI-unix.yml

Upgrade GHA image to Ubuntu 24.04 and use the distro-provided qemu.
It should not be necessary anymore to install qemu from .deb because the stock qemu is new enough in 24.04.

build: fix qemu builds

---

src/unix/linux.c

io_uring support was default-disabled because of numerous kernel bugs but those are all in the sqpoll (file i/o) parts of io_uring.
Batching of epoll_ctl calls through io_uring works fine, is a nice optimization, and is therefore unconditionally enabled again.
The UV_USE_IO_URING environment variable now only affects sqpoll, and only when the UV_LOOP_ENABLE_IO_URING_SQPOLL event loop flag is set.
Fixes: https://github.com/libuv/libuv/issues/4616

linux: always use io_uring for epoll batching

---

docs/src/timer.rst

It was already documented but only in the uv_timer_set_repeat section. Move it to the toplevel and flesh it out more.
Refs: https://github.com/libuv/libuv/issues/181
Refs: https://github.com/libuv/libuv/discussions/4639

doc: clarify repeating timer behavior more

---

src/win/thread.c
src/win/winapi.h
test/test-thread-name.c

It supports the API: https://github.com/mirror/mingw-w64/blob/93f3505a758fe70e56678f00e753af3bc4f640bb/mingw-w64-headers/include/processthreadsapi.h#L358

win: enable uv_thread_{get,set}name on MinGW

---

src/win/fs-event.c

This PR is in response to a node bug I found:
https://github.com/nodejs/node/issues/52769
The leak appears to be coming from libuv leaking short_path.  This PR fixes it by freeing it.

Freeing short_path to fix win watch leak

---

docs/src/fs_event.rst
test/test-fs-event.c

This commit documents a FreeBSD kernel issue where uv_fs_event can receive a NULL filename and updates test-fs-event.c to skip filename assertions on FreeBSD.
* Bugzilla: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197695
Refs: https://github.com/libuv/libuv/issues/4606
-----
This is not precisely a fix, but I'm open to pivot this PR into something else.

test: address FreeBSD kernel bug causing NULL path in fsevents

---

docs/src/udp.rst
include/uv.h
include/uv/unix.h
src/unix/udp.c
src/uv-common.c
src/uv-common.h
src/win/udp.c
test/test-udp-try-send.c

Add a version of uv_udp_try_send that can send multiple datagrams.
Uses sendmmsg(2) on platforms that support it (Linux, FreeBSD, macOS),
falls back to a regular sendmsg(2) loop elsewhere.
This work was sponsored by ISC, the Internet Systems Consortium.
<hr>
The first commit is a NFC that is prep work for the second commit. Same line count, more functionality, improved legibility (IMO)
I moved `uv__udp_sendmsg` to the bottom of udp.c because the diff is crazy hard to read otherwise.
I don't love the name `uv_udp_try_send2` but I guess it's convention by now. Can I see hands for `uv_udp_try_sendv`? `uv_udp_try_send_many`? Other suggestions?

unix,win: add uv_udp_try_send2

---

docs/src/threading.rst
src/win/thread.c
src/win/winapi.c
src/win/winapi.h

As said symbols are unavailable on Windows Server 2016.
Fixes: https://github.com/libuv/libuv/issues/4677

win: lazy-load [GS]etThreadDescription symbols

---

src/unix/fs.c

Fixes: https://github.com/libuv/libuv/issues/4678
Refs: https://github.com/libuv/libuv/issues/4532

linux: try preadv64/pwritev64 before preadv/pwritev

---

src/unix/async.c

In chrooted env without /dev/null uv_loop_init() fails. Use "/" instead. 
The same fix is already present in src/unix/stream.c

fix for missing /dev/null in chrooted enviroment

---

src/win/winapi.h

This fixes the order of the last two fields in the `FILE_STAT_BASIC_INFORMATION` struct.
Documentation: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-file_stat_basic_information

win: fix order of FILE_STAT_BASIC_INFORMATION struct fields

---

src/unix/thread.c

The pthread_getaffinity_np function is not supported on OpenHarmony systems. Add **\_\_OHOS\_\_** Macro to support affinity.

unix: Add support for affinity on openharmony

---

docs/src/fs.rst
include/uv.h
src/unix/fs.c
src/uv-common.h
src/win/fs.c
test/test-fs.c

Extend uv_fs_utime, uv_fs_futime and uv_fs_lutime to accept NAN and INFINITY, with NAN meaning "don't touch the timestamp" and INFINITY meaning "set to the current timestamp."
Ugly, but it avoids having to add uv_fs_utime2, etc.
Fixes: https://github.com/libuv/libuv/issues/4665

unix,win: accept NAN/INFINITY as file timestamps

---

test/test-platform-output.c

Fixes: https://github.com/libuv/libuv/issues/4713

test: handle UV_ENOTSUP in platform_output

---

docs/src/threading.rst

This should fix the HTML output, which [currently looks as follows](https://docs.libuv.org/en/v1.x/threading.html#c.uv_thread_setpriority):

doc: fix rendering of threading.html

---

src/unix/udp.c

Solaris provides sendmmsg() as of 11.3.32.
It was added at the same time as MSG_WAITFORONE.
The same is seen in Illumos guarded by __BSD_VISIBLE
Fixes: https://github.com/libuv/libuv/issues/4715

unix,sunos: enable use of sendmmsg on Solaris and Illumos

---

src/unix/aix.c
src/unix/bsd-ifaddrs.c
src/unix/ibmi.c
src/unix/linux.c
src/unix/sunos.c

Allocate storage upfront, that way we can never run out of memory halfway through processing the interface list.
Fixes: https://github.com/libuv/libuv/issues/4723

unix: handle out of memory in iface name copy

---

src/unix/openbsd.c

On OpenBSD we do not know the cpuspeed in same cases (mostly arm64) and the HW_CPUSPEED sysctl will return EOPNOTSUPP in that case, which can be ignored because we still need the rest of the CPU information.

openbsd: do not error out if cpuspeed is not available

---

test/test-thread-name.c

`uv_thread_getname` is not available on aix and ibm i
Same issue as thread_name test case
see: https://github.com/libuv/libuv/pull/4599#issuecomment-2498376606
CC
@libuv/ibmi 
@libuv/aix

test: aix/ibmi skip thread_name_threadpool

---

docs/code/plugin/main.c

In function main, the pointer lib allocated at line 7 is passed as an argument to functions uv_dlopen at line 10, uv_dlerror at lines 11 and 17, and uv_dlsym at line 16, but it is never freed before the function returns at line 24. This results in a memory leak bug.
Thus we add a free operation before the function returns.

Free pointer `lib` before function returns.

---

src/fs-poll.c

Rename the `handle` parameter of `timer_close_cb`'s declaration to `timer` to match the definition.

style: rename parameter to match definition

---

test/runner-unix.c
test/runner-win.c
test/runner.c
test/runner.h

This commit updates the test runner's print_lines() logic to better handle partial lines.
Prior to this change, I was seeing output like this (you can observe this in the CI as well):
```
```
After this change, I'm seeing:
```
```

test: support partial output lines in test runner

---

src/unix/pipe.c

Solaris implemented pipe2 in 11.4 and illumos have had it since 2013.
Ref:
https://docs.oracle.com/cd/E88353_01/html/E37841/pipe2-2.html
https://illumos.org/man/2/pipe2
https://www.illumos.org/issues/3714

pipe2: support pipe2 on solaris and illumos

---

src/unix/pipe.c

Use fchmod() on platforms that support it on UNIX sockets. Only fall back to chmod() on platforms that don't (macOS and the BSDs.)
Remove the stat + chmod dance from the fallback and just call chmod directly, because that's another source of TOCTOU issues.
Fixes: https://github.com/libuv/libuv/issues/2040
<hr>
The removal of stat() is possibly maybe a change in behavior but IMO the previous behavior is wrong.

unix: remove TOCTOU issues from uv_pipe_chmod

---

src/unix/pipe.c

On some platforms (like GNU/Hurd), `getsockname` returns an empty string for sockets in the UNIX domain. However, we do have stored the path info in `pipe_fname` of `uv_pipe_t`, so we can try with it if `getsockname` returns an empty string.
---
I've tested this on GNU/Hurd and it works well now.

unix: uv_pipe_chmod try with pipe_fname if getsockname returns ''.

---

src/unix/haiku.c

Haiku has parallel types to `stdint.h`, and their APIs use these types.  In the Haiku-specific `haiku.h` file, it is passing an address of a `uint32_t` to `get_cpu_topology_info()`, that expects the other `uint32`:
https://github.com/haiku/haiku/blob/648fa5897c28d5a4c8a5b4992dbf9b9d410434c8/src/system/libroot/os/system_info.cpp#L187
You get an "incompatible-pointer-types" warning in gcc if the warnings are turned up.  But if you pass the pointer to Haiku's notion of `uint32`, then the warning goes away.

Use uint32 vs. uint32_t for Haiku API

---

docs/src/threadpool.rst

I changed the default stack size in commit 73b0c1f94 from October 2022 and although I added a versionchanged note, I didn't update the blurb a few lines below.
It wasn't accurate before that change either though, because even with musl libc's ~80kb thread stacks, 128 threads works out to 10 MB.
Refs: https://github.com/nodejs/node/issues/57911

doc: update thread pool stack size comment

---

test/test-connect-unspecified.c

Distinguish a callback for v4 and v6 connections is not relevant for this test.

test: merge uv_tcp_connect callbacks

---

test/test-fs-event.c

Fixes: https://github.com/libuv/libuv/issues/4659

test: skip multievent tests on macOS with TSAN enabled

---

src/unix/core.c
src/unix/internal.h
src/unix/linux.c

Fixes: https://github.com/libuv/libuv/issues/4740

linux: align CPU quota calculation with Rust's cgroup heuristics

---

src/unix/sunos.c

---
Sadly I don't have a SunOS, but I believe this is what we should be doing.

sunos: use uv__io_init_start to simplify fs event watcher setup

---

README.md

---
This is quite irrelevant, but I have this believe of having simpler instructions to compile will reduce a bit the friction for new contributors and stuff.

build: add shorter instructions for CMake build

---

src/timer.c

---
Another day, another trivial patch.

src: remove unused include of <assert.h> in timer.c

---

test/test-udp-multicast-join.c

Fixes: https://github.com/libuv/libuv/issues/4778

test: skip `udp_multicast_join` if not system-wide available

---

docs/src/fs.rst
docs/src/loop.rst

The documentation is referring to an internal name - UV_LOOP_ENABLE_IO_URING_SQPOLL - in several places, fix this by using the public UV_LOOP_USE_IO_URING_SQPOLL name instead.

Fix documentation to say UV_LOOP_USE_IO_URING_SQPOLL  instead of  UV_LOOP_ENABLE_IO_URING_SQPOLL

---

src/unix/core.c
src/win/util.c
test/test-thread-priority.c

pthread_getschedparam and pthread_setschedparam do not use errno but instead return the error code directly.
https://pubs.opengroup.org/onlinepubs/9799919799/functions/pthread_getschedparam.html

unix: fix uv_thread_{get,set}priority returning incorrect error codes

---

.github/workflows/CI-unix.yml
.github/workflows/CI-win.yml
.github/workflows/sanitizer.yml

---
This is gonna make the gh-actions pipelines a bit shorter and will use our latest cmake build instructions.

build: deduplicate sanitizer jobs using matrix strategy

---

docs/src/guide/utilities.rst

The link at gnu.org is a redirect now and the docs linter breaks some times.

doc: update ncurses link

---

docs/src/tcp.rst
include/uv.h
src/unix/internal.h
src/unix/stream.c
src/unix/tcp.c
src/win/tcp.c
src/win/winsock.h
test/test-tcp-flags.c

Implement `uv_tcp_keepalive_ex` function that extends `uv_tcp_keepalive` to support `TCP_KEEPINTVL` and `TCP_KEEPCN` socket options in addition to TCP_KEEPIDLE.

tcp: support customizing TCP_KEEPINTVL and TCP_KEEPCNT

---

src/uv-common.c

Hi, 
This patch fixes a potential null pointer dereference in `src/uv-common.c` inside the `uv__print_handles()` function.
When `loop` is `NULL`, it falls back to `uv_default_loop()`, but the return value is not checked. As a result, if `uv_default_loop()` returns `NULL`, the subsequent call to `uv__queue_foreach(q, &loop->handle_queue)` will dereference a null pointer, leading to undefined behavior or a crash.
Main branch (as of b00c5d)
In `src/uv-common.c`, the function `uv__print_handles()` attempts to use `uv_default_loop()` when the input `loop` parameter is `NULL`. This occurs at line 579:
```c
if (loop == NULL)
loop = uv_default_loop();
```
However, `uv_default_loop()` can return `NULL` if `uv_loop_init()` fails internally. This leads to a potential null pointer dereference at line …

Fix potential null dereference in uv__print_handles() when uv_default_loop() fails

---

Makefile.am

This mirrors the behavior already fixed in the CMake build system.
Fixes: https://github.com/libuv/libuv/issues/4794
Refs: https://github.com/libuv/libuv/commit/4681d5d5705be932f82e1e79eff72f17b5bf82e2
---
Yeah, this is not as elegant as it should be, I'm just taking responsibility of fixing something I intended to fix a couple weeks back.

test: link with libm when autotools

---

include/uv.h

These macros are not defined in the public headers

include: remove unused private macro undefs from uv.h

---

src/win/util.c

Distinguish between errors and "the console title is the empty string" when calling GetConsoleTitle. Both are signified by a return value of zero.
No test because I couldn't think of a succinct way to programmatically create a new console window with an empty title.
Fixes: https://github.com/nodejs/node/issues/58695

win: handle empty string in uv_get_process_title

---

src/win/poll.c

This resolves potential race condition when child process has been created between WSASocketW() and SendHandleInformationW().
* src/win/poll.c (uv__fast_poll_create_peer_socket): Add WSA_FLAG_NO_HANDLE_INHERIT flag to WSASocketW() call. Remove SetHandleInformation(HANDLE_FLAG_INHERIT = 0) call.

win: Use WSA_FLAG_NO_HANDLE_INHERIT in WSASocketW().

---

src/unix/tcp.c

Refs: https://github.com/libuv/libuv/issues/4755

unix: handle possible `ENOMEM` in `uv__tcp_listen`

---

src/win/fs.c

Refs: https://github.com/libuv/libuv/security/advisories/GHSA-qf6p-jg38-9f4x#advisory-comment-131127

win: remove obsolete comment

---

src/unix/aix.c
src/unix/bsd-ifaddrs.c
src/unix/ibmi.c
src/unix/linux.c
src/unix/sunos.c
src/uv-common.c
src/win/util.c

---
This fixes a pending to do of sharing the function across different platforms.
Refs: https://github.com/libuv/libuv/pull/4818/files#diff-f94aad28d2cd4f6da2805a265c6645b8ae63cc49c9c1cb74ac7fadb9ba152733L160

unix: deduplicate uv_free_interface_addresses across platforms

---

src/win/async.c

Switch to __sync_fetch_and_or on x86. Libuv already uses it on other architectures.

win: replace inline asm with compiler intrinsic

---

src/win/pipe.c

Starting a new read after uv_read_cb returns causes memory corruption on the OVERLAPPED read_req if uv_read_stop+uv_read_start was called during the callback after the latest refactoring. This apparently also forces the kernel to deadlock us, since it apparently cannot cancel the second read while the first one is pending (reads apparently are not permitted to finish out of order). Avoid that simply by not issuing another read (set more=0) if there is already a read pending (from uv_read_start).
There are probably better things we could do here (such as bring back `uv_active_tcp_streams_threshold`), but the current `alloc_cb` design may not currently permit that without making breaking changes. We could also detect in `uv_read_start` that we are inside of of the `read_cb` for that stream, …

win,pipe: minimal fix to uv_read_cb->uv_read_start recursion bug

---

src/win/util.c

Fixes issues https://github.com/libuv/libuv/issues/4838

Added support for arm64 machine type in uv_os_uname for Windows

---

docs/src/pipe.rst

It was incorrectly documented as returning `void` since its addition, but it returns `int`.

doc: fix return value for `uv_pipe_connect2`

---

src/unix/udp.c

Fix a logic bug in the fallback code for platforms that don't have a sendmmsg-like system call. It only sent at most one packet, even when there were more available, and that was observable through a failing test on such systems.
Fixes: https://github.com/libuv/libuv/issues/4848

unix: fix udp sendmmsg fallback path

---

docs/code/pipe-echo-server/main.c
test/task.h
test/test-poll.c

This fixes the test suite in environments where `/tmp` is not writable or does not allow the use of Unix sockets, and matches the use of relative paths elsewhere in the tests.
---
I have only tested this change on macOS. If relative paths are unsuitable here for some reason, then another option would be using `uv_os_tmpdir`, but given the use of relative paths elsewhere in the test suite I hope that it should be fine.

test: use relative paths for pipes and Unix sockets

---

src/win/fs-fd-hash-inl.h
test/test-fs-fd-hash.c

The static initial table reserved space for MxN elements but only used every Nth element. Removing the excess elements shrinks the table 16x.
I added search/insertion/deletion time logging while here to ensure no performance regressions.
Fixes: https://github.com/libuv/libuv/issues/4823

win: shrink fd hash table from 2592k to 162k

---

src/win/process.c

_snwprintf_s takes its length argument in characters, not bytes.
Does not appear to be a security issue because the paths are not under an attacker's control unless the system has been compromised beyond salvation: requires a combination of being able to set the name of the executable and/or changing %LOCALAPPDATA% or a registry key.
Refs: https://github.com/libuv/libuv/security/advisories/GHSA-jjrx-vr7q-7732

win: fix path size calculation

---

src/threadpool.c

Use libuv's own OS-independent implementation to get env var UV_THREADPOOL_SIZE.
Fixes: #4887

fix: inconsistency in getting thread pool size from environment variable UV_THREADPOOL_SIZE on Windows.

---

src/unix/ibmi.c

Add a stub function for no-ahafs builds. src/unix/core.c won't actually call uv__ahafs_event but the linker still needs to see a symbol.
Like commit 87943b03 but for IBM i instead of AIX this time.

ibmi: add stub function to satisfy linker
