libuv/libuv

- src/unix/fs.c
The fix from commit 269ff0be is wrong in that it sniffs system headers
to determine if preadv() and pwrite() are supported.
It breaks the fs_write_multiple_bufs test on one of my ARM systems;
its glibc has preadv() and pwritev() wrappers but its kernel has no
support for the corresponding system calls.
Simply try the system call and fall back to a normal read or write
loop if not supported.  Move the no_preadv and no_pwritev variables
around to squelch two -Wpedantic warnings about mixing declarations
with code.
R=@saghul
> linux: fix support for preadv/pwritev-less kernels

- src/unix/pipe.c
Don't unlink the socket in uv_pipe_bind().  If the bind operation fails,
the socket is most likely not ours.
Fixes: https://github.com/libuv/libuv/issues/108
R=@saghul
> unix: don't unlink unix socket on bind error

- test/test-udp-options.c
> test: skip udp_options6 if there no IPv6 support

- docs/src/tty.rst
> doc: clarify the behavior of uv_tty_init

- src/unix/freebsd.c
> freebsd: make uv_exepath more resilient

- src/unix/tty.c
> unix: make setting the tty mode to the same value a no-op

- docs/src/fs_event.rst
> doc: clarify which flags are supported in uv_fs_event_start

- src/unix/darwin-proctitle.c
> Minor cleanup

- docs/src/dns.rst
- include/uv-unix.h
- include/uv-win.h
- include/uv.h
- src/unix/getaddrinfo.c
- src/unix/getnameinfo.c
- src/win/getaddrinfo.c
- src/win/getnameinfo.c
- test/test-getaddrinfo.c
- test/test-getnameinfo.c
- test/test-list.h
Continuation of #148, after we un-forked libuv/libuv.
R=@bnoordhuis
> Synchronous get{addr,name}info

- src/win/thread.c
The reported bug is arguably a compiler bug - a non-static inline
function should be inlined inside the compilation unit but still
have external linkage - but the abundant use of 'inline' isn't
really necessary in the first place.  Remove it.
Fixes: https://github.com/libuv/libuv/issues/191
> win: don't use inline keyword in thread.c

- include/uv-win.h
- test/test-fs.c
Also make the tests more strict.
> windows: fix setting dirent types on uv_fs_scandir_next

- build.mk
- checksparse.sh
- src/unix/stream.c
- test/test-list.h
- test/test-tcp-oob.c
- uv.gyp
In the collaboration with Ben Noordhuis <info@bnoordhuis.nl> and
Saúl Ibarra Corretgé <saghul@gmail.com>.
Cherry-picked from v1.x (e19089f)
Reviewed-By: Saúl Ibarra Corretgé <saghul@gmail.com>
Reviewed-By: Ben Noordhuis <info@bnoordhuis.nl>
> stream: use SO_OOBINLINE on OS X

- docs/src/conf.py
- docs/src/dns.rst
- docs/src/fs.rst
- docs/src/misc.rst
- docs/src/poll.rst
- docs/src/sphinx-plugins/manpage.py
- docs/src/stream.rst
R=@bnoordhuis (was it you who asked for this once?)
I may have missed some referencesd to system / library calls, but this should be the bulk of it.
> Generate links to manpages from documentation

- docs/src/dns.rst
- include/uv.h
Fixes: https://github.com/libuv/libuv/issues/182
R=@creationix
> doc: document uv_getnameinfo_t.{host|service}

- src/unix/fs.c
Thanks @julien33 for the patch.
Fixes: https://github.com/libuv/libuv/issues/252
> unix: fix compilation on Android

- test/test-tty.c
> test: fix tty_file, only close handle if initialized

- README.md
- docs/src/pipe.rst
- docs/src/tcp.rst
- docs/src/udp.rst
Fixes: https://github.com/libuv/libuv/issues/281
R=@bnoordhuis
> doc: clarify what uv_*_open accepts

- test/benchmark-getaddrinfo.c
- test/benchmark-loop-count.c
- test/benchmark-million-timers.c
- test/benchmark-ping-pongs.c
- test/benchmark-pound.c
- test/benchmark-pump.c
- test/benchmark-sizes.c
- test/benchmark-spawn.c
- test/run-benchmarks.c
- test/run-tests.c
- test/runner.c
- test/task.h
- test/test-handle-fileno.c
- test/test-idle.c
- test/test-ip6-addr.c
- test/test-loop-handles.c
- test/test-osx-select.c
- test/test-timer-again.c
- test/test-tty.c
Initial patch by @simar7, thanks!
> test: remove LOG and LOGF variadic macros

- Makefile.am
- src/unix/core.c
- test/test-list.h
- test/test-pipe-connect-prepare.c
- uv.gyp
> unix: don't block for io if any io handle is primed

- src/unix/linux-core.c
Old 32 bits kernels (native and compat) have a bug where timeouts larger
than (LONG_MAX / CONFIG_HZ) milliseconds are treated as infinite.
Work around that by capping the timeout and polling again if necessary.
R=@saghul?
> linux: work around epoll bug in kernels < 2.6.37

- src/unix/core.c
- src/unix/internal.h
- src/unix/udp.c
R=@bnoordhuis
Fixes: https://github.com/libuv/libuv/issues/301
> Make sure UDP send callbacks are always fired asynchronously

- test/runner-unix.c
Make the test runner code that waits for other processes to terminate
retry the select() system call on EINTR and take elapsed time into
account.
A small side effect of this change is that millisecond timeout values
are now honored.
R=@saghul
CI: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/112/
> test: retry select() on EINTR, honor milliseconds

- docs/src/index.rst
- docs/src/misc.rst
- docs/src/version.rst
- include/uv-version.h
- src/version.c
> core: add UV_VERSION_HEX macro

- src/unix/tty.c
Once we are past uv__stream_init, the handle has been added to
loop->handle_queue, it needs to be undone in case of failure.
R=@bnoordhuis
> tty: cleanup handle if uv_tty_init fails

- src/unix/kqueue.c
Refs: https://github.com/libuv/libuv/issues/387
R=@indutny, @bnoordhuis
> darwin: save a fd when FSEvents is used

- docs/src/fs.rst
> docs: add Windows specific note for uv_fs_open

- docs/src/fs.rst
Refs: https://github.com/libuv/libuv/issues/426
R=@bnoordhuis
> doc: add note about . and .. entries in uv_fs_scandir

- common.gypi
> build: remove ancient condition from common.gypi

- src/unix/core.c
R=@saghul
CI: https://ci.nodejs.org/view/libuv/job/libuv+any-pr+multi/181/
> unix: don't retry dup2/dup3 on EINTR

- vcbuild.bat
> build,win: print the Visual Studio version in use

- test/test-fs-event.c
> test,win: fix compilation warning

- gyp_uv.py
Fixes: https://github.com/libuv/libuv/issues/705
R=@saghul
CI: https://ci.nodejs.org/job/libuv+any-pr+multi/247/ (currently private)
> build: map 'AMD64' host arch to 'x64'

- src/unix/fs.c
Refs: https://github.com/nodejs/node/pull/5402
R=@bnoordhuis
> darwin: replace F_FULLFSYNC with fdatasync syscall

- src/win/tty.c
> win: remove unneeded condition

- CONTRIBUTING.md
- MAINTAINERS.md
R=@bnoordhuis @piscisaureus @indutny
> doc: add @cjihrig as a maintainer

- src/win/fs-event.c
> win: remove duplicated code when processing fsevents

- Makefile.am
- Makefile.mingw
> win,build: remove unused build defines

- Makefile.am
- checksparse.sh
- docs/src/misc.rst
- include/uv.h
- src/unix/core.c
- src/unix/internal.h
- src/win/internal.h
- src/win/util.c
- test/test-get-passwd.c
- test/test-list.h
- test/test-platform-output.c
- uv.gyp
This commit adds the `uv_get_passwd()` function, which returns a subset of the current effective user's password file entry.
Refs #731
> unix,windows: add uv_get_passwd()

- README.md
- docs/Makefile
Just to make things easier when editing the documentation.
R=@libuv/collaborators
> doc: add ability to live reload and regenerate HTML

- src/unix/linux-core.c
CI: https://ci.nodejs.org/job/libuv-test-commit/27/
> linux: fix fd leaks in uv_cpu_info() error paths

- src/win/fs-event.c
- src/win/internal.h
- src/win/util.c
Yak shaving at it's best.
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows/44/
R=@libuv/collaborators
> MOAR WINDOZE CLEANUP

- src/unix/thread.c
It has been reported that destroying condition variables that have been
signalled but not waited on can sometimes result in application crashes.
See https://codereview.chromium.org/1323293005.
CI: https://ci.nodejs.org/job/libuv-test-commit/41/
> darwin: work around condition variable kernel bug

- MAINTAINERS.md
> doc: add Imran Iqbal (iWuzHere) to maintainers

- test/runner-unix.c
- test/runner-win.c
- test/runner.c
- test/runner.h
- test/task.h
CI: https://ci.nodejs.org/job/libuv-test-commit/60/
> test: make tap output the default

- src/unix/error.c
Fixes: https://github.com/libuv/libuv/issues/899
> unix: map ENFILE errno

- src/win/fs.c
- src/win/tty.c
See https://github.com/libuv/libuv/issues/941.
CI: https://ci.nodejs.org/job/libuv-test-commit/70/
> Silence two -Wmaybe-uninitialized warnings

- include/uv-win.h
- src/win/core.c
- src/win/tcp.c
- src/win/udp.c
This code has been disabled since 2011, I guess we're ok without it.
> win: remove unused code

- src/unix/core.c
FreeBSD 9 is supported until the end of the year, but we are not going to release v2 before then, right? :-)
R= @libuv/collaborators
> unix: remove support for FreeBSD < 10

- src/win/core.c
- src/win/req-inl.h
Windows summer cleanup continues!
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows/121/
R= @libuv/collaborators
> win: remove unneeded internal function

- include/uv-win.h
- src/win/thread.c
After removing their fallbacks we can simplify their structure.
R= @libuv/collaborators 
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit-windows/122/
> Simplify uv_cond_t and uv_rwlock_t

- MAINTAINERS.md
> doc: add santigimeno to maintainers

- docs/src/fs.rst
Fixes: https://github.com/libuv/libuv/issues/1017
/cc @libuv/collaborators
> doc: document uv_fs_realpath caveats

- test/test-tty.c
Fixes: https://github.com/libuv/libuv/issues/1029
> test: fix building pty test on Android

- docs/src/handle.rst
- docs/src/misc.rst
R= @libuv/collaborators 
As brought up by @bagder in https://github.com/libuv/libuv/issues/1027#issuecomment-244386298
> Improve documentation for uv_alloc_cb

- README.md
(I always manage not not find find it when I need it, IMHO it's a useful thing to have there.)
> doc: add ABI tracker link to README

- test/test-threadpool-cancel.c
Saturate the thread pool before trying to post-and-cancel the work
request.  Before this commit we simply posted requests in a loop,
in the (sometimes idle) hope that one would get queued up instead
of being dispatched right away.
Refs: https://github.com/libuv/libuv/pull/1010
CI: https://ci.nodejs.org/job/libuv-test-commit/109/
R=@saghul
> test: make threadpool_cancel_single deterministic

- src/win/core.c
This commit moves the allocation of `uv__loops` into `uv__loops_add()` and frees all of the memory associated with `uv__loops` in `uv__loops_remove()` once the loop count reaches zero.
Fixes: https://github.com/libuv/libuv/issues/1252
Fixes: https://github.com/libuv/libuv/issues/1125
> win: free uv__loops once empty

- Makefile.am
- checksparse.sh
- docs/src/misc.rst
- include/uv.h
- src/unix/core.c
- src/win/util.c
- test/test-gethostname.c
- test/test-list.h
- uv.gyp
Fixes: https://github.com/libuv/libuv/issues/1315
> unix,win: add uv_os_gethostname()

- src/unix/fs.c
- src/win/fs.c
- test/test-fs-copyfile.c
Refs: https://github.com/libuv/libuv/pull/1465
> unix,win: check for bad flags in uv_fs_copyfile()

- tools/vswhere_usability_wrapper.cmd
Fixes: https://github.com/libuv/libuv/issues/1476
> Bump vswhere helper 2

- src/win/util.c
Windows version of https://github.com/libuv/libuv/pull/1760.
This commit refactors `uv_os_homedir()` to to use `uv_os_getenv()` to retrieve the `USERPROFILE` environment variable. This removes a fair amount of duplicated code, while introducing the following changes:
1. The function no longer returns `UV_EIO` when `USERPROFILE` is longer than `MAX_PATH`. This can be reinstated by adding a check for `r == 0 && *size >= MAX_PATH`.
2. The `USERPROFILE` string is now a `char*`, meaning that it must be converted from utf8 to utf16 by `uv_os_genenv()`.
CI with green Windows run: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/732/
> win: update uv_os_homedir() to use uv_os_getenv()

- include/uv/win.h
Refs: https://github.com/libuv/libuv/issues/1671
> win: remove _WIN32_WINNT define

- docs/src/fs.rst
- include/uv.h
- src/unix/fs.c
- src/win/fs.c
- test/test-fs-copyfile.c
Refs: https://github.com/libuv/libuv/pull/1465
> unix: add UV_FS_COPYFILE_FICLONE support

- src/win/internal.h
- src/win/pipe.c
- src/win/tcp.c
cc @bzoz 
The patch itself is complete, but I haven't actually tested compatibility with older node versions.
> win,pipe: restore compatibility with the old IPC framing protocol

- test/test-process-priority.c
cc: @bzoz 
Refs: https://github.com/nodejs/node/pull/22817
Refs: https://github.com/libuv/help/issues/64
Passing CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1037/
> test: handle uv_os_setpriority() windows edge case

- Makefile.am
As pointed out in https://github.com/libuv/libuv/pull/2148#discussion_r248501753
> build: wrap long lines in Makefile.am

- Makefile.am
Refs: https://github.com/libuv/libuv/pull/2198#issuecomment-466118047
> build: add missing header

- docs/src/misc.rst
- include/uv.h
- src/unix/core.c
- src/uv-common.c
- src/win/util.c
- test/test-env-vars.c
Fixes: https://github.com/libuv/libuv/issues/2400
~TODO: windows.~
> unix,win: add ability to retrieve all env variables

- .github/stale.yml
Let The Purge begin!
/cc @libuv/collaborators WDYT? (happy to bikeshed on the values, I just picked some that I felt were ok as a starting point)
> misc: enable stalebot

- CMakeLists.txt
- Makefile.am
- docs/src/misc.rst
- include/uv.h
- src/random.c
- src/threadpool.c
- src/unix/internal.h
- src/unix/linux-syscalls.c
- src/unix/linux-syscalls.h
- src/unix/random-devurandom.c
- src/unix/random-getentropy.c
- src/unix/random-getrandom.c
- src/unix/random-sysctl.c
- src/win/internal.h
- src/win/util.c
- src/win/winapi.c
- src/win/winapi.h
- test/test-list.h
- test/test-random.c
- test/test-threadpool-cancel.c
- test/test.gyp
- uv.gyp
Add an API for obtaining cryptographically strong random data from the
system PRNG.
Refs: https://github.com/libuv/libuv/pull/1055
CI: https://ci.nodejs.org/job/libuv-test-commit/1437/ (still need to figure out why random_sync fails on Windows)
> unix,win: add uv_random()

- test/test-fs-event.c
Refs: https://github.com/libuv/libuv/issues/2491
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1610/
> Fix watch file tests on macOS

- src/unix/fs.c
The Unix/macOS `uv__fs_copyfile()` implementation falls back to using `uv_fs_sendfile()`. This commit refactors the error handling to use the `sendfile()` `req`'s `result` field, which is a `ssize_t` instead of using the return value, which is an `int`. The `int` value was coming back as a negative number for large files on some machines.
Refs: https://github.com/nodejs/node/issues/30085
CI: https://ci.nodejs.org/view/libuv/job/libuv-test-commit/1620/
EDIT: The CI has no new failures. I also ran Node's copyfile tests, as well as verifying that this fixed the linked Node issue.
> unix: refactor uv__fs_copyfile() logic

- MAINTAINERS.md
Thank you for inviting me to join.
> doc: add richardlau to maintainers

- src/unix/aix-common.c
Changes based on code in `src/unix/bsd-ifaddrs.c`.
https://github.com/libuv/libuv/blob/f9618443920fd0cbd3ab11c9d37c1f24a7aa1067/src/unix/bsd-ifaddrs.c#L128-L143
Spotted the physical addresses were always `00:00:00:00:00:00` on AIX.
e.g. (v1.x) https://ci.nodejs.org/job/libuv-test-commit-aix/1668/nodes=aix72-xlc-ppc64/console
```console
```
compared to (for this PR) https://ci.nodejs.org/job/libuv-test-commit-aix/1670/nodes=aix72-xlc-ppc64/console
```console
```
(Both running on `test-osuosl-aix72-ppc64_be-2`:
```console
$ netstat -ni
Name  Mtu   Network     Address            Ipkts Ierrs    Opkts Oerrs  Coll
en0   1500  link#2      5a.c6.c5.74.19.2         38611838     0         10522321     0     0
en0   1500  140.211.9   140.211.9.30             38611838     0         10522321     0 …
```
> aix: fix setting of physical addresses

- src/unix/linux-core.c
Alternative to #2580 that doesn't break ABI.
CI: https://ci.nodejs.org/job/libuv-test-commit/1665/
> unix: suppress -Waddress-of-packed-member warning

- src/win/core.c
This assert was stronger than necessary (we assert the actual condition
later in this function). And it's vulnerable to a race condition
occurring in uv__work_done where we drain the work queue but still have
a stale message on this object.
Fixes: https://github.com/libuv/libuv/issues/2610
CI: https://ci.nodejs.org/job/libuv-test-commit/1692/
> fix win32 threadpool_cancel test flakiness

- common.gypi
- test/test-poll-close-doesnt-corrupt-stack.c
- test/test-poll-closesocket.c
~~CI: https://ci.nodejs.org/job/libuv-test-commit/1684/~~
CI: https://ci.nodejs.org/job/libuv-test-commit/1685/
> test: fix -fno-common build errors

- test/test-udp-ipv6.c
We seem to be receiving unrelated network traffic from other libuv
tests. Add some debugging output, in case that happens in the future,
and filter out any messages received that we didn't send.
Fixes: https://github.com/libuv/libuv/issues/2130
Fixes: https://github.com/libuv/libuv/issues/2467
CI: https://ci.nodejs.org/job/libuv-test-commit/1700/
> test,udp6: fix udp_ipv6 test flakiness

- CMakeLists.txt
- Makefile.am
- src/win/core.c
- test/test-async-multi.c
- test/test-list.h
- test/test.gyp
> adds check so we only queue one copy of the async wakeup request

- CMakeLists.txt
CI: https://ci.nodejs.org/job/libuv-test-commit/1830/
> build: make cmake build benchmarks

- src/win/poll.c
No functional changes, just deduplicating code and moving it around.
CI: https://ci.nodejs.org/job/libuv-test-commit/1805/
> win: DRY poll.c

- src/unix/async.c
Fixes: https://github.com/libuv/libuv/issues/2769
CI: https://ci.nodejs.org/job/libuv-test-commit/1867/
Good: doesn't regress multi-CPU performance
Good: improves single-CPU performance (`taskset 1`) of the `async1` benchmark by 12%
Bad: decreases single-CPU performance of `async2` by 16% and `async4` by 5%
`async8` times out in both cases. I guess that counts as "no regression." :-)
> unix: yield cpu when spinlocking on async handle

- CMakeLists.txt
- Makefile.am
- src/unix/stream.c
- src/win/tcp.c
- test/echo-server.c
- test/test-list.h
- test/test-not-readable-nor-writable-on-read-error.c
- test/test-not-readable-on-eof.c
- test/test-not-writable-after-shutdown.c
Rebased copy of #1825 with some minor style cleanup
> unix,stream: clear read/write states on close

- docs/src/misc.rst
get total/free memory documentation more descriptive 😎
> docs: get memory doc more descriptive

- src/win/fs.c
close https://github.com/libuv/libuv/issues/2499
> win,fs: use CreateDirectoryW instead of _wmkkdir

- src/win/fs.c
It is easy to miss that this is accessing MSVC state, while several
users of it were only setting GetLastError.
Refs: https://github.com/libuv/libuv/pull/2921
CI: https://ci.nodejs.org/job/libuv-test-commit/1977/
> win,fs: avoid implicit access to _doserrno

- CMakeLists.txt
MSVC on chinese windows need flag `/utf-8` .
close #2887
> Fix compile error C2001 on chinese windows.

- docs/src/udp.rst
Refs: https://github.com/libuv/libuv/pull/2836
> doc: correct UV_UDP_MMSG_FREE version added

- .mailmap
- AUTHORS
I've changed employer. Update my contact information accordingly.
> mailmap: update contact information for richardlau

- docs/src/errors.rst
- include/uv.h
- include/uv/errno.h
Refs: https://github.com/nodejs/node/pull/38159#discussion_r610288214
> include: add EOVERFLOW status code mapping

- src/unix/core.c
Fixes: https://github.com/libuv/libuv/issues/3174
> unix: fix errno handling in uv__getpwuid_r

- docs/src/stream.rst
> Document that uv_read_stop always succeeds

- src/unix/freebsd.c
Fixes: https://github.com/libuv/libuv/issues/3155
> freebsd: fix incompatible pointer type

- src/win/fs.c
- test/test-fs-open-flags.c
This reverts commit 93942168281680bca60ddbd8d4c596fabcb8efd9.
> Revert "win,fs: correct error code in uv_fs_read and uv_fs_write"

- LINKS.md
- README.md
- docs/src/guide/introduction.rst
- docs/src/index.rst
Copied from https://github.com/libuv/libuv/wiki/Projects-that-use-libuv
> docs: move list of project links under PR control

- test/runner-unix.c
Hello! 
I think there are some pointer arithmetic mistakes in the lines 200 and 326. Since vec is pointer to the process_info_t,  we only need to add i to this instead of i * sizeof(process_info_t).
> Bug: Wrong pointer arithmetic

- src/unix/thread.c
Prior to this patch a race condition may occur
in case a thread tries to destroy the barrier
while other awaiting threads were not
notified. Since the internal mutex and
condition variables are destroyed this may
cause an undefined behavior as described
by the man pages.
So in order to prevent such scenarios the
detroy function will not wait until all
awaiting threads are finished before
proceeding.
Closes: #3102
> darwin: fix uv_barrier race condition

- src/win/atomicops-inl.h
Don't use x86 inline assembly in these cases, but fall back to `__sync_fetch_and_or`, similar to `_InterlockedOr8` in the MSVC case.
This corresponds to what is done in src/unix/atomic-ops.h, where ARM/AArch64 cases end up implementing `cmpxchgi` with `__sync_val_compare_and_swap`.
> mingw: Fix building for ARM/AArch64

- src/unix/process.c
- src/unix/thread.c
- test/run-tests.c
- test/test-spawn.c
Refs: https://github.com/libuv/libuv/issues/2655 (fixes one issue)
> [v2] threads,android: use syscall directly for affinity

- docs/src/guide/basics.rst
> docs: fix information about scheduling

- src/unix/process.c
Years ago, we found that various kernels (linux, macOS) were known to
fail if they try to deliver a signal during this syscall, so we prevent
that from happening. They may have fixed those issues, but it is
generally just a bad time for signals to arrive (glibc blocks them here,
in posix_spawn for example, and even includes some more internal ones
that it won't let us touch here--but it is also using vfork, which has
additional constraints and requirements).
Refs: https://github.com/timholy/IProfile.jl/issues/16
This was initially https://github.com/JuliaAttic/libuv-archive/commit/c45ec4715ecaf6f5ae01e8a760db54283e9b27d5, but has been modified a few times since (particularly here).
> unix: protect fork in uv_spawn from signals

- CMakeLists.txt
Fixes #3074 as discussed with @XeCycle.
Thanks!
> Use standard installation layout

- src/unix/fs.c
It's been reported that copy_file_range() on a CIFS mount fails with
an EPERM error, even though the source and target files have the
appropriate permissions.
This is probably a variation on the EPERM error that libuv handles when
it tries to fchmod() a file on a CIFS mount that hasn't been mounted
with the "noperm" option, so let's handle it here too.
This commit applies minor refactoring because the "work around file
system bugs" section got quite unwieldy.
I also snuck in a bug fix where the workaround for buggy CephFS mounts
disabled copy_file_range() permanently.
Fixes: https://github.com/libuv/libuv/issues/3322
> linux: work around CIFS EPERM bug

- ChangeLog
The release tool was having a tough day.
> doc: fix v1.43.0 changelog entries

- src/unix/stream.c
macOS versions 10.10 and 10.15 - and presumbaly 10.11 to 10.14, too -
have a bug where a race condition causes the kernel to return EPROTOTYPE
because the socket isn't fully constructed.
It's probably the result of the peer closing the connection and that is
why libuv translates it to ECONNRESET.
Previously, libuv retried until the EPROTOTYPE error went away but some
VPN software causes the same behavior except the error is permanent, not
transient, turning the retry mechanism into an infinite loop.
Refs: https://github.com/libuv/libuv/pull/482
Refs: https://github.com/libuv/libuv/pull/3405
> darwin: translate EPROTOTYPE to ECONNRESET

- src/win/thread.c
> issue about C90

- src/idna.c
error C4146: unary minus operator applied to unsigned type, result still unsigned
> Fix error C4146 on MSVC

- src/unix/freebsd.c
- src/unix/fs.c
- src/unix/internal.h
> unix: uv__fs_sendfile using copy_file_range on FreeBSD 13 and above

- src/unix/process.c
This is a commit series to re-enable the usage of posix_spawn on macOS.
CI: https://ci.nodejs.org/job/libuv-test-commit-osx-cmake/359/
CI+node: https://ci.nodejs.org/job/libuv-in-node/191/
> posix spawn, take 2

- src/unix/process.c
Small improvement suggested in #3257
> process: simplify uv__write_int calls

- src/unix/udp.c
- test/test-udp-connect.c
- test/test-udp-connect6.c
Issue: https://github.com/libuv/libuv/issues/3560
> IBMi: Implement UDP disconnect

- src/unix/core.c
As suggested in https://github.com/libuv/libuv/pull/3523#discussion_r821550169 @bnoordhuis
> unix: simplify getpwuid call

- .github/workflows/CI-win.yml
I got the conditional reversed in https://github.com/libuv/libuv/pull/3564
> build: re-enable CI for windows changes

- test/test-fs-event.c
FSEvents on macOS sometimes sends one change event, sometimes two.
Make the test more lenient.
Fixes #3589.
> test: fix flaky file watcher test

- configure.ac
- m4/libuv-check-flags.m4
Issue: https://github.com/libuv/libuv/issues/3573
> Aix: Fix xlc autotools build

- test/test-embed.c
- fix busy loop
- fix multi-thread race conditions
- reduce amount of platform-specific code
Fixes: https://github.com/libuv/libuv/issues/3606
> test: rewrite embed test

- src/unix/core.c
Use MSG_CMSG_CLOEXEC on Unix-y platforms that support it (all except
macOS and SunOS spawn.)
Remove the feature test for Linux. Libuv's kernel baseline is 2.6.32
and MSG_CMSG_CLOEXEC was added in 2.6.23.
> unix: use MSG_CMSG_CLOEXEC where supported

- src/unix/tty.c
EINTR is explicitly documented as a possible error code of tcsetattr().
The documentation for tcgetattr() is silent on the subject but better
safe than sorry.
Fixes: https://github.com/libuv/libuv/issues/3645
> unix: retry tcgetattr/tcsetattr() on EINTR

- docs/src/guide/introduction.rst
> docs: update introduction.rst

- src/win/util.c
Another thread can change the working directory between calls to
GetCurrentDirectoryW().
The first call was used to determine the size of the buffer to use in
the second call. Retry if the reported size does not match the expected
size because the buffer's contents is undefined in that case.
> win: fix thread race in uv_cwd() and uv_chdir()

- docs/src/fs.rst
> Add notes about negative offsets used in read/write filesystem functions

- src/unix/kqueue.c
Remove the TODO that says to batch up kevent(EV_DELETE) system calls. It's unduly complicated in case of errors.
If you pass an out array to kevent(), it will store error records that tell you which file descriptor caused the error but it also stores new events in the array, complicating state management.
If you don't pass an out array, it simply doesn't tell you anything except that _something_ failed. Optimistically trying batch deletion and falling back to one-by-one deletion is probably possible but is something of a deoptimization and also feels somewhat dangerous.
macOS has a mostly-undocumented kevent_qos() system call that accepts a KEVENT_FLAG_ERROR_EVENTS flag that fixes the first problem but that of course isn't portable.
Long story short, it seems like too much hassle for too …
> kqueue: DRY file descriptor deletion logic

- src/unix/linux-core.c
Fixes: https://github.com/libuv/libuv/issues/2315
cc @maleadt - I figured it'd be easier to type it out than having you jump through more hoops.
> linux: teach uv_get_constrained_memory() cgroupsv2

- CMakeLists.txt
- Makefile.am
- src/unix/stream.c
- test/test-list.h
- test/test-tcp-write-in-a-row.c
Resolve https://github.com/libuv/libuv/issues/3668
Follow https://github.com/libuv/libuv/pull/3723 reviewer's suggestions, merge to v1.x rather than master.
> stream: process more than one write req per loop tick

- .github/workflows/CI-win.yml
- CMakeLists.txt
Fixes: https://github.com/libuv/libuv/issues/3682
Requires fixing https://github.com/libuv/libuv/issues/3691
> build: support AddressSanitizer on MSVC

- src/win/pipe.c
In the old version of uv_pipe_open, the parent process ID is used by default. If the open pipe is used in the same process, the parent process will be obtained incorrectly.
Now we first get the client pid and compare it with its own pid. If it is the same, then get the server pid. If the two are the same, then the pipe is from the same process.
> win: Optimize the method of obtaining ipc_remote_pid

- include/uv.h
- include/uv/errno.h
Fixes: https://github.com/libuv/libuv/issues/3795
> include: map ENODATA error code

- docs/src/fs.rst
- docs/src/guide/networking.rst
- src/win/poll.c
- src/win/tcp.c
- src/win/util.c
- test/test-fs.c
Our minimum requirements are Windows 8 now.
> win: drop code checking for Windows XP / Server 2k3

- docs/src/threading.rst
- include/uv.h
- src/unix/thread.c
- src/win/thread.c
- test/test-thread-affinity.c
Add uv_thread_getcpu() api to get the cpu number on which the calling thread is running.
> thread: add uv_thread_getcpu()

- CMakeLists.txt
- Makefile.am
- src/win/internal.h
- src/win/pipe.c
- src/win/stream.c
- test/test-list.h
- test/test-pipe-try-write.c
I've taken @bnoordhuis code from https://github.com/libuv/libuv/pull/888 and [have modernized the tests](https://github.com/libuv/libuv/commit/9e3f220b09357a34b28ce57e4c8dd23bbdb96bf5) and tried to [fix the issues it had](https://github.com/libuv/libuv/commit/43b5141db8efc1bb512a44f96e5e631bc2155e5d).
> win: implement uv_try_write() for pipes (take 2: it was pr #888)

- src/unix/linux.c
Drop support for old kernels. Assume support for CLOCK_BOOTTIME.
> linux: simplify uv_uptime()

- .github/workflows/CI-docs.yml
Taken from #3570. I assume it should be non-controversial, so I will merge when it passes CI.
> docs: add CI for docs PRs

- src/unix/async.c
The current fix (libuv#2231) was found to be slow in certain cases. This change should improve scalabaility a bit by only incurring the spin loop delay while closing an UV_ASYNC. It also is intended to slightly improve the behavior after uv_loop_close is called, by parking all of the pending flags as set, so that it will not access the loop at all (until the uv_async_t memory is freed, which we leave still to the responsibility of the user).
Takes some inspiration from https://github.com/libuv/libuv/pull/2654
Takes some inspiration from https://github.com/libuv/libuv/pull/2656
Refs: https://github.com/libuv/libuv/pull/2231
> unix: remove busy loop from uv_async_send

- docs/src/fs.rst
> doc: document uv_fs_cb

- .github/workflows/sanitizer.yml
- test/test-eintr-handling.c
- test/test-fork.c
- test/test-fs.c
- test/test-ipc-send-recv.c
- test/test-signal-multiple-loops.c
- test/test-tcp-writealot.c
- tsansupp.txt
Refs: https://github.com/libuv/libuv/issues/3681
<hr>
Not completely ready, see discussion in the linked issue.
> build: promote tsan ci to must-pass

- .github/workflows/CI-unix.yml
- src/unix/core.c
- src/unix/internal.h
- src/unix/thread.c
- test/task.h
- test/test-fs.c
- test/test-get-currentexe.c
- test/test-gethostname.c
- test/test-metrics.c
- test/test-tcp-rst.c
- test/test-udp-connect.c
- test/test-udp-connect6.c
- test/test-udp-multicast-join.c
There are some existing test failures on both OSes, and I've adjusted some of the asserts so it's easier to see why they're failing.
I'll try to find some time to look into the failures, but I thought it would be better to have this up for discussion rather than delay it due to those.
Closes #3510
> build: add CI for OpenBSD and FreeBSD

- test/test-tty.c
Fixes: https://github.com/libuv/libuv/issues/3894
> test: remove bad tty window size assumption

- test/test-condvar.c
Remove expectations around uv_cond_timedwait() maximum sleep time.
The OpenBSD buildbot sleeps more than 5x longer than requested. It no longer makes sense to expect some reasonable upper bound because at that point we've moved well beyond reasonable.
Fixes: https://github.com/libuv/libuv/issues/3896
> test: remove timing-sensitive check

- src/unix/fsevents.c
ThreadSanitizer complains about unsynchronized access to the handle->loop->cf_state pointer.
The warning is probably benign but the fsevents thread already knows the pointer. It doesn't have to read it, it just needs to propagate it.
Refs: https://github.com/libuv/libuv/issues/3880
> macos: fix fsevents thread race conditions

- test/test-fs.c
https://ci.nodejs.org/view/libuv/job/libuv-test-commit/2266/
> test: fix visual studio 2015 build error

- docs/src/misc.rst
Fixes: https://github.com/libuv/libuv/issues/3928
> doc: consistent single backquote in misc.rst

- src/unix/linux.c
Libuv no longer supports such kernels so the workaround can be removed.
> linux: remove bug workaround for obsolete kernels

- src/unix/fs.c
> macos: fix source not being followed when cloning

- MAINTAINERS.md
Move Bert and Fedor to emeriti.
> doc: update active maintainers list

- src/unix/linux.c
Handle wraparound properly, otherwise we may end up overwriting elements that have not been consumed by the kernel yet.
> linux: fix logic bug in sqe ring space check

- src/unix/stream.c
Libuv makes no claim to being strict aliasing-clean but type punning makes me feel unclean so replace it with memcpy().
> unix: use memcpy() instead of type punning

- src/unix/stream.c
Instead of suppressing the VLA warning, use a fixed-size buffer that is big enough to receive at least one control message but not so big that IBMi PASE rejects it.
> unix: remove clang compiler warning pragmas

- src/win/process.c
close https://github.com/libuv/libuv/issues/3992
> win: improve mingw build

- test/test-fs.c
Fixes: https://github.com/libuv/libuv/issues/3995
> test: fix -Wbool-compare compiler warning

- .mailmap
- AUTHORS
- ChangeLog
- configure.ac
- include/uv/version.h
Finalize `v1.45.0`. ALready tagged, pushed and artifacts published, but the `v1.x` branch is protected so I need a PR for this.
> Release v1.45.0

- .readthedocs.yaml
Now required: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
> misc: update readthedocs config

- src/unix/fs.c
- src/unix/internal.h
- src/unix/linux.c
- src/uv-common.h
- test/test-threadpool-cancel.c
Specifically: `link`, `mkdir`, `rename`, `symlink` and `unlink`.
> linux: add some more iouring backed fs ops

- include/uv.h
I believe it's fair to say at this point that these functions are not going to be removed in v0.12. They are still deprecated though.
> include: update outdated code comment

- include/uv/unix.h
- src/unix/linux.c
This commit is adding support for LoongArch architecture.
> Add support for LoongArch

- LINKS.md
> Update LINKS.md; add DPS8M

- src/unix/process.c
- test/runner-unix.c
- test/test-fork.c
- test/test-pipe-close-stdout-read-stdin.c
Details: https://github.com/libuv/libuv/issues/4042
> unix: skip prohibited syscalls on tvOS and watchOS

- configure.ac
- include/uv/version.h
Fixes: https://github.com/libuv/libuv/issues/4060
> Now working on version 1.46.1

- test/test-thread-affinity.c
Fixes: https://github.com/libuv/libuv/issues/4080
> test: fix license blurb

- src/unix/linux.c
Those kernels have a known resource consumption bug where the sqpoll thread busy-loops.
Fixes: https://github.com/libuv/libuv/issues/4089
> linux: don't use io_uring on pre-5.10.186 kernels

- src/unix/linux.c
In Ubuntu, the kernel version reported by `uname()` follows the versioning format that Ubuntu uses for their kernels which does not have a direct correspondence with the mainline kernel version they're based on. Get that version from `/proc/version_signature` as documented in:
https://wiki.ubuntu.com/Kernel/FAQ#Kernel.2FFAQ.2FGeneralVersionRunning.How_can_we_determine_the_version_of_the_running_kernel.3F
> unix: get mainline kernel version in Ubuntu

- .github/workflows/CI-unix.yml
The version of the deb package has changed to 7.2.
> build: fix qemu install in CI-unix workflow

- src/unix/tcp.c
Add PASE implementation of ifaddrs, getifaddrs, freeifaddrs
Part of https://github.com/libuv/libuv/issues/4117
> ibmi: implement ifaddrs, getifaddrs, freeifaddrs

- src/unix/fs.c
- android ndk 24 has preadv, no need for #ifdef guards
- macos 11 has preadv/prwitev, ditto
<hr>
> unix: remove pread/preadv conditionals

- src/unix/fs.c
We can use the |bufs| argument directly instead of always copying it and sometimes heap-allocating it.
The same trick doesn't work for uv_fs_write() because the iterator mutates the buffers in the list and that's visible to the caller.
Fixes: https://github.com/libuv/libuv/issues/4038
> unix: don't malloc on sync uv_fs_read

- docs/src/guide/processes.rst
I took the liberty to create the PR for this documentation issue feel free to give any feedbacks
> doc: uv_close should be called after the exit callback (#1911)

- docs/src/fs_event.rst
Refs: https://github.com/libuv/libuv/issues/4160
> doc: filename arg to uv_fs_event_cb can be NULL

- test/test-tcp-connect6-error.c
Fixes: https://github.com/libuv/libuv/issues/4211
> test: check if ipv6 link-local traffic is routable

- .gitignore
Per https://github.com/libuv/libuv-release-tool/pull/19
> misc: ignore libuv-release-tool files

- src/unix/linux.c
Introduced long ago for old Linux/libc flavors libuv no longer supports.
We include <ifaddrs.h> unconditionally elsewhere so there is no point in special-casing it here.
Fixes: https://github.com/libuv/libuv/issues/4242
> linux: remove HAVE_IFADDRS_H macro

- src/win/process.c
Per documentation, this was the wrong way to test for ESRCH. This hopefully fixes it.
Fixes: https://github.com/libuv/libuv/issues/4300
> win: fix ESRCH implementation

- CMakeLists.txt
Adding support for issue https://github.com/libuv/libuv/issues/4282
> Adding alias for libuv

- src/unix/linux.c
It's been reported that creating many event loops introduces measurable overhead now that libuv creates an sqpoll-enabled ring.
I don't really see any change in CPU time with or without this change but deferring ring creation until it's actually used seems like a good idea, and comes with no downsides that I can think of, so let's do it.
Fixes: https://github.com/libuv/libuv/issues/4308
cc @isilence
> linux: create io_uring sqpoll ring lazily

- .github/workflows/CI-sample.yml
Seems silly to only have a rule that says not to run this if the docs code changes.
> misc: run sample CI when code changes

- src/win/process.c
Remove it since it can cause stack overflows. Use heap allocation instead.
Fixes: https://github.com/libuv/libuv/issues/4348
> win: remove _alloca usage

- src/unix/fs.c
I removed the fallback code back in October but it prevents Node.js from upgrading libuv in their v20.x release line because they support systems older than we do. Bring back a dlsym-based fallback path.
Fixes: https://github.com/libuv/libuv/issues/4332
> unix: reinstate preadv fallback code

- include/uv/win.h
- src/win/thread.c
InitOnceExecuteOnce is available in Windows >= Vista.
Ref: https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-initonceexecuteonce
> win: simplify uv_once implementation

- src/unix/udp.c
Benchmarking shows that sendmsg() is persistently around 1% faster for single datagrams, and that kind of stands to reason because there is less setup overhead, and the kernel has to copy in less data.
Fixes: https://github.com/libuv/libuv/issues/4320
<hr>
Commit log should really read `freebsd,linux:` but then it won't fit in 50 columns anymore :cry:
> linux: don't use sendmmsg() for single datagrams

- src/unix/stream.c
The file descriptor leak in the inner path was pointed out by @theanarkh and I subsequently spotted another one in the outer loop. Rewrite the function to process all control messages.
Refs: https://github.com/libuv/libuv/pull/4357
> unix: fix fd leaks in SCM_RIGHTS error path

- .github/dependabot.yml
This will auto-update our github-actions scripts via PR whenever a new version is released (on a weekly basis, and immediately after merging)
> Create dependabot.yml for updating github-actions

- src/unix/freebsd.c
> Fix compilation failure on DragonFly BSD

- src/unix/darwin-syscalls.h
- src/unix/internal.h
- src/unix/udp.c
adds mmsg support to darwin platform using internal sendmsg_x / recvmsg_x functions
> udp: add mmsg support to darwin

- src/unix/core.c
This PR expands the `uv_available_parallelism()` to natively support more platforms:
- FreeBSD
- NetBSD
- OpenBSD + macOS
> unix: expand uv_available_parallelism() to support more platforms

- README.md
Refs: https://github.com/libuv/libuv/issues/4532
> doc: add known issue in armv7

- src/unix/core.c
> Fix build on NetBSD

- LINKS.md
> Add scala-native-loop

- src/unix/kqueue.c
Along with the improvement of code simplicity.
> kqueue: merge kevents for uv__io_check_fd to lower overhead

- src/unix/kqueue.c
Refs: https://github.com/libuv/libuv/issues/3947
> kqueue: replace EV_OOBAND handling with EVFILT_EXCEPT + NOTE_OOB

- src/unix/kqueue.c
Unsupported on FreeBSD, breaking the build.
This reverts commit b1d30f9489771a295c1d9b06402e49a77b3e91e6.
> Revert "kqueue: change EV_OOBAND to EVFILT_EXCEPT+NOTE_OOB (#4597)"

- CMakeLists.txt
- Makefile.am
- SUPPORTED_PLATFORMS.md
- include/uv/win.h
Fixes: https://github.com/libuv/libuv/issues/3889
<hr>
There's probably more that can be simplified now. Suggestions?
> win: drop support for windows 8

- src/unix/linux.c
Libuv looks for "Processor" in /proc/cpuinfo but it's been reported that on at least some Raspberry Pi models, it's called "model name". Look for both.
Fixes: https://github.com/nodejs/node/issues/56105
> linux: fix uv_cpu_info() arm cpu model detection

- src/win/core.c
- src/win/winapi.c
- src/win/winapi.h
It was introduced in Vista, so we can assume it's always there now.
> win: use GetQueuedCompletionStatusEx directly

- SUPPORTED_PLATFORMS.md
- include/uv/win.h
- src/win/winapi.h
- src/win/winsock.h
- test/test-spawn.c
The OG MinGW has been dead for years, MinGW-w64 has taken its place.
> win: drop support for the legacy MinGW

- test/test-udp-mmsg.c
Replace comparison of `alloc_cb_called` with the total bytes read (`read`) to validate the test's correctness.
Fixes: https://github.com/libuv/libuv/issues/4650
> test: fix flaky flaky udp_mmsg test

- test/test-udp-multicast-join6.c
Fixes: https://github.com/libuv/libuv/issues/4651
> test: test: fix udp-multicast-join for FreeBSD

- src/win/fs-event.c
Fixes: https://github.com/libuv/libuv/pull/4376#issuecomment-2544728609
> win: fix leak processing fs event

- src/win/util.c
Fixes: https://github.com/libuv/libuv/issues/4680
> win: fix leak in uv_os_tmpdir

- src/win/process.c
The CreateProcess API on Windows is still not longPathAware, even if the process itself is. So, if the cwd used for CreateProcess is too long, then the call fails with a 'INVALID_DIRECTORY' error.
To deal with this, check the length of the cwd and shorten it if it is longer than MAX_PATH.
This fixes #4684
> Check cwd length before spawning on win32

- src/unix/core.c
> unix: enable getrusage for SunOS

- src/unix/aix.c
- src/unix/ibmi.c
Refs: https://github.com/libuv/libuv/pull/4724
Fixes: https://github.com/libuv/libuv/issues/4729
---
Test CIs:
- AIX: https://ci.nodejs.org/job/libuv-test-commit-aix/2638/nodes=aix72-ppc64/console
- IBM i: https://ci.nodejs.org/job/libuv-test-commit-ibmi/1691/nodes=ibmi74-ppc64/console
> unix: fix undeclared identifiers

- CMakeLists.txt
Fixes: https://github.com/libuv/libuv/issues/4734
> build: use `-lm` in FreeBSD

- src/unix/kqueue.c
> kqueue: use uv__io_init_start to simplify fs event watcher setup

- test/runner.h
---
Trivial patches are my passion.
> test: remove unused include of <limits.h> in runner.h

- test/test-spawn.c
Introduced in commit 2545ffe74 from last month.
> test: pass correct string type to GetModuleHandleW

- src/win/fs.c
Refs: https://github.com/libuv/libuv/issues/4819
> win: remove unnecessary inlining from fs.c

- src/win/core.c
- src/win/req-inl.h
Refs: https://github.com/libuv/libuv/issues/4819
> win: move uv__process_reqs to core.c

- src/win/fs-fd-hash-inl.h
Refs: https://github.com/libuv/libuv/issues/4819
> win: remove unnecessary inlining from header file

- src/win/fs.c
Wine has a bug (https://bugs.winehq.org/show_bug.cgi?id=50771) where FILE_WRITE_ATTRIBUTES will cause CreateFile to fail if the file is read-only. The recommended work around is to instead use FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE, which we do as of #4318. However, we were still using FILE_WRITE_ATTRIBUTES to create the initial handle, despite this no longer being required, except for the fallback path. As a result, libuv is still broken under wine, even on master. Fix this by removing the `FILE_WRITE_ATTRIBUTES` from the initial CreateFile call and re-opening the handle in the fallback path if necessary. Note that we still have the same issue in fs_chmod and I've requested some guidance from wine on what to do about this, but this should at least fix unlink.
Ref …
> win,fs: Avoid FILE_WRITE_ATTRIBUTES in unlink to work around wine bug

- test/test-idna.c
Fixes: https://github.com/libuv/libuv/issues/4865
> test,win: fix -Wattributes warnings

- docs/src/udp.rst
- include/uv.h
- src/unix/udp.c
- src/win/udp.c
Fixes: https://github.com/libuv/libuv/issues/4551
> unix,win: implement `uv_udp_open_ex`
